### ISSUE TITLE
Include dists

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#101]
It's becoming clearer that this module will need dists  to be useful as a node module.

**Comment by tmcw** [comment]
Not going to do it.

**Comment by ansis** [comment]
@tmcw why not?

To me it would make more sense to include the latest release in the root than `dist/dev`

**Comment by tmcw** [comment]
Because of the tagging timewarp; we need to tag package.json in git with, say, `v0.6.7` in order to build v0.6.7, and thus cannot include dists of v0.6.7 in the tag of v0.6.7 without going back in time, untagging and retagging with the new dist.

**Comment by ansis** [comment]
Why do we need the build script to handle checking out a tag? Why not just have it build to the root and let anyone who wants to rebuild an old version just checkout the tag first (and for new versions it would already be in the commit)? Building old versions seems like an odd case to handle in the build script
