### ISSUE TITLE
Issue with map panning when opening a custom popup

### ISSUE THREAD

**Issue by arnochauveau** [mapbox/mapbox.js#1011]
I have markers with custom popups bound to them like this:

``` javascript
marker.bindPopup('<h2 class="popup">' + obj.name + '</h2>'
        + '<div class="popup">'
        + '<img class="popupimg" src=".' + obj._image_url + '" />'
        + '<div>'
        +  showbrands(obj) 
        + '<p>' + obj.adress + '</p>' 
        + getwordpresslink(obj)
        + '</div>'
        + '</div>');

marker.on('click', openPopup);
```

however when I open a marker that is close to the border the map pans like this: 

![wrong_pan](https://cloud.githubusercontent.com/assets/4454851/7809353/c9507484-0399-11e5-8c8d-17c8480136e1.gif)

and when I click a second time it works as expected:

![rigth_pan](https://cloud.githubusercontent.com/assets/4454851/7809369/decac17a-0399-11e5-8339-319fa7f6be49.gif)

if I close it again and reopen it, it also works as expected...

I think the issue is that the popup doesn't know the height of the image and thus doesn't include the image height in the popup height which results in the map not panning enough...

Is there a workaround or fix for this problem?

**Comment by jfirebaugh** [comment]
> Is there a workaround or fix for this problem?

Yep: include explicit `width=` and `height=` attributes in the `img` tag.

**Comment by arnochauveau** [comment]
that seems to work! thank you very much!
