### ISSUE TITLE
Turf examples are broken

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox.js#1014]
- https://www.mapbox.com/mapbox.js/example/v1.0.0/turf-concave/
- https://www.mapbox.com/mapbox.js/example/v1.0.0/turf/

They reference `https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v2.0.2/turf.min.js`, which doesn't exist... yet. I'll fix this by deploying v2.0.2.

cc @lyzidiamond: https://github.com/mapbox/mapbox.js/commit/3627817d9829424253d4db4651905ac37c641006

**Comment by lyzidiamond** [comment]
Oh! Snaps! Sorry about that. Nice catch @aaronlidman.

**Comment by aaronlidman** [comment]
Fixed with: https://github.com/mapbox/mapbox.js-plugins/commit/be6dba9392d28eda6585d05d185d88cfea8dc557
