### ISSUE TITLE
Zooming in/out the map with lot of markers cause app to memory leak.

### ISSUE THREAD

**Issue by j16h** [mapbox/mapbox.js#1017]
Hi guys,

You have to add lot's of markers on the map and continuously zoom in / zoom out the map.
As a result, you gonna see in the Task Manager that the amount of memory continuously increasing.

Here is my experience a [screenshot](https://www.dropbox.com/s/tl4vs19qtqslvt9/Screen%20Shot%202015-06-01%20at%204.07.21%20PM.png?dl=0) with my app + result of Task Manager.

**Comment by tmcw** [comment]
@mourner this is likely a Leaflet issue?

**Comment by tmcw** [comment]
Closing: this would require more information to debug, and is very likely a Leaflet issue.
