### ISSUE TITLE
expose geocoder autocomplete

### ISSUE THREAD

**Issue by sbma44** [mapbox/mapbox.js#1021]
@ingalls can we get autocomplete functionality exposed in mapbox.js? Per @gundersen this is a priority for Monday, if at all possible. From earlier conversations you made this sound pretty straightforward -- lmk if that's not the case & we'll figure something else out.

**Comment by ingalls** [comment]
Autocomplete is already supported by mapbox.js. When creating an instance of the geocoder-control one simply sets the autocomplete option to true.

`.addControl(L.mapbox.geocoderControl('mapbox.places', { autocomplete: true }));`
