### ISSUE TITLE
Issue with passing proximity param to geocoder.query

### ISSUE THREAD

**Issue by 1parkplace** [mapbox/mapbox.js#1032]
I updated to 2.2.0 and updated my geocoder query code to:
`mapboxMap.geocoder.query({
                query: $("#searchText").val(),
                proximity: L.latLng($('#' + _clientIDs.hdnCenterLat).val(), $('#' + _clientIDs.hdnCenterLng).val())
        }, mapboxMap.geocodeMap);`
Stepping through, I see the object created and the proximity object with populated Lat, Lng values, but the URL that is generated does not have the proximity query string values.

Is there some defunct logic in the URL create? or is there something wrong with my syntax in calling it?

**Comment by ingalls** [comment]
Hey @1parkplace it sounds like the proximity option isn't being turned on when you create instantiate a Geocoder object. If `proximity` is not set to true it is simply ignored when `query()` is called. See [here](https://github.com/mapbox/mapbox.js/blob/mb-pages/API.md#lmapboxgeocoderidurl-options)

Try:

```
var geocoder = L.mapbox.geocoder('mapbox-places', {
    accessToken: ?,
    autocomplete: true,
    proximity: true
})

```

A further example can be found [here](https://github.com/mapbox/mapbox.js/blob/f6c3ffefc69beb35c24c325f0f4635d0273235d7/src/geocoder_control.js#L26-L29)

**Comment by jfirebaugh** [comment]
I'm going to remove the `proximity` option from the `L.mapbox.geocoder` constructor -- as @1parkplace's trouble shows, it's confusing to have to both construct with `proximity: true` and pass `proximity` later on. Passing it later on should be enough.
