### ISSUE TITLE
retire old documentation

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#1037]
https://www.mapbox.com/mapbox.js/api/v1.3.1/ ranks really highly in searches. it is also very very old.

**Comment by lyzidiamond** [comment]
@tmcw So are you thinking anything < 2.0.0?

**Comment by lyzidiamond** [comment]
For the record, I am very :+1: on this, just want to know the scope so we can set next actions and get it done.

**Comment by lyzidiamond** [comment]
Closed via https://github.com/mapbox/www.mapbox.com/pull/5939.
