### ISSUE TITLE
Bring it up to date with Leaflet 1.0

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox.js#1038]
There's a `leaflet-0.8` branch. Time to bring it up to date with Leaflet 1.0 beta 1 which was just released: http://leafletjs.com/2015/07/15/leaflet-1.0-beta1-released.html

**Comment by nakhbari** [comment]
+1

**Comment by TheSisb** [comment]
+1

**Comment by gotjoshua** [comment]
+1

**Comment by tmcw** [comment]
Do not +1 this issue. Mapbox.js tracks _released versions of Leaflet, only_. That does not include beta, rc, -dev, or anything else. When there's a Leaflet 1.0, then we'll update. Until then, we will not.

**Comment by mourner** [comment]
Leaflet 1.0 is out! Let's do this.

**Comment by d3netxer** [comment]
+1

**Comment by tmcw** [comment]
Seriously another +1!? Re-locking.

**Comment by tmcw** [comment]
Closing in favor of #1192.
