### ISSUE TITLE
Using mapbox.js with JSPM not working

### ISSUE THREAD

**Issue by ntilwalli** [mapbox/mapbox.js#1042]
I'm trying to set up a simple test of mapbox.js/jspm/systemjs functionality (taking advantage of the fix in #1008) and I'm consistently running into the error: `Uncaught (in promise) Error: Cannot read property 'baseVal' of undefined`.  My HTML file is very basic:

```
<!doctype html>
<html>
<head>
    <title>Hello, Mapbox!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div id="main"></div>
    <script src='jspm_packages/system.js'></script>
    <script src='config.js'></script>
    <script>
        System.import('main')
    </script>
</body>
</html>
```

And my `main.js` is also very basic:

```
import $ from 'jquery'
import L from 'mapbox.js'

let map;

$(document).ready(function () {
    let mapHost = document.querySelectorAll("#main")
    L.mapbox.accessToken = <insert my MB access token string here>
    map = L.mapbox.map(mapHost, 'mapbox.streets', { zoomControl: false })
    map.setView([22.76, -25.84], 3)
})
```

The full stack trace from Chrome is:

```
Uncaught (in promise) Error: Cannot read property 'baseVal' of undefined
    Error loading http://127.0.0.1:8080/src/main.js
    at Object.L.DomUtil._getClass (http://127.0.0.1:8080/jspm_packages/npm/leaflet@0.7.3/dist/leaflet-src.js:998:22)
    at Object.L.DomUtil.hasClass (http://127.0.0.1:8080/jspm_packages/npm/leaflet@0.7.3/dist/leaflet-src.js:964:29)
    at Object.L.DomUtil.addClass (http://127.0.0.1:8080/jspm_packages/npm/leaflet@0.7.3/dist/leaflet-src.js:974:25)
    at L.Map.L.Class.extend._initLayout (http://127.0.0.1:8080/jspm_packages/npm/leaflet@0.7.3/dist/leaflet-src.js:2022:13)
    at L.Map.L.Class.extend.initialize (http://127.0.0.1:8080/jspm_packages/npm/leaflet@0.7.3/dist/leaflet-src.js:1566:8)
    at L.Map.extend.initialize (http://127.0.0.1:8080/jspm_packages/npm/mapbox.js@2.2.1/src/map.js:31:32)
    at new L.Class.extend.NewClass (http://127.0.0.1:8080/jspm_packages/npm/leaflet@0.7.3/dist/leaflet-src.js:231:20)
    at Object.module.exports.map (http://127.0.0.1:8080/jspm_packages/npm/mapbox.js@2.2.1/src/map.js:174:10)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8080/src/main.js!transpiled:20:20)
    at jQuery.Callbacks.fire (http://127.0.0.1:8080/jspm_packages/github/components/jquery@2.1.4/jquery.js:3099:30)
```

I installed mapbox.js using the command `jspm install npm:mapbox.js`. I am using the Babel transpile functionality in systemjs.  I don't see how that could be interfering.  Is this a bug?

**Comment by tmcw** [comment]
See previous issue https://github.com/mapbox/mapbox.js/pull/1008 and try using the master branch for now?

**Comment by ntilwalli** [comment]
Ah. I mistakenly assumed that #1008 had been merged into what's distributed on npm.  I'll try that.  Thanks.

**Comment by ntilwalli** [comment]
@tmcw That did not solve the issue.  I installed a custom configuration of the package using specifically the `mb-pages` branch and a jspm install override: 

```
jspm install github:mapbox/mapbox.js@mb-pages -o "{ registry: 'npm', main: 'src/index', dependencies: {'corslite': '0.0.6', 'isarray': '0.0.1', 'leaflet': '0.7.3', 'mustache': '0.7.3', 'sanitize-caja': '0.1.3'} }"
```

The only change from above is the line `import L from 'mapbox.js'` was changed to `import L from 'mapbox/mapbox.js'`  I'm getting the same stack trace as above.

**Comment by ntilwalli** [comment]
@tmcw This problem goes away when I create the map using the element id instead of the element reference directly.

Works:

```
    map = L.mapbox.map('main', 'mapbox.streets').setView([22.76, -25.84], 3)
```

Does not work:

```
    let mapHost = document.querySelectorAll("#main")
    map = L.mapbox.map(mapHost', 'mapbox.streets').setView([22.76, -25.84], 3)
```

**Comment by tmcw** [comment]
`let mapHost = document.querySelectorAll("#main")`

querySelectorAll selects a list of nodes, rather than a single node (as implied by the 'all'). If you want the first node with id `#main`, you would

```
map = L.mapbox.map(mapHost[0], 'mapbox.streets').setView([22.76, -25.84], 3)
```

Or use querySelector.

**Comment by ntilwalli** [comment]
Wow.  Totally missed that.  Fixed it.  Thanks so much.

**Comment by tmcw** [comment]
Cool, closing: jspm support will land in the next tag.

**Comment by ntilwalli** [comment]
Looking forward to it.  Thanks again.

**Comment by playground** [comment]
Is there a way to use mapbox with Systemjs without jspm?
