### ISSUE TITLE
Microsoft Edge compat

### ISSUE THREAD

**Issue by csuwildcat** [mapbox/mapbox.js#1043]
Hey there Mapboxers,

I am working on assessing, cataloging, and triaging library compat with Microsoft Edge. Do you know the version compat range for Mapbox in Edge? Are all versions fully operable in Edge? Also, do you have any bugs that block features or compat I can help with or escalate?

**Comment by lucaswoj** [comment]
Thanks for getting in touch with us @csuwildcat! We would love to test [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js) and Mapbox.js in Edge but there doesn't seem to be a way to get Edge running on our end.

> Join the Windows Insider Program to try Microsoft Edge (http://dev.modern.ie)
> 
> We’re very close to the public release of Windows 10 so we’re not onboarding any new PCs to the Windows Insider Program just now. (https://insider.windows.com)
> 
> Microsoft edge isn't a standalone browser. It comes bundled with windows 10 technical preview. You will have to download Windows 10 technical preview latest build to get your hands on Edge. (http://www.quora.com/Can-I-download-Microsoft-Edge-for-my-Windows-8-1-laptop)

Is there any way you can help us out?

**Comment by lucaswoj** [comment]
We have been working on some IE11 WebGL-related performance problems recently (https://github.com/mapbox/mapbox-gl-js/issues/1336). Do you think that this will affect Edge too? Can you provide us any assistance on this?

**Comment by csuwildcat** [comment]
Yes, I'll send a more detailed reply this evening (out of office for the
next few hours).
- Daniel

**Comment by csuwildcat** [comment]
If you just signed up for the Insiders program, you won't have access to the RTM as of last Friday - it was frozen in prep for final release. We're going to have a hard time getting you access to the RTM until Wednesday's release. If Mapbox works reasonably well in IE11, it should be just fine in Edge, as Edge is a 100% standards compliant browser that has robust support for WebGL. If you don't have a machine that already had access to the Insider builds, we can wait until Wednesday and I can immediately triage any issues you find - will that work?

**Comment by lucaswoj** [comment]
Thanks @csuwildcat! 

Mapbox.js, works fine in IE11 and we will let you know if we find any issues when Edge is released.

This project's successor, [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js), has [recently begun having bad rendering performance](https://github.com/mapbox/mapbox-gl-js/issues/1336) (seemingly related to `gl.disableVertexAttribArray`). Based on what you have said, I do not anticipate it will be any better in Edge. I would love some more :eyes: on that issue.

**Comment by lucaswoj** [comment]
@csuwildcat We're starting to get some bug reports related to Microsoft Edge for GL JS. It looks like there are some serious rendering issues. https://github.com/mapbox/mapbox-gl-js/issues/1437

**Comment by tmcw** [comment]
:+1: let's focus efforts on Mapbox GL JS.
