### ISSUE TITLE
Problem with setView on Chrome

### ISSUE THREAD

**Issue by GNURub** [mapbox/mapbox.js#1048]
when i put the center option or i do setView ex: 

``` javascript
 map.setView({lat: 0, lng: 0}, 10);


```

The view dont load, but if i I open a devtool window for example it works, is like it refresh the view![seleccion_385](https://cloud.githubusercontent.com/assets/1318648/9143642/d3cc99b4-3d47-11e5-81b3-7e283a09e8db.png)
![seleccion_386](https://cloud.githubusercontent.com/assets/1318648/9143760/7d644db4-3d48-11e5-89e2-e236f7b05c5d.png)

**Comment by jfirebaugh** [comment]
Can you create a JSFiddle that demonstrates the issue?
