### ISSUE TITLE
mapbox access token failed net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by jometho** [mapbox/mapbox.js#1051]
Hello, I am having a problem setting my access token in my application I keep getting this error when I check from the console "Fialed to load resource : net::ERR_EMPTY_RESPONSE" and could not load tile JSON. How should I solve this problem, I couldn't find any solution online

**Comment by jfirebaugh** [comment]
Can you link to your code or make a JSFiddle that demonstrates the issue? Thank you!

**Comment by tmcw** [comment]
Closing; more information would be needed to debug this issue.
