### ISSUE TITLE
Roll new release with drag fix

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox.js#1052]
This PR fixes a very annoying issue on Chrome where slow loading tiles stop any zoom/pan interaction on the map: https://github.com/Leaflet/Leaflet/pull/3692

@tmcw @mourner - what is your plan / timing to roll a mapbox.js update including https://github.com/Leaflet/Leaflet/pull/3692 ?

**Comment by tmcw** [comment]
The steps need to be (1) Leaflet release (2) Mapbox.js release. Mapbox.js uses tags of Leaflet, only.

**Comment by mourner** [comment]
Blocked by this issue: https://github.com/Leaflet/Leaflet/issues/3689

**Comment by mourner** [comment]
Leaflet 0.7.4 is live. @lxbarth can you please make sure it's working as expected on http://leafletjs.com?

**Comment by mourner** [comment]
Found a regression in 0.7.4 so hold on for now :( https://github.com/Leaflet/Leaflet/issues/3796

**Comment by mourner** [comment]
Released 0.7.5 today, that one should be good to go.

**Comment by tmcw** [comment]
Rolling an update with 0.7.5.

**Comment by tmcw** [comment]
Implemented & deployed with #1055
