### ISSUE TITLE
Don't autoattach window.L on require()

### ISSUE THREAD

**Issue by antpaw** [mapbox/mapbox.js#1060]
The entire point of using require and browserify is to get rid of global variables. 

``` js
var L = require('mapbox.js');
```

this is how to design should look like.

**Comment by tmcw** [comment]
Yep, we get browserify. To avoid the global export, [Leaflet would have to change](https://github.com/Leaflet/Leaflet/blob/master/src/Leaflet.js): this is upstream in that codebase.

**Comment by tmcw** [comment]
Upstream: https://github.com/Leaflet/Leaflet/issues/3958

**Comment by robertberry-zz** [comment]
Could you not write a small wrapper for Leaflet and at least import it, though, when you reference it within the Mapbox codebase?

You have modules like this:

https://github.com/mapbox/mapbox.js/blob/mb-pages/src/feedback.js

As L is only set into the 'window', this means it's not available as a global in Node. This means if I write any tests that import modules that then import Mapbox, I get this error:

```
var Feedback = L.Class.extend({
                          ^
ReferenceError: L is not defined
```

**Comment by tmcw** [comment]
Same as earlier issue #726 

We're 100% open to a great PR that fixes the issue. Unfortunately many of the solutions have already been explored and are dead ends: if we wrap and require Leaflet we'll break standalone builds, and so on.
