### ISSUE TITLE
Improve This Map link does not obtain map viewport when initially expanded

### ISSUE THREAD

**Issue by jwass** [mapbox/mapbox.js#1067]
The Improve This Map link includes the current map bounds/zoom only if the info control was expanded when the map view was last changed.

To reproduce (on geojson.io):
1) zoom/pan the map
2) expand the info control
3) click Improve This Map - it won't carry the bounds/zoom through in the link.

You have to pan or zoom between steps 2) and 3) above to be able to click through to edit. Not a huge deal but probably amplified due to the info control being collapsed by default.

I'm using whichever version of mapbox.js that is currently deployed on geojson.io at the time of writing this up. Apologies if it's already been fixed but not deployed there.

**Comment by jfirebaugh** [comment]
Thanks for the report. The info control is [deprecated](https://github.com/mapbox/mapbox.js/issues/941) and will not be receiving any further bugfixes. I've opened [an issue on geojson.io](https://github.com/mapbox/geojson.io/issues/482) to replace it with the default attribution control.
