### ISSUE TITLE
Markers on edge of window flash on/off when interacting with map

### ISSUE THREAD

**Issue by MateoV** [mapbox/mapbox.js#107]
When the middle of a marker is off the edge of the browser window, it will flash on and off alternately when dragging the map. This is even more noticeable when displaying tooltips. Every hover-on event, the edge marker will change back and forth.

Looks like it is the x-coord of the `transform: translate` style that is alternating between a positive and negative number.

**Comment by ansis** [comment]
Fixed in https://github.com/mapbox/markers.js/issues/44
