### ISSUE TITLE
v2.2.3 would introduce breaking change

### ISSUE THREAD

**Issue by karenzshea** [mapbox/mapbox.js#1074]
Changes from https://github.com/mapbox/mapbox.js/pull/1063 will break uses of [mapbox.config.HTTP_URL](https://www.mapbox.com/mapbox.js/api/v2.2.2/l-mapbox-config-http_url/) and HTTPS_URL where a version number is set in the path. Most commonly seen in cahoots with api-maps-staging like in mapbox.js examples https://github.com/mapbox/mapbox.js/blob/1c6c03d5b5362b42a547d97a14417475f894b70c/docs/_layouts/example.html#L35

We could either add code to dedupe version paths or go for the 3 pointer

cc @yhahn @tmcw @sbma44

**Comment by jfirebaugh** [comment]
Great catch @karenzshea! I like your approach to fixing this in #1076.

**Comment by tmcw** [comment]
Fixed in #1076
