### ISSUE TITLE
Circles get bigger the further north/south they are

### ISSUE THREAD

**Issue by Thource** [mapbox/mapbox.js#1075]
Running the following code will result in something similar to the image attached.

``` javascript
L.circle([85,0], 1000000).addTo(map);
L.circle([80,0], 1000000).addTo(map);
L.circle([70,0], 1000000).addTo(map);
L.circle([60,0], 1000000).addTo(map);
L.circle([50,0], 1000000).addTo(map);
L.circle([40,0], 1000000).addTo(map);
```

They should all be the same size.
Is this a bug or is there a reason behind this?

![image](https://cloud.githubusercontent.com/assets/4104309/10888714/b6e0bb0a-8185-11e5-9e0d-528aa310a6b3.png)

**Comment by tmcw** [comment]
Yes, the map is in [web mercator](https://en.wikipedia.org/wiki/Web_Mercator), which is not an equal-area projection. So, meters are bigger at the top. Projections are compromises, equal area is what mercator compromises on.

Closing: use L.circleMarker if you want circles drawn by pixel size.
