### ISSUE TITLE
Switch arrays of GeoJSON features to FeatureCollection in examples

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox.js#1077]
Per discussion with @lyzidiamond and @tmcw, despite the fact that Leaflet can handle arrays of features (as opposed to `FeatureCollection`), this is [bad practice](http://geojson.org/geojson-spec.html#feature-collection-objects) and should be changed to `FeatureCollection` in public examples. Examples that include arrays of features: 
- [ ] Distance between two markers: https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-distances/
- [ ] Markers with multiple filters: https://www.mapbox.com/mapbox.js/example/v1.0.0/markers-with-multiple-filters/
- [ ] Markers with images slideshow: https://www.mapbox.com/mapbox.js/example/v1.0.0/markers-with-image-slideshow/
- [ ] Marker tooltips outside of map: https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-tooltips-outside-map/
- [ ] Load GeoJSON: https://www.mapbox.com/mapbox.js/example/v1.0.0/load-geojson/
- [ ] Toggle marker color on click: https://www.mapbox.com/mapbox.js/example/v1.0.0/change-marker-color-click/
- [ ] Soundcloud embed: https://www.mapbox.com/mapbox.js/example/v1.0.0/soundcloud-embed/
- [ ] Tabs in marker tooltips: https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-tooltip-tab-groups/
- [ ] Marker navigation from marker menu: https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-navigation-from-menu-list/
- [ ] Custom marker image: https://www.mapbox.com/mapbox.js/example/v1.0.0/custom-marker/

**Comment by jfirebaugh** [comment]
:+1:

**Comment by lyzidiamond** [comment]
BAM @danswick thanks for opening this! Let's try to knock these out this week.

**Comment by tmcw** [comment]
Looks like this fell by the wayside - going to get this done now.
