### ISSUE TITLE
maxBoundsViscosity not working

### ISSUE THREAD

**Issue by MrBlenny** [mapbox/mapbox.js#1078]
As far as I can tell, maxBoundsViscosity is not working in 2.2.3. 
http://mourner.github.io/Leaflet/reference.html#map-maxboundsviscosity

I'm not sure if this a problem with mapbox.js or leaflet. Please advise.

```
            var map = L.mapbox.map(element, 'myMapCode', {
                maxBounds: [[-90,-180],[90,180]],
                maxBoundsViscosity: 1.0,
                minZoom: 3,
            });
```

**Comment by tmcw** [comment]
That is pre-release documentation for the unreleased leaflet 1.0- please use the official released docs.
