### ISSUE TITLE
geocoderControl 'error' event not fired when match not found

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox.js#1083]
The docs for `geocoderControl.on('error', ...)` suggest that a request that fails to match with a location should trigger an error event. However, the response just contains an empty set of features: 

Example query: 

`https://api.mapbox.com/geocoding/v5/mapbox.places/asldkfj.json?types=place,address&access_token=token`

```
{
  "type": "FeatureCollection",
  "query": [
    "asldkfj"
  ],
  "features": [],
  "attribution": "NOTICE: © 2015 Mapbox and its suppliers. All rights reserved. Use of this data is subject   to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained."
}
```

Which seems to contradict the API docs here: 

![image](https://cloud.githubusercontent.com/assets/2365503/11319699/53964d02-9045-11e5-9b9e-7984ef9a7645.png)

**Comment by tmcw** [comment]
These docs should be updated. Error is a request error, like a 404, 500+, DNS issue, etc; it shouldn't be fired for empty result sets.
