### ISSUE TITLE
deeper zoom levels

### ISSUE THREAD

**Issue by blq** [mapbox/mapbox.js#1085]
I notice that many maps (tileLayers) use a maxZoom of about 19 (that the service returns). But by inspection the map data often supports several deeper zoom levels. 
Maybe this is more of a question of the maps themselves or the map service. Is this by design or is this a oversight that can be improved?

**Comment by blq** [comment]
...bump

**Comment by tmcw** [comment]
This is by design. Leaflet doesn't support variable zoom levels and we don't have a service to overzoom consistently with raster tiles.

**Comment by blq** [comment]
My question is not actually about overzooming. I simply noticed that there are often couple of more real standard tile layers available that can be reached, but are for some reason not included in the zoom-level-counter.
