### ISSUE TITLE
Other languages?

### ISSUE THREAD

**Issue by Randgalt** [mapbox/mapbox.js#1089]
How do I get a map in Spanish? I can see that the GL lib supports it. Does the JS lib?

**Comment by jfirebaugh** [comment]
For Mapbox.js, you will need to create a custom Mapbox Studio Classic style. See [this help article](https://www.mapbox.com/help/changing-label-language/). It's a bit more involved than with Mapbox GL -- one of the advantages of moving to client-side rendering is that changing the label language can be done on the fly.

**Comment by ilyatrunov** [comment]
is there a way to upload your own translations, for languages that are not currently supported?
