### ISSUE TITLE
Make geocoder-request abortable

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox.js#1090]
When using the geocoder as an autocomplete-while-typing library it is important to be able to abort requests. 
Normally you should get a handle to the XHR or request object.
Peeking at the code it should be possible to return the request object in query(): it is based on request.js which is based on corslite which returns the request object which is either a XDomainRequest or a XMLHttpRequest. It would help a lot.

**Comment by tmcw** [comment]
This sounds like a decent enhancement for a release where we improve the geocoder code.

**Comment by tmcw** [comment]
This will require a major version bump - 3.0.0 release only.

**Comment by tmcw** [comment]
Folding into #1193

**Comment by mohsentaleb** [comment]
Is this resolved? Could you please mention the commit?
@tmcw
