### ISSUE TITLE
Support headless node.js rendering

### ISSUE THREAD

**Issue by nyurik** [mapbox/mapbox.js#1094]
For [my project](https://github.com/wikimedia/mediawiki-extensions-Kartographer) to integrate mapbox.js into Wikipedia, I will need to support server-side (node.js) rendering of a map with simplestyle geojson overlays. I saw [this project](https://github.com/jieter/leaflet-headless) for leaflet. Are there any similar projects for mapbox.js?

**Comment by tmcw** [comment]
We don't plan on implementing headless mode for mapbox.js. The Leaflet code may end up being compatible, but Leaflet is at heart a browser library that will have uncertain compatibility with servers - our efforts are spent on [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native)'s headless rendering mode instead. The previous implementation of static maps at Mapbox uses [node-blend](https://github.com/mapbox/node-blend). Tile layout is very simple to implement and is likely better done outside of an existing browser-based library.
