### ISSUE TITLE
Mapbox.js : setLayoutProperty for language settings

### ISSUE THREAD

**Issue by VinaykumarNM** [mapbox/mapbox.js#1097]
Hi,
Maobox.js show map titles (country name, city name etc) in respective native languages. But our requirement is to show all titles (country name, city name) in English only.
Mapbox GL has a method 'setLayoutProperty', is there any similar method/property to set language as 'English'?

Any help would be helpful.

Thanks
Vinay

**Comment by jfirebaugh** [comment]
Since Mapbox.js does not use client-side rendering like Mapbox GL, there's no equivalent to `setLayoutProperty`. You can read about how to change the label language for classic styles [here](https://www.mapbox.com/help/change-language/#change-label-language-in-mapbox-studio-classic).
