### ISSUE TITLE
Tile Images fail to Load 

### ISSUE THREAD

**Issue by burock** [mapbox/mapbox.js#1100]
Hi,
I'm trying to include mapbox into my website:

```
L.mapbox.accessToken = 'blah';
var map = new L.mapbox.Map('map','burock.ok303cgl');
map.doubleClickZoom.disable();
var geocoderControl = L.mapbox.geocoderControl('mapbox.places', {
       autocomplete: true
});
geocoderControl.addTo($scope.map);
```

with html:

```
<div class="md-whiteframe-4dp" flex>
                    <div id="map" class="map-container"></div>
</div>
```

and css:

```
.map-container {
    position:absolute;
    width:400px; 
    height: 400px;
}
```

But the output is as attached. If I clear the cache and load it for the first time it looks ok, however, on any second view i get this partial display.
![image](https://cloud.githubusercontent.com/assets/786494/12110687/974d7b2c-b397-11e5-8a71-cf075606e5c7.png)

Any advice is welcome..

Cheers,
Burak.

**Comment by burock** [comment]
Just in case anyone interested a workaround i did was to add the following (somehow map.invalidateSize did not run without a timeout??)

```
map.on('layeradd', function(e) {
           setTimeout(function(){ map.invalidateSize(true);}, 400);
        });
```

**Comment by tmcw** [comment]
This problem is described in our existing help documentation: https://www.mapbox.com/help/blank-tiles/#your-map-is-hidden
