### ISSUE TITLE
Markup fault in "Displaying WMS layers" example

### ISSUE THREAD

**Issue by iH8** [mapbox/mapbox.js#1105]
https://www.mapbox.com/mapbox.js/example/v1.0.0/wms/

![mapbox](https://cloud.githubusercontent.com/assets/692063/12354179/775fe714-bb94-11e5-9f05-19c0fecdba9c.png)

**Comment by tristen** [comment]
Thanks @iH8 looks like the link in the description field of that post needed some proper quotes! Will re-publish shortly.
