### ISSUE TITLE
Add infowindow popups for WMS

### ISSUE THREAD

**Issue by ezgis504** [mapbox/mapbox.js#1107]
I am trying to mashup a handful of WMS layers into a Leaflet map. I need the map to include popup infowindows, but this functionality is current unavailable. There are a couple of different scripts out there, but none of them have worked for me. [Leaflet.wms](https://github.com/heigeo/leaflet.wms) seems like a good one, but like I said it doesn't work for me.

**Comment by tmcw** [comment]
Sorry, we don't plan on spending much time implementing WMS compatibility. You'll need to find or build a compatible Leaflet plugin that fits your usecase.
