### ISSUE TITLE
Single quote in yaml description breaks the header

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox.js#1111]
<img width="677" alt="screen shot 2016-01-22 at 2 37 03 pm" src="https://cloud.githubusercontent.com/assets/58878/12522268/b523a50c-c11d-11e5-882e-6df7d8cced30.png">

**Comment by tmcw** [comment]
yaml is turrble

**Comment by tristen** [comment]
Yeah, the description field needs to be wrapped in quotes if there's going to be any characters like that in there. I can fix.
