### ISSUE TITLE
Labels disappear on overlapping marker

### ISSUE THREAD

**Issue by sebastiantiede** [mapbox/mapbox.js#1112]
I've changed the layer order – everything works fine except one little detail:
all labels disappear that overlap a marker if the label layer is on the top.

in the original sequence the markers overlap labels – as expected.

Thanks in advance
Sebastian

**Comment by mourner** [comment]
You probably intended to open this in https://github.com/mapbox/mapbox-gl-js

**Comment by sebastiantiede** [comment]
mh, I need to work with mapbox studio because of the export tool.
