### ISSUE TITLE
Tile not loading when holding drag on mobile phone

### ISSUE THREAD

**Issue by simonvandel** [mapbox/mapbox.js#1123]
When dragging the map on [example](https://www.mapbox.com/mapbox.js/example/v1.0.0/), map tiles are instantly loaded while dragging the map on a desktop. However when accessing the same example on an Android phone (Chrome), the tiles load only after dragging has ended. This leads to white areas, which is unwanted.

Is it possible to have the same behavior on the phone as on the desktop?

**Comment by jfirebaugh** [comment]
Yes, set the [`updateWhenIdle` option](http://leafletjs.com/reference.html#tilelayer-updatewhenidle) for the tile layer to true.
