### ISSUE TITLE
Tooltips content isn't clickable on mobile

### ISSUE THREAD

**Issue by edudar** [mapbox/mapbox.js#113]
While working on map component for our own HTML5 framework I noticed that city names aren't clickable within tooltips at http://mapbox.com/mapbox.js/example/custom-marker-tooltip/ on iPhone in Safari and Chrome. They are on desktop though. Seems like a bug.

**Comment by davecranwell** [comment]
As far as I can tell touch events besides dragging motions are completely unsupported. I'd like to be able to click the layers in my map, when viewing the web page on touchscreen devices like phone or tablet. Hover, obviously, is far harder to support as there is no ability to hover a finger, but click should work.

During testing i've got my mapbox javascript thus:

``` javascript
mapbox.load(mymap, function(o){
  //do stuff like adding layers, setting zoom rangers etc
  map.interaction.auto();
  map.interaction.on({
    on: function(o){
      // do stuff
      alert('here');
    }
  });
}
```

... and while the 'here' alert obviously happens whenever you do anything with the mouse on a desktop, the alerts don't seem to fire at all on my iPhone, suggesting that interactivity is handled by entirely different code for mobiles.

Having just tested it on Android's Chrome, its not even possible to drag the map around, let alone click. It seems to be possible to drag on iOS but perhaps thats just by luck.

**Comment by ansis** [comment]
@edudar This should be fixed by mapbox/markers.js#47 which will be incorporated into the next mapbox.js release

@davecranwell I've opened a ticket about touch events upstream at mapbox/wax#256. They should be supported, but it seems to be broken. A ticket about the Android drag issue is open at mapbox/easey#29

**Comment by ansis** [comment]
Fixes should now be rolled into master and can be tested with:

http://api.tiles.mapbox.com/mapbox.js/v0.6.6-dev2/mapbox.uncompressed.js
http://api.tiles.mapbox.com/mapbox.js/v0.6.6-dev2/mapbox.css

**Comment by ansis** [comment]
v0.6.6 has been deployed and should fix these issues, closing
