### ISSUE TITLE
Drawing lots of svg elements is super slow in IE/Edge

### ISSUE THREAD

**Issue by PatrickStotz** [mapbox/mapbox.js#1133]
Adding more than a few hundred items with mapbox.js is super slow in IE. 
Chrome, Firefox & Safari are doing fine (50s vs. 1 second)
Demo: https://jsfiddle.net/3w1hz608/3/

This applies to line features as well as point features/markers. I've tried a ton of different ways to load and parse the data, but it seams to be the svg drawing that's not working properly.

Using Leaflet 0.7.3 fixes the problem, but I rely on other mapbox.js features.
Switching to Leaflet Canvas mode (L_PREFER_CANVAS = true) is another workaround, but I'd prefer to use SVG.

Will now try to to use the mapbox.js standalone version + leaflet.js while this issue is open.
Any other thoughts?

**Comment by PatrickStotz** [comment]
Leaflet 0.7.7. is affected, too. Mapbox.js standalone + leaflet 0.7.3 works for the moment

**Comment by tmcw** [comment]
SVG is simply slow in IE once you have a certain number of elements. Mapbox.js doesn't affect the SVG renderer in Leaflet at all - any method you call on `L` that isn't part of `L.mapbox` is totally unaffected by Mapbox. This performance ceiling is one of the main reasons we've focused on [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/) instead of Mapbox.js recently.

**Comment by PatrickStotz** [comment]
I see the benefits of moving to WebGL, but for the moment I just have to support SVG & IE (even if it hurts sometimes). 
As mentioned before, Leaflet 0.7.3 is working perfectly fine. Rendering time < 1 second. It's Leaflet 0.7.7.  (and mapbox accordingly) that's blowing up the rendering time to like 50-60 seconds.

**Comment by antonylawler** [comment]
I'm using svg 'raw', i.e. not via a library. Fine on Chrome, IE, Safari, Ipad, Iphone. Near unusable on Edge. It's not a mapbox.js issue, it's an Edge issue.

**Comment by tmcw** [comment]
Closing; contact your Microsoft representatives.
