### ISSUE TITLE
mapbox.js 1.6 branch does not build because of missing 'esprima-six' module

### ISSUE THREAD

**Issue by eddietejeda** [mapbox/mapbox.js#1135]
The 'esprima-six' module was unpublished from npm and now the library does not build.

More information:
http://stackoverflow.com/questions/33608630/what-happened-to-the-esprima-six-npm-module

Error message:

> npm WARN package.json mapbox.js@1.6.6 No license field.
> npm WARN deprecated native-buffer-browserify@2.0.17: Use the "buffer" module (https://www.npmjs.com/package/buffer) instead
> npm ERR! Darwin 15.4.0
> npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install"
> npm ERR! node v4.2.1
> npm ERR! npm  v2.14.7
> npm ERR! code E404
> 
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/esprima-six
> npm ERR! 404 
> npm ERR! 404 'esprima-six' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of 'astw'
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/eddie/Sites/civicinsight/node_modules/mapbox.js/n

**Comment by tmcw** [comment]
v1.6.7 is published to npm!
