### ISSUE TITLE
Use SVG for icons

### ISSUE THREAD

**Issue by edg2s** [mapbox/mapbox.js#1137]
Currently we build a PNG and a 2x PNG. In most browsers we can just use the SVG directly.

**Comment by tmcw** [comment]
Mapbox.js supports [IE8+](https://www.mapbox.com/mapbox.js/api/v2.4.0/) and [IE8 doesn't support SVG](http://caniuse.com/#search=svg), so we can't do this without breaking a promise.

**Comment by edg2s** [comment]
I'm not suggesting you drop the PNGs/IE8 support completely. There are many ways to target specific versions of IE in CSS: body classes, conditional comments or the linear-gradient trick.

**Comment by tmcw** [comment]
Having IE8 support would mean still having a png & png2x resource around, and then adding a compatibility hack on top of that. It would add complexity to a part of Mapbox.js that is currently working quite well, so I'd rather not implement it.

**Comment by edg2s** [comment]
Complexity? It's one of the more simple browser hacks. I imagine it isn't the only one in your library. In MediaWiki we use the linear-gradient trick: http://pauginer.com/post/36614680636/invisible-gradient-technique

This is very easy to implement, the only downside is it still serves PNGs to IE9, but that is no worse than the current situation.

**Comment by edg2s** [comment]
We are already using the SVG background image in Wikipedia's new map extension where it works fine: https://gerrit.wikimedia.org/r/#/c/282937/
Ideally we can replace that hack with this upstream fix.

**Comment by edg2s** [comment]
As you can see this change is only two extra lines of CSS. Do you still have any objections?

**Comment by tmcw** [comment]
@tristen @samanpwbb do you think this is a good path to go down for icons?

**Comment by edg2s** [comment]
It's worth noting that there are an increasing number of devices with 3x or higher pixel densities, and zooming into the interface is much more common on touch devices.

**Comment by peterqliu** [comment]
@edg2s [use L.divIcon](http://jsfiddle.net/ksh97750/)

**Comment by edg2s** [comment]
@peterqliu thanks, but we're talking about toolbar icons at the moment, not markers.

**Comment by edg2s** [comment]
Any more thoughts on this? The Leaflet team have just merged a similar patch: https://github.com/Leaflet/Leaflet.draw/pull/530

**Comment by tristen** [comment]
@edg2s Sorry! this dropped off my radar when I saw https://github.com/mapbox/mapbox.js/issues/1137#issuecomment-213834921. https://github.com/mapbox/mapbox.js/pull/1138 looks good and I think this is a good path to go down.

**Comment by edg2s** [comment]
@tristen Could you please re-open #1138 as @tmcw closed it claiming it killed IE8 support (it doesn't). Also maybe someone could merge it?

**Comment by edg2s** [comment]
Bump.
