### ISSUE TITLE
Roll in min-width fix from Wax

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#114]
Porting #244 over here - this needs to be rolled into mapbox.js. This tag will include some other improvements as well.

**Comment by ian29** [comment]
Assigned to [Tender discussion #3175](http://support.mapbox.com/discussions/general-questions/3175-interactive-panel-not-scrolling).

**Comment by ansis** [comment]
Done in cb099691825ca716e111742ad11e44e3a80f8bac
