### ISSUE TITLE
Markers search and tooltip

### ISSUE THREAD

**Issue by nadj** [mapbox/mapbox.js#1140]
Hi, I have an input field on my map that searches for marker by an entered id. 
When the marker is found I want to open the tooltip of that marker. 
Here is my example  (try to enter 1,2, or 3 in the input field located at the botom center of the map):
[https://jsfiddle.net/n4auLfp8/](url)

Can't figure out how to open the tooltip.

**Comment by tmcw** [comment]
Sorry, this issue tracker is for mapbox.js development, rather than support. Feel free to contact [Mapbox support](https://www.mapbox.com/help/) for help.
