### ISSUE TITLE
pngjs dependency on node-zlib-backport causes npm install failure

### ISSUE THREAD

**Issue by monkeyboy64** [mapbox/mapbox.js#1141]
pngjs just added a new dependency on node-zlib-backport.

node-zlib-backport doesn't build on os-x:

> node-zlib-backport@0.11.15 install /Users/adam/src/numetric/web/node_modules/node-zlib-backport
> node-gyp rebuild

  CXX(target) Release/obj.target/zlib/src/node_zlib.o
In file included from ../src/node_zlib.cc:32:
/Users/adam/.node-gyp/5.1.0/include/node/node_internals.h:6:10: fatal error: 'util-inl.h' file not found
# include "util-inl.h"

```
     ^
```

1 error generated.
make: **\* [Release/obj.target/zlib/src/node_zlib.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adam/src/numetric/web/node_modules/node-zlib-backport
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "install" "node-zlib-backport"
npm ERR! node v5.1.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE

npm ERR! node-zlib-backport@0.11.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-zlib-backport@0.11.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-zlib-backport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-zlib-backport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-zlib-backport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adam/src/numetric/web/node_modules/npm-debug.log

**Comment by tmcw** [comment]
Hi,

Thanks for the bug report, but I believe this is in the wrong repository; this is for Mapbox.js, and we have no dependency on pngjs.
- Tom
