### ISSUE TITLE
Firefox and Safari tile issue

### ISSUE THREAD

**Issue by lancegliser** [mapbox/mapbox.js#1145]
Translation of the tiles seems to be off. The same map renders well in Chrome.
<img width="1271" alt="screen shot 2016-05-13 at 3 24 33 pm" src="https://cloud.githubusercontent.com/assets/12085479/15260978/67095d8a-191f-11e6-8a4d-62bd7af0f042.png">

I've tried removing all of our css from the site as well, expecting the interplay might be causing these issues. The results are below, but the map seems to render outside the yellow bounds of the #map. 
<img width="699" alt="screen shot 2016-05-13 at 3 36 03 pm" src="https://cloud.githubusercontent.com/assets/12085479/15261195/92c4f0f0-1920-11e6-803f-3381f5d5760f.png">

Any ideas how to resolve this?

**Comment by tmcw** [comment]
Can you provide an example of this page or the issue as a jsfiddle?

**Comment by lancegliser** [comment]
Sadly I'm not able to get you a standalone page example. If I use the map in a standalone fiddle it functions without issue. I'll drop you a note in your email for the moment.

**Comment by lancegliser** [comment]
Nate Dean figured out the issue. It was sadly simple. The way we were loading the stylesheets was blowing up in FF and not correctly rendering. It works fine after we moved back to simpler style imports. Closing this out.
