### ISSUE TITLE
Standardise lan/lot order

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox.js#115]
In some examples, e.g. in http://mapbox.com/mapbox.js/example/single-marker/, we use both lon/lat and lan/lot order of coordinates. We should standardise the order across all examples.

**Comment by tmcw** [comment]
I don't think this matters... it's always lon/lat in geojson, and order of attributes in objects doesn't matter - that's why we use objects in the first place.

**Comment by tmcw** [comment]
Closing, since people have been snarky about GeoJSON's coord order, I've made notes on it.
