### ISSUE TITLE
grid-lines on my map

### ISSUE THREAD

**Issue by personaljesus80** [mapbox/mapbox.js#1156]
hello,

i am searching for a way to integrate grid-lines on my map.
the grid has to be configurable in meters.

i am new in using mapbox and didnt find a way or a german forum, to ask these question.

this is the map: https://a.tiles.mapbox.com/v4/personaljesus.122625d6/page.html?access_token=pk.eyJ1IjoicGVyc29uYWxqZXN1cyIsImEiOiJjaXJpc2k0NngwMDAzaHNrd3doNG55emtiIn0.zVMGz5_Ul47R9Qiv7qwJgQ#14/50.0129/8.2456 

can anyone help me quickly? i need this for my masterthesis.

greetings and thanks.
personaljesus

**Comment by tmcw** [comment]
Hi personaljesus,

Sure, use the [Leaflet.Graticule](https://github.com/turban/Leaflet.Graticule) plugin to add grid lines to your map.
- Tom
