### ISSUE TITLE
Grid Control with latest leaflet 

### ISSUE THREAD

**Issue by anandar** [mapbox/mapbox.js#1158]
Trying to use standalone Mapbox.js (v2.4.0) with latest leaflet v1.0.0-rc3 . Previously was using Mapbox.js (v2.2.1) but due to performance issues in IE/Edge had to upgrade. With the new leaflet 
unable to add tooltips to the map. Below is the code snippet 

```
 dataLayer.grid = L.gridLayer({
            bounds: ([[boundaries._southWest.lat, boundaries._southWest.lng], [boundaries._northEast.lat, boundaries._northEast.lng]]),
            center: [4.7, 19],
            zoom: 3,
            minZoom: 2,
            maxZoom: 8,
            maxBounds: L.latLngBounds(L.latLng(-85, -180), L.latLng(85, 180)),
            grids: [url]
          });
          map.addLayer(dataLayer.grid);
          gridControl = L.mapbox.gridControl(dataLayer.grid);
          map.addControl(gridControl);
          dataLayer.grid.on('mousemove', function (e) {});
```

If the leaflet gridlayer is used the grid.json is not getting requested from server as _loadTileJSON(_) is not getting initialized. 

Is there a easy work around this. Please help

**Comment by tmcw** [comment]
Hi @anandar,

Sorry, Mapbox.js is not yet compatible with Leaflet 1.x ( #1038 ): we're updating to the new Leaflet once there's a 1.0 stable release, but not before then.
- Tom
