### ISSUE TITLE
Markers are created at the wrong place

### ISSUE THREAD

**Issue by Pilou44** [mapbox/mapbox.js#1159]
Hello,
I've got an issue on Android with mapbox 4.1.0: when I add markers they are often displayed at the wrong place. But as soon as I pan the map they move to the right place.
I join screen captures of my example. I calculate an itinerary and display it with a polyline. Markers A an B represent start and end of itinerary. 
Here it what it looks like on creation: 
![1](https://cloud.githubusercontent.com/assets/10031050/17894429/9db0eaae-6949-11e6-8518-48d30247cbed.png)
Here is what it looks like just after I move the map a little:
![2](https://cloud.githubusercontent.com/assets/10031050/17894434/a5838372-6949-11e6-95a0-dfd3e2a216da.png)
I didn't see this issue in the existing ones.
Thank you.

**Comment by tmcw** [comment]
Hi,

This is the issue tracker for Mapbox.js; the JavaScript SDK, not the Java one. Please contact [Mapbox support](http://mapbox.com/help) or file an issue tracker with [Mapbox GL Native](http://github.com/mapbox/mapbox-gl-native).
- Tom
