### ISSUE TITLE
Feature request: continuous vs on-end events

### ISSUE THREAD

**Issue by mnoble01** [mapbox/mapbox.js#117]
It seems a bit counterintuitive that the 'panned' event is fired _while_ the map is being panned. 

Would it be possible to add a 'panning' event to be fired while the map is being panned (i.e. mousedown) and another called 'panned' to be fired onmouseup?

Cheers,
     Makala

**Comment by ansis** [comment]
Does the `drawn` event suit your needs? It gets fired whenever the map gets redrawn (zooming, panning, etc).

**Comment by mnoble01** [comment]
Hi, no. The `drawn` event is also fired continuously when panning.

**Comment by mnoble01** [comment]
Right now I am using a hacky solution that keeps track of the state of the mouse and sets a `panning` variable. My `onmouseup` event uses this variable as a conditional, then resets the `panning` var as necessary.

**Comment by mnoble01** [comment]
Oh, I forgot to say this originally, but the same goes for `zooming`.

**Comment by littleiffel** [comment]
I am also interested in such an event after the panning or zooming is finished.

**Comment by idan** [comment]
+1!

Right now the `zoomed` event is significantly less useful than it seems—it delivers an offset and a current zoom level, but the "current" level is an arbitrary point in the middle of the zoom animation, and I have to keep track of the "previous" zoom level manually in order for the offset to be useful. (cf. #147)

**Comment by Ciki** [comment]
I'd like to have this feature as well :-)

**Comment by jfirebaugh** [comment]
We won't be adding new features to v.0.6.x, but in v1, leaflet supports `move` and `moveend` events, for example.
