### ISSUE TITLE
Inconsistent style-rendering

### ISSUE THREAD

**Issue by ngeens** [mapbox/mapbox.js#1171]
mapbox-js version: v2.4.0
## Steps to Trigger Behavior
1. Open Mapbox Studio preview/sharing url: https://api.mapbox.com/styles/v1/ngeens/circ2dl5u002hh1kp950caxzq.html?title=true&access_token=pk.eyJ1IjoibmdlZW5zIiwiYSI6ImNpcmMyYXVjMDAwN21pYWx3b2lvcHpvNDAifQ.7QcQaZtD1ttfCq4qgBdzLw#3.577873543226374/48.009524894513106/7.8074666275565505/0
2. Open Codepen with style embedded: http://codepen.io/nikogeens/pen/VKdvXX
3. Compare rendering. See how the white country-borders are visible in the preview url, but don't show in the codepen url.
## Expected Behavior

Rendering should be consistent.
## Actual Behavior

White country-borders dissapear.

This used to render correctly in the past, I think... Is this a bug?
Or I might be missing something...

**Comment by mikemorris** [comment]
We're tracking this issue upstream in https://github.com/mapbox/mapbox-gl-native/issues/6620
