### ISSUE TITLE
Support language option in geocoder

### ISSUE THREAD

**Issue by pablo-co** [mapbox/mapbox.js#1175]
The [Geocoding API](https://www.mapbox.com/help/geocoding-service/) supports different languages for the results. Yet the [geocoder](https://github.com/mapbox/mapbox.js/blob/34e4610dcca34152188b1a57cb4d3dab0db00a96/src/geocoder.js) in this library ignores that parameter. Will this option be added soon to the geocoder?

I would have no problem in doing a PR if this is a low priority issue for you.

**Comment by tmcw** [comment]
Folding into #1193
