### ISSUE TITLE
Update docs and examples for v3.0.0

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#1178]
- [x] Docs updated
- [ ] Find and fix broken examples

TODO:
- [x] imagePath now expects a trailing `/` in Leaflet 1.0 so https://www.mapbox.com/mapbox.js/example/v1.0.0/coffeescript/ is showing 404s
  - https://github.com/mapbox/mapbox.js/pull/1179
- [x] z-index of map changed so marker distance doesn't appear
  - https://github.com/mapbox/mapbox.js/pull/1180
- [x] leaflet markercluster is broken https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/
- [x] https://www.mapbox.com/mapbox.js/example/v1.0.0/stylelayer/ is broken

v3.0.0-beta is deployed to the CDN so that we can test it with the docs site. We should test, deploy, and blog on Monday.

**Comment by geografa** [comment]
@tmcw I'm getting 404s on the API docs at the moment. It's running locally and everything passes with one pending test. 2.4.0 docs seem to be working as well. Could this be a publisher thing?

cc @lyzidiamond @colleenmcginnis

**Comment by tmcw** [comment]
Docs are fixed, the generation script changed to accomodate for Jekyll 3, but ended up writing `.html` files instead of directories with `index.html`s in them.

**Comment by tmcw** [comment]
Closing: docs are now fixed (again), open new issues for any issues that crop up.
