### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ./images/marker-icon.png

### ISSUE THREAD

**Issue by minessis** [mapbox/mapbox.js#1186]
Getting the following webpack build error after incrementing from npm version `mapbox.js@2.4.0` to `mapbox.js@3.0.0`:
```bash
ERROR in ./~/css-loader!./~/mapbox.js/theme/style.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./images/marker-icon.png in /Users/ralphwlewis/GitHub/hud-admin/node_modules/mapbox.js/theme
 @ ./~/css-loader!./~/mapbox.js/theme/style.css 6:8874-8909
```

Please advise

**Comment by tmcw** [comment]
For the time being, we recommend that you don't upgrade to 3.0.0. When https://github.com/mapbox/mapbox.js/pull/1182 is resolved, it'll be ready to go, but until then, please stay on 2.4.0.
