### ISSUE TITLE
Update bower repo

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox.js#1188]
3.0.0 is tagged here so I assume it's released? Can 3.0.0 be pushed to the https://github.com/mapbox/mapbox.js-bower repo?

If 3.0.0 isn't ready can the beta be pushed instead?

**Comment by tmcw** [comment]
3.0.0 is a dud version, so I didn't go through the bower release process. I'm about to release 3.0.1, which will bump the bower versions.

**Comment by tmcw** [comment]
Bower repo now contains v3.0.1
