### ISSUE TITLE
icons-ffffff.svg not found

### ISSUE THREAD

**Issue by wyattp11** [mapbox/mapbox.js#1197]
I'm getting a 404 not found on:
http://api.mapbox.com/mapbox.js/v3.0.1/images/icons-ffffff.svg

All the PNGs display, other SVGs load but do not show in browser(just pasting into Chrome, assume that is normal behavior). Should only impact those dependent on the Mapbox CDN?

**Comment by tmcw** [comment]
Sorry about that, fixed on the CDN and added to the deploy script in the referenced commit.
