### ISSUE TITLE
geocoder.queryURL does not account for bbox option

### ISSUE THREAD

**Issue by lukewhyte** [mapbox/mapbox.js#1198]
On line 50 of `src/geocoder.js`, inside of the `geocoder.queryURL` method, each of the possible options to be fed into the query string are handled. `bbox`, despite being a possible option that the API does understand, isn't accounted for here and won't be passed to the query.

**Comment by lukewhyte** [comment]
Also, [API documentation](https://www.mapbox.com/api-documentation/?language=JavaScript#request-format) isn't clear as to whether the `bbox` option should be passed in as an array or converted to a string beforehand.

**Comment by tmcw** [comment]
👍 Fixed in #1199

The REST API documentation is about the URL structure, and urls are strings alone.
