### ISSUE TITLE
Using Torque and data from CartoDB example working no more

### ISSUE THREAD

**Issue by Maxszik** [mapbox/mapbox.js#1203]
The [Using Torque and data from CartoDB](https://www.mapbox.com/mapbox.js/example/v1.0.0/torque-temporal-data/) example doesnt seem to work anymore.

Using safari or chrome on mac.

**Comment by tmcw** [comment]
Thanks for the heads-up. Looks like torque's CDN version isn't updated for Leaflet v1. I'm not seeing a new CDN endpoint in the official example. @xavijam might you know if there's a new CDN link for torque that'll work with Leaflet v1.x? Thanks!

**Comment by tmcw** [comment]
No response from the carto side. Removing the example and closing.

**Comment by xavijam** [comment]
Hey! sorry guys for not answering before (I missed this notification). There is no a new CDN endpoint for torque library itself. It will come soon. Sorry again!
