### ISSUE TITLE
map.dragging.disable() not working

### ISSUE THREAD

**Issue by madebymats** [mapbox/mapbox.js#1208]
When calling `map.dragging.disable()` nothing happens.

**Comment by tmcw** [comment]
Here's [an example where I did that and it disabled dragging](https://jsfiddle.net/5uwdfhdp/). Is there something else you expect to happen?

**Comment by madebymats** [comment]
Try an exemple where you enable dragging on click and enable dragging on click aswell. 

Sorry i wasn't more precise.

**Comment by tmcw** [comment]
> Try an exemple where you enable dragging on click and enable dragging on click aswell.

Rephrase that? That sentence doesn't make any sense.

**Comment by madebymats** [comment]
create a map with dragging disabled.
attach dragging.enable/dragging.disable to a click (toggle)
dragging won't enable again.

I solved this by enabling dragging when going in  to the fullscreen mode and disabling it by exiting fullscreen. But i never managed to get enable/disable working on click. 

Does that make any sense? :-)

**Comment by tmcw** [comment]
No, it doesn't. Here's [a map in which dragging is disabled and then enabled again with a click](https://jsfiddle.net/5uwdfhdp/2/). Please provide a code example of what you mean.

**Comment by madebymats** [comment]
I tried your example with addition of enabling dragging again. And it worked, which it didn't do for me previously. I must have messed up when checking for the dragging status.

```
L.mapbox.accessToken = 'pk.eyJ1IjoidG1jdyIsImEiOiJIZmRUQjRBIn0.lRARalfaGHnPdRcc-7QZYQ';
var map = L.mapbox.map('map', 'mapbox.streets')
    .setView([40, -74.50], 9);

map.dragging.disable();

map.on('click', function() {
	console.log(map.dragging._enabled);
	if(map.dragging._enabled == false ){
		map.dragging.enable();
	}else{
		map.dragging.disable();
	}	
});
```

Sorry for not checking my code more thoroughly.
