### ISSUE TITLE
Disable needs to be safe for layers that aren't attached to maps

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#121]

**Comment by tmcw** [comment]
Even when layers are added to maps, .disable is unstable. This needs a good, hard look.

**Comment by wboykinm** [comment]
Would that be why toggling "Layer 1" [in this example](http://mapbox.com/mapbox.js/example/layers/) wipes both layers?

**Comment by ansis** [comment]
8329680dbfd0fd0eb805eeeb4b1e47d9e98b4299 should fix enabling/disabling when not attached to a map.

I didn't see anything that would cause problems when attached to a map. What error were you getting?

**Comment by ansis** [comment]
@wboykinm that seems to be a separate issue, I've opened #125
