### ISSUE TITLE
featureLayer : loadID

### ISSUE THREAD

**Issue by PixGit** [mapbox/mapbox.js#1211]
Hi,

Im trying to load markers on my map:

This code is working (when i manually add geojson data on the page)
`L.mapbox.featureLayer().setGeoJSON(geojson).addTo(map);`

But when i try to load data automatically from the mapbox:mapID it gives me an error:
`L.mapbox.featureLayer().loadID('xxxon.XXXXpqi004z32qty2jfj0oz-XXX').addTo(map);`

The error i got:
could not load features at http://a.tiles.mapbox.com/v4/j......

Edit:
I'm getting this response from server:
{"message":"Markers do not exist"}

Thanks

**Comment by tmcw** [comment]
Your problem is described in #1084: you're using a dataset ID, not a project ID. featureLayer can only load markers from projects created with /editor.
