### ISSUE TITLE
Two-finger zoom causes map to disappear on Galaxy Nexus Phone

### ISSUE THREAD

**Issue by Getafix-hub** [mapbox/mapbox.js#122]
When I Two-finger zoom on a displayed map, the screen goes blank. I need to close the App and reopen.

Is this a bug or a configuration issue? 

The LogCat error is:

10-06 19:42:58.704: E/Web Console(17570): Uncaught TypeError: Cannot read property 'y' of undefined at http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.js:3

**Comment by ansis** [comment]
Thanks for reporting, It would be great if you could get a line number for the uncompressed version.
http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.uncompressed.js

**Comment by Getafix-hub** [comment]
There you go 

10-08 16:37:18.935: E/Web Console(29399): Uncaught TypeError: Cannot read property 'y' of undefined at http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.uncompressed.js:5612

**Comment by Getafix-hub** [comment]
Any idea when this issue will be looked-at / fixed?

**Comment by jdj1229** [comment]
I am having the same problem is there a workaround for this?

**Comment by violabg** [comment]
this bug still exist on version 0.6.7, it can be tested on http://mapbox.com/mapbox.js/examples/ and any android device

**Comment by violabg** [comment]
I found a solution, basicaly the problem is that the code relay on touchevent scale property that dose not exist on android.
I can upload the source file if you tell me how

**Comment by heyitsgarrett** [comment]
@violabg, please share in a [Gist](https://gist.github.com/) and we can take a look at on our end. Thanks

**Comment by violabg** [comment]
ok, this is the link to the file https://gist.github.com/violabg/5261534 you can compare with the original here 
http://api.tiles.mapbox.com/mapbox.js/v0.6.7/mapbox.uncompressed.js
to see the changes I made.
Not sure if it is the best solution, but i works
