### ISSUE TITLE
The "main" field cannot contain globs (example: "*.js")

### ISSUE THREAD

**Issue by FireLizard** [mapbox/mapbox.js#1240]
When installing mapbox.js via bower I get the following error:

```shell
$> bower install --force --production
bower mapbox.js#^3.1.1    invalid-meta The "main" field cannot contain globs (example: "*.js")
```

At the corresponding [bower.json](https://github.com/mapbox/mapbox.js-bower/blob/master/bower.json#L6) it seems to be the "image/*" -line.

How can I fix this circumstance?

**Comment by riastrad** [comment]
Bower support was removed in v`3.2.0` (ref. [CHANGELOG.md](https://github.com/mapbox/mapbox.js/blob/6a208d8a574737ffda7099b06c6e7d19b8980b62/CHANGELOG.md#v320))
