### ISSUE TITLE
Bug in automatic compositing

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox.js#125]
Provider is not properly updated after layer is disabled.
Bug can be seen in http://mapbox.com/mapbox.js/example/layers/

https://github.com/mapbox/mapbox.js/issues/121#issuecomment-9231769

**Comment by wboykinm** [comment]
Though for practical purposes of layer switching this can be worked around. For instance, would it be a substantively different effect to sub in `map.addLayer()` and `map.removeLayer()` in place of "enable" and "disable" in this case? What is the intent of having the threee different layer activation functions? (Add/Enable/Get)

**Comment by ansis** [comment]
It was a bug related to the automatic compositing, fixed in 4d3d063bebdd0814cc6e10a8f93c58164a562d28

Enable/disable were added to make it simpler to toggle layers while reusing them and maintaining their order.`removeLayer` destroys the layer and get simply returns the layer for other purposes.

I'm not sure why we have `map.disableLayer()` but are using `map.getLayer().disable()`. @tmcw, have a preference for the latter?
