### ISSUE TITLE
Possibilities

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#126]
If we don't have enough time/control/luck to make modestmaps a success, possibly we should just port, to Leaflet.

This is just a thought-dump, internet people don't jump on this.
### Work required
- Rewrite leaflet inertial panning to be better
- [Rewrite easey](http://bukk.it/productivity.gif)
- Rewrite all controls
- Rewrite markers.js, possibly the core api :/
- Redocument everything
- Rewrite all examples
- Break 0.x compatibility
- Figure out maintainership
- Decide path for vector-styling future, degree of api-wrapping
## Advantages
- Everyone has heard of Leaflet
- Immediate access to lots of plugins
- Can finally say we support vector features (though through a not-perfect api)
- Reduced development/maintenance time of the core, especially in regards to browser upkeep.
### Disadvantages
- All MM apis break. Code breakage would be massive.
- Less direct control over core
- Less-cool coding style (openlayersy)
- Unclear that stuff like the markers API could be efficiently supported here without a full rewrite of the Leaflet API
- ol3 or d3 could be the 'next platform' anyway, and would be 'yet another switch'
- Some of these rewrites internal to Leaflet might be costly, especially stuff like inertial panning
- Leaflet is bigger than MM and we'd be back to the 'custom build scenario' in which some users really really want the full version even though [we don't want to serve it all the time](http://bukk.it/allthefucks.gif).

![](http://bukk.it/noregrets.gif)

/cc @ansis @yhahn @tristen

**Comment by yhahn** [comment]
![orly](http://i.imgur.com/EZBHj.gif)

**Comment by wboykinm** [comment]
[I didn't see this one coming](http://images.wikia.com/icarly/images/7/7b/Surprise.gif)
