### ISSUE TITLE
Mapbox Studio style does not render using mapbox.js v3.1.1

### ISSUE THREAD

**Issue by parry-drew** [mapbox/mapbox.js#1260]
### Steps to Trigger Behavior
 1. There is a specific style we host on mapbox Studio that will render in in mapbox-gl.js, but not mapbox.js.
 2. I can use other styles and access tokens with no issue.
 
### Link to Demonstration
Example of the [style using mapbox.js](https://codepen.io/parry-drew/pen./VdQKRv?editors=0010)
Example of the [style using mapbox-gl.js](https://codepen.io/parry-drew/pen/vrdyxx?editors=0010)

### Expected Behavior
The style will will show a black outline using both js api.

### Actual Behavior
The style does not render using mapbox.js.

**Comment by riastrad** [comment]
:wave: thank you for reporting back in 2018, @parry-drew (and happy new year(s), btw). Unfortunately, it looks like your Mapbox.js snippet is no longer up on CodePen. However, since you first cut this issue we've released Mapbox.js v3.2.1, which should have resolved the issue you've described.
