### ISSUE TITLE
Mapbox js v3.1.1 is supporting leaflet v1.0.2

### ISSUE THREAD

**Issue by krthi** [mapbox/mapbox.js#1262]
I am using mapbox js v3.1.1, I have faced autopanning issue while rendering popup at map. The version of leaflet the mapbox currently supporting is V1.0.2, Based on the documentation of leaflet the autopanning issue at popup is fixed in current version of leaflet (v1.3.1)

**Comment by riastrad** [comment]
@krthi appreciate you reporting this issue way back when. Just wanted to flag for you (and anyone who 👍'd this issue) that v3.2.0 updated the underlying Leaflet version to v1.4.0.
