### ISSUE TITLE
Possible tilejson request race condition in IE

### ISSUE THREAD

**Issue by dhcole** [mapbox/mapbox.js#127]
Hey, I'm seeing what looks like a race condition in IE using `map.addLayer(mapbox.layer().id(layerID))` where sometimes I see a javascript error saying "Unable to get value of the property 'bounds': object is null or undefined". I've seen this with 'center', as well as 'tiles' or 'bounds'. Hard to debug with minified code, but when I built 0.6.6 locally, I see the error points to https://github.com/mapbox/mapbox.js/blob/master/src/layer.js#L61

I can reproduce the bug (sporadically) on this example: http://mapbox.com/mapbox.js/example/layers/ where center is the missing property being called.

Reproduced on IE9 and IE8.

Let me know what else I can provide to help troubleshoot. It's evasive on the example page, but I'm seeing it much more frequently on an internally project, possibly because there's a lot more network activity.

**Comment by tmcw** [comment]
Can you use `mapbox.load` instead? IE JSONP flaw + needing to re-release mapbox.js probably doesn't mesh with the timeline of a client project.

**Comment by dhcole** [comment]
Yea thanks, I'll give that a shot.

**Comment by dhcole** [comment]
`mapbox.load` doesn't solve the issue totally, but that plus wrapping the next calls on `map` in a setTimeout() does seem to help. I'll go with that for now.

**Comment by mateusz-michalik** [comment]
Hey guys, not quite sure why I'm receiving these emails?

**Comment by tmcw** [comment]
@dhcole use [queue](https://github.com/mbostock/queue) with `queue(1)` if you want to do async things serially.
