### ISSUE TITLE
Repeated attribution when using styleLayer

### ISSUE THREAD

**Issue by Albert221** [mapbox/mapbox.js#1271]
That's my code:

```js
const map = new L.mapbox.map('contact-map', 'mapbox.streets', {
    center: coords,
    zoom: 15
});
L.mapbox.styleLayer('mapbox://styles/mapbox/streets-v9').addTo(map);
```

And the attribution is duplicated:

![image](https://user-images.githubusercontent.com/4085280/50376572-ccfdba80-060e-11e9-8d93-4e738c129a7d.png)

How can I fix that?

**Comment by ghost** [comment]
@Albert221 
Did you found a solution for this problem?

**Comment by Albert221** [comment]
I migrated to Mapbox GL JS. Mapbox.js is unsupported :(

**Comment by riastrad** [comment]
Thanks for flagging, @Albert221. Although you've migrated to Mapbox GL JS, it's certainly worth correcting this behavior in any newer releases. (Adding it to a milestone as a result.)

In the meantime, this is not an amazing solution, but in your code you are initializing two layers (`mapbox.streets` and the `styleLayer`) that trigger the default attribution behavior. If possible, you can prevent the duplication by only using one of these layers, i.e.:

```js
const map = new L.mapbox.map('contact-map', {
    center: coords,
    zoom: 15
});
L.mapbox.styleLayer('mapbox://styles/mapbox/streets-v9').addTo(map);
```

**Comment by riastrad** [comment]
Did a little bit of digging today, and I'm confident this is an instance of https://github.com/Leaflet/Leaflet/issues/5355. There's also an open feature request for making it harder to do this type of thing unintentionally here: https://github.com/Leaflet/Leaflet/issues/4925.

For Mapbox.js, I can see how this behavior might be unexpected if you are not aware that passing in the argument `'mabpox.streets'` when initializing `L.mapbox.map` fetches a tileJSON and creates a new layer:
https://github.com/mapbox/mapbox.js/blob/3ac9871841ada8076edc6386f63f0a6dbb853802/src/load_tilejson.js#L9-L19

https://github.com/mapbox/mapbox.js/blob/3ac9871841ada8076edc6386f63f0a6dbb853802/src/format_url.js#L41

The duplication is in fact, two attributions from two different layers' tileJSON (`'mapbox.streets'` tileLayer & the `mapbox/streets-v9` styleLayer)  are being retrieved and concatinated by Leaflet's `Control.Attribution` (see [current implementation](https://github.com/Leaflet/Leaflet/blob/3acb64d9008dce5ef5d163f121579ddc52c62dc9/src/control/Control.Attribution.js#L39-L45)).

I think we can hold off on modifying this behavior for now, as it would be an small, ideological departure from Leaflet's current attribution implementation. In any case, getting to work on https://github.com/mapbox/mapbox.js/issues/1316 would probably make it less likely that this misunderstanding occurs.
