### ISSUE TITLE
Transfer /mapbox.js to docs.mapbox.com

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox.js#1276]
@mapbox/frontend-platform and @mapbox/docs are working together to transfer this site to the new `docs.mapbox.com` domain.

Here are the steps in the process.

- [x] Launch the staging site at `docs.tilestream.net`.
- [x] QA the staging site .
- [x] Launch the production site at `docs.mapbox.com`.
- [x] 301 redirect from `www` to `docs`.
- [x] Adjust target repo list in docs-page-shell.
- [x] Change docs-page-shell so it points to the new URL.
- [x] Change dotcom-page-shell so it points to the new URL.
- [x] Delete `www` files and branches.

We're going to start on this today, and try to finish it today or tomorrow.

**Comment by davidtheclark** [comment]
The staging site is now live at https://docs.tilestream.net/mapbox.js. I ran the link checker and didn't find any problems.

@mapbox/docs could you please check out the staging site before we proceed?

**Comment by katydecorah** [comment]
@davidtheclark 

Everything looks like it's working well, but there are two things I wasn't sure about:
* https://docs.tilestream.net/mapbox.js is a 404 and doesn't redirect to https://docs.tilestream.net/mapbox.js/
* maps in /examples aren't loading, expected in this environment?

**Comment by davidtheclark** [comment]
Thanks, @katydecorah. 

The first point is a CDN configuration problem. Since `mapbox.js` looks like it's requesting a file, a trailing slash is not added and `/index.html` is not appended. We'll have to make a special case for this URL path in the CDN. I'll work on this.

The maps in examples on the current staging site, https://122e4e-mapbox.global.ssl.fastly.net/mapbox.js/, also do not work — so I'm guessing this isn't a problem. When we deploy to production we can check this before we push the redirect live.

**Comment by davidtheclark** [comment]
Another possibility, to keep complexity out of the CDN configuration, would be to change this site's URL to `mapbox-js`. What do you think of those two options, @mapbox/docs ?

**Comment by katydecorah** [comment]
> change this site's URL to mapbox-js

@davidtheclark good solution, I think we should go with that

**Comment by davidtheclark** [comment]
We chatted about keeping the `mapbox.js` URL path for now. That change is live, so https://docs.tilestream.net/mapbox.js should now work fine. Do you see any other problems?

**Comment by katydecorah** [comment]
@davidtheclark works great! I have not found any other problems related to this work

**Comment by davidtheclark** [comment]
The production site is live now at https://docs.mapbox.com/mapbox.js. 

It looks to me like the example maps are working just fine.

Please let me know if you find any problems. Will implement the redirects later today.

**Comment by davidtheclark** [comment]
Transfer is complete!

I switched the repo's main branch to publisher-production, changed the base branch of all open PRs, and deleted dev-pages and mb-pages.
