### ISSUE TITLE
odd zooming behavior

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox.js#128]
Using:

```
  <script src='http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.js'></script>
  <link href='http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.css' rel='stylesheet' />
```

Take from http://mapbox.com/mapbox.js/examples/...

This zooms to null island:

```
  var map = mapbox.map('map');
  map.addLayer(mapbox.layer().id('examples.map-vyofok3q'));
  map.center({ lat: 45.528, lon: -122.663});
  map.zoom(15);
```

While this does not:

```
  var map = mapbox.map('map');
  map.addLayer(mapbox.layer().id('examples.map-vyofok3q'));
  map.center({ lat: 45.528, lon: -122.663});
  map.zoom(15,true);
```

Flipping the order of zoom/center also changes the behavior, which seems really odd. User error or bug?

**Comment by ansis** [comment]
Its come up before and has been considered a user error. Its a result of `map.enforceLimits` being called, which adjusts the coordinate so that the map isn't shifted beyond its edges, which it would be at zoom level 0.

This can be avoided by zooming first, or by using `map.centerzoom`.

**Comment by tmcw** [comment]
Upstream: https://github.com/stamen/modestmaps-js/issues/135

This is definitely confusing though 'correct behavior', better ideas welcome

**Comment by jfirebaugh** [comment]
Obsolete with v1.
