### ISSUE TITLE
Attribution controls are showing twice

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox.js#1289]
When creating a map and adding a simple style layer, the attribution control shows the same content twice.

To reproduce: 

L.mapbox.map('dynamicMapBox', 'mapbox.streets').addLayer(L.mapbox.styleLayer('mapbox://styles/mapbox/streets-v11'));

![Screen Shot 2019-04-02 at 11 27 14](https://user-images.githubusercontent.com/44614102/55391842-6b68b880-553a-11e9-8392-06b253ecca3c.png)

Look at the bottom right. 

This is a known issue already published in 2015. Is this going to be solved?

**Comment by riastrad** [comment]
Thanks for reporting the issue, @ArneMisbaer. I'm going to go ahead and use https://github.com/mapbox/mapbox.js/issues/1271 to track this bug. In the meantime, you can work around the double attribution issue with the recommendation made in https://github.com/mapbox/mapbox.js/issues/1271#issuecomment-576884708
