### ISSUE TITLE
setZoomRange on layers is broken

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#130]
See http://bl.ocks.org/3911736

**Comment by ansis** [comment]
It looks like it was never properly implemented in MM. `provider.sourceCoordinate` can be easily made limit by zoom level, but then you have other layers' tiles being stretched.

Do you think that's alright, or should it be possible to set a zoom range on layers themselves? It can easily be achieved using map events, so I'm not sure if it makes sense to add this.

**Comment by tmcw** [comment]
Closing; v0.6.7 is deprecated.
