### ISSUE TITLE
Can't change the title of L.Marker.

### ISSUE THREAD

**Issue by jim-king-2000** [mapbox/mapbox.js#1301]
There is no API in the doc to change the title of L.Marker. Suggest to add one.

**Comment by riastrad** [comment]
@jim-king-2000 can you give a little bit more context on _why_ you would want to change the title of `L.Marker`? Is there something specific you're trying to do that this blocks?

**Comment by jim-king-2000** [comment]
We intend to display the position of the marker in the title property. Since the position keeps change, we have to set the title every time when it changes. By the way, almost all map APIs (such as Bing Maps, Google Maps, etc...) support the change of the title of the marker.
