### ISSUE TITLE
Spurious request for jsonp load?

### ISSUE THREAD

**Issue by idan** [mapbox/mapbox.js#131]
I'm using mapbox 0.6.6, but with a private tileset that I'm serving up with tilestache.

Here's the tilejson I'm giving it:

```
telostats_tiles = {
    'tilejson': '2.0.0',
    'scheme': 'xyz',
    'name': 'Tel Aviv Light',
    'description': 'A light tileset focusing on the municipality of Tel Aviv, suitable for visualizations.',
    'attribution': 'OSM contributors',
    'bounds': [34.742, 32.026, 34.924, 32.149],
    'minzoom': 13,
    'maxzoom': 17,
    'tiles': [TILESERVER_URL],
    'grids': [],
}
```

However, with every load, I'm getting a 404 from the following XHR request issued by mapbox:

```
http://a.tiles.mapbox.com/v3/.jsonp?callback=grid
```

Any clues on why this request is being made?

**Comment by yuvadm** [comment]
Should note that the extra call comes up when doing `map.setExtent(new MM.Extent(...))`

**Comment by ansis** [comment]
I'm having trouble reproducing. @idan, can you paste or link the code causing the request?

**Comment by idan** [comment]
http://jsfiddle.net/CxMZn/ shows it in action. Open up the console to see the error. It seems harmless—everything works, but I don't get why it's trying to issue that XHR

**Comment by ansis** [comment]
Thanks for the example. This bug (related to #125) has been fixed in master, and will be released soon.
