### ISSUE TITLE
Button events don't fire on iOS

### ISSUE THREAD

**Issue by etburke** [mapbox/mapbox.js#132]
Button touch events in the mapbox.js examples don't seem to be working on my iPhone 4S running iOS 5.1, though marker tooltips and pop-ups do work.

**Comment by tmcw** [comment]
This has been fixed in the geolocation example. Did you see this not working in any other example?

**Comment by etburke** [comment]
Awesome! Thanks for addressing that. I just ran through the examples on an
iPad 3 running iOS 6.0.0. The buttons on the WMS layer example don't seem
to respond and the Toggling UI Controls example buttons, while they do seem
to respond, don't do anything. Also, the opacity bar doesn't seem to
respond. Sorry - I wish I had more time to test.

**Comment by tmcw** [comment]
We've updated the examples for v1 and all of their buttons should work correctly.
