### ISSUE TITLE
Update to new Maki icons

### ISSUE THREAD

**Issue by AnniG** [mapbox/mapbox.js#1334]
I would like to use some maki icons that should be available according to https://labs.mapbox.com/maki-icons. But the answer to my request to https://api.mapbox.com/v4/marker/pin-l-aquarium-park.png?access_token=[myToken] gives me a 'Marker "pin-l-aquarium-park" is invalid.' Same for amusement-park, bowling-alley, castle, fence and probably more.
Is there a chance you could update your API? Thanks for your great work!

**Comment by riastrad** [comment]
👋 @AnniG, the API you're referring to is a deprecated one that will not be receiving any updates in the future. I would highly advise against relying on it. Over https://github.com/mapbox/mapbox.js/issues/1315, I briefly explored a few alternative ways to retrieve or generate markers without relying on the old API. 

I didn't find a clean solution for Mapbox.js, but depending on your implementation there may be some good starting points there.
