### ISSUE TITLE
Maps with CSS direction: rtl render incorrectly

### ISSUE THREAD

**Issue by idan** [mapbox/mapbox.js#135]
A map element whose parents have the CSS `direction` property set to `rtl` will render incorrectly, with results ranging from totally borked to "almost normal".

I don't know if it makes sense for mapbox.js to set `style="direction: ltr;` on map elements, but given that all of the tile and marker positioning relies on that assumption, I'd at least document this somewhere.

Cheers!

**Comment by tmcw** [comment]
Moved to https://github.com/modestmaps/modestmaps-js/issues/59
