### ISSUE TITLE
"zoomed" event not triggered when animate is true

### ISSUE THREAD

**Issue by franckalbinet** [mapbox/mapbox.js#138]
"zoomed" event is only triggered when animate is set to "true". 

Triggered when m.centerzoom({ lat: -33.563, lon: -66.09 }, 17, true); 

Not triggered when m.centerzoom({ lat: -33.563, lon: -66.09 }, 17, false);

**Comment by tmcw** [comment]
Closing; v0.6.7 is deprecated.
