### ISSUE TITLE
Refine retina versions of controls

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#14]
This should be _the_push to make things perfectly retina & mobile compatible.
- DONE: zoom controls should adapt or look correct at 1:1 px
- interaction controls may need the fix in mapbox/wax#198
- should users be able to supply a retina version of their tiles?

**Comment by tmcw** [comment]
Removing from milestone: retina versions of tiles and the retina tweak for interaction will come in the next push.

**Comment by tristen** [comment]
Sorry I should have responded to this one:

> DONE: zoom controls should adapt or look correct at 1:1 px

I didn't do any work here - isn't this a TODO?

**Comment by tmcw** [comment]
zoom controls look 'fine' since the pixels are mostly doubled fine, but now I'm realizing that fullscreen etc will need a boost
