### ISSUE TITLE
Layer switcher example broken

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox.js#142]
The [layer switcher example](http://mapbox.com/mapbox.js/example/layers/) for mapbox.js seems glitchy. Clicking on "Layer 1" to deselect it hides everything in Chrome.

Any ideas @tmcw?

**Comment by wboykinm** [comment]
Same for FF and IE. It's been wonky for awhile now. Further reason to [update this one](http://bl.ocks.org/4178338) to mapbox.js, right? :)

**Comment by willwhite** [comment]
@wboykinm not sure I follow. That gist you link to does use mapbox.js.

**Comment by wboykinm** [comment]
Veeeeery imperfectly - still running `MM.map` - more details [over on support.](http://support.mapbox.com/discussions/general-questions/8825-consolidating-a-switcher-to-mapboxjs)

**Comment by willwhite** [comment]
Assigned to [Tender discussion #8825](http://support.mapbox.com/discussions/general-questions/8825-consolidating-a-switcher-to-mapboxjs).

**Comment by jfirebaugh** [comment]
Seems to be working in v1.0.0.
