### ISSUE TITLE
setLayerAt drops location when switching layers

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox.js#146]
Using `setLayerAt` to switch between layers in the `mapbox.load` framework, the layers lose location info. [This example](http://bl.ocks.org/4331911) shows the behavior: The first time you switch away from a layer it retains the layer's map position whatever panning or zooming is done with the subsequently-set layer. When switching back to a previously-loaded layer, the former location is returned, and the map no longer responds to pan/zoom controls.

Steps to the bug on chrome,ie,FF and safari:
1. pan/zoom a bit on load
2. switch to a different layer
3. pan/zoom somewhere else
4. switch back to original layer

Also throws the following JS error at step 4 above:

```
Uncaught TypeError: Cannot call method 'getTile' of null                   mapbox.js:2
e.Layer.inventoryVisibleTile              
e.Layer.draw                      
mapbox.layer.draw            
e.Map.draw                    
_redraw 
```

**Comment by wboykinm** [comment]
`MM.getFrame(this.getRedraw());` looks like a prime culprit [in the source build](https://github.com/mapbox/mapbox.js/blob/master/dist/dev/mapbox.uncompressed.js#L3970). Is there a way to change its behavior?

**Comment by tmcw** [comment]
Closing; v0.6.7 is deprecated.
