### ISSUE TITLE
Disable Zoom and Panning while still allowing Markers

### ISSUE THREAD

**Issue by sethrubenstein** [mapbox/mapbox.js#151]
So when I have a layer or multiple layers with markers and I want to disable zoom and panning I imagine I'd use the example in the docs and when calling my Map variable ala

```
var map = mapbox.map('map');
```

that I would need to add `layer, null, []` to the map so it would be like this....
`var map = mapbox.map('map', layer, null, []);``
but that does not work and instead the map doesnt even load.

Any ideas?

**Comment by tmcw** [comment]
Please [enable web developer extensions](http://macwright.org/enable-web-developer-extensions/) and check for a specific error here.
