### ISSUE TITLE
addLayer layer draw order

### ISSUE THREAD

**Issue by bengolder** [mapbox/mapbox.js#152]
I've attempted to create [my own d3 svg layer](http://bl.ocks.org/4516091) based on [the example in the api documentation](http://mapbox.com/mapbox.js/example/vectors-with-d3/).

Everything seems to work except that the svg layer is always drawn underneath the tile layer.

I've tried adjusting the z-index of the div node that holds the svg layer, but this z-index value is always converted to 'auto'.

I've also tried insertLayerAt instead of addLayer to change the layer order, but this doesn't seem to help.

Here's the script:

https://gist.github.com/4515842

**Comment by bengolder** [comment]
here's a example to show it in action, this time with insertLayerAt:
http://bl.ocks.org/4516091

**Comment by bengolder** [comment]
resolved. 

If I put {position:relative} in the css for my svg layer parent node, it displays on top of the map.

**Comment by tmcw** [comment]
Yes, this is just a positioning problem; in other cases MM will use position-relative for its own layers.
