### ISSUE TITLE
Marker drawn callback fired too early?

### ISSUE THREAD

**Issue by chancancode** [mapbox/mapbox.js#153]
Is there any reason why the marker 'drawn' callback is fired before the markers are repositioned? I'm trying to pan the map the the center of my custom tooltip window (instead of panning to the coordinates it is attached to, so that the entire marker windows is guaranteed to be visible), but that requires the tooltip window / marker to be positioned correctly on the drawn callback so that it could correctly calculate the offset.

Offending line is here: https://github.com/mapbox/mapbox.js/blob/master/dist/dev/mapbox.uncompressed.js#L8234

**Comment by tmcw** [comment]
Moved to markers.js https://github.com/mapbox/markers.js/issues/51
