### ISSUE TITLE
Layer composite not working when using mapbox.load

### ISSUE THREAD

**Issue by miguelpeixe** [mapbox/mapbox.js#154]
When using the code below I'm not getting composite, even when passing through the layers and setting composite to true. I got it working by not using mapbox.load. Is it a bug?

``` javascript
mapbox.load(layers, function(data) {
    var map = mapbox.map('map');
    $.each(data, function(i, layer) {
        map.addLayer(layer.layer);
    });
}
```

**Comment by miguelpeixe** [comment]
Probably a chained question: can't I use layer interaction when enabling composite layers?

**Comment by tmcw** [comment]
Are your layers coming from MapBox or another source?

**Comment by miguelpeixe** [comment]
MapBox

**Comment by miguelpeixe** [comment]
Here's a working example @tmcw 
http://jsfiddle.net/ffTtH/

**Comment by tmcw** [comment]
This is a dumb bug in `mapbox.js`: ticket #156 filed for it.

The workaround is to set `_mapboxhosting` to `true` on layers loaded with `mapbox.load`: http://jsfiddle.net/CSSHr/

**Comment by miguelpeixe** [comment]
Great, thanks
