### ISSUE TITLE
Layer interaction only working for last layer

### ISSUE THREAD

**Issue by miguelpeixe** [mapbox/mapbox.js#157]
I just realized that tilejson interaction is only working for the last layer.

**Comment by miguelpeixe** [comment]
Example:
http://jsfiddle.net/ST43C/1/

Purple and blue areas are different interactive layers. Purple is the last one and the only one working.

**Comment by miguelpeixe** [comment]
Any news on this matter? ModestMaps + Wax handles this just fine.

**Comment by tmcw** [comment]
Closing; v0.6.7 is deprecated.
