### ISSUE TITLE
Wrapping broken

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox.js#160]
Downstream: http://support.mapbox.com/discussions/tilemill/5192-whole-world-map-bounds
http://www.theloop.ca/news/all/map-of-the-week/article/-/a/1404116/Global-military-expenditures-How-does-Canada-rank-

Seems to break at different locations, not always at the date line.

**Comment by tmcw** [comment]
Closing; v0.6.7 is deprecated.
