### ISSUE TITLE
compositing

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#163]
decide how we're going to abstract or if we're going to abstract automatic tile-based compositing and how this interacts with discrete layers in leaflet.

**Comment by tmcw** [comment]
Okay: here's my thinking here:

We should support explicit compositing only, in the layer type. So right now we support

``` javascript
L.TileLayer.MapBox({ id: 'mapbox.foo' });
// shortcut
L.TileLayer.MapBox('mapbox.foo');
```

We would allow for

``` javascript
L.TileLayer.MapBox('mapbox.foo', 'mapbox.bar');
// or
L.TileLayer.MapBox([{ id: 'mapbox.foo' }, { id: 'mapbox.bar' }]);
// or
L.TileLayer.MapBox({ id: 'mapbox.foo' }, { id: 'mapbox.bar' });
```

**Comment by jfirebaugh** [comment]
I think just commas is good, no?

**Comment by tmcw** [comment]
Yeah, everything else is a bad abstraction.
