### ISSUE TITLE
tilejson support

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#167]
Here we go.

MapBox.js has quite a few parts that download tilejson in different ways. Here's a review of how they work or don't.

`mapbox.load` is just like `wax.load`. It is equivalent to a `$.ajax` call:

``` js
mapbox.load('foo', function(o) {
  // user makes map with data in o
});
```

`mapbox.auto` makes a map and returns it. Thus it is the 'one liner' option, but can have a callback, just like `mapbox.load`.

``` js
// a map in one line
mapbox.auto('div', 'foo');

mapbox.auto('div', 'foo', function(map) {
  // user can customize the map
});
```

`mapbox.layer().id()` is a 'fake async call'. It's a layer that you can add to a map that refreshes itself when it loads data async, but frees you from generally having to think about its asyncness.

``` js
mapbox.map('foo').addLayer(mapbox.layer.id('foo'));
```

And so it goes. The issues:
## Nobody Understands Async

Many users are writing Javascript for the first time or are not full time developers, and do not have concepts of async or what's happening with AJAX. We are also barely in the place to educate them about this, and other frameworks do not educate them about this.

And so we see classic async errors

``` js
mapbox.auto('foo', function(map) {
});
elem.onclick = function() { map.doSomething(); }; // fail
```

This is the main justification for `mapbox.layer` - that it encourages users to scope the map normally. Otherwise they rarely do, and this is a major support pain point.
## Round trips are expensive

TileJSON calls block the map from rendering and thus can make map views seem slower than the competition.
## Maps are Update-oriented

Users often have a set of layers a, b, c - and sometimes the mega-tons-of-layers case where obviously something is institutionally wrong but it's not our place to fix that.

And so interacting with layers that are async-added but are needed after pageload and sometimes re-needed is tricky.
## Where Do We Go

Open to unconventional options here as well as conventional options.
- mapbox.com/foo.js?layers=a.foo,b.foo - something that you can include as a script tag that 'makes those layers available' by just straight-up adding them to a MAPBOX_LAYERS array or something like that
- blocking xmlhttprequest calls. I'm serious
- lots of docs for async requests
- encouraging people only to use tilejson at a different point, or when a simple layer template 'is not enough'.
- having tiles show up immediately and the rest of the details come in with an async call

Please add more.

**Comment by jfirebaugh** [comment]
So the "hide the async approach inside L.TileJSON.LayerGroup" approach works OK. The API isn't as nice as `mapbox.auto` for this simple case -- do we still want to do that?

**Comment by jfirebaugh** [comment]
Added mapbox.auto in 0985e50f9ad87dc8aa6867fce058aa134d718957.
