### ISSUE TITLE
rebuild swipe example

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#168]
good learning example

not the first ones here: https://groups.google.com/forum/#!msg/leaflet-js/vXU_bir6JsA/2aEpOU7XGvQJ

**Comment by jfirebaugh** [comment]
Main issue here is the [lack of a public API](https://github.com/mapbox/mapbox.js/commit/9b450083d044bc584bb541e97b8a5a39f43faa75#L0R55) to get a DOM element for the layer.

**Comment by jfirebaugh** [comment]
Also panning and zooming is broken (same as the mailing list post).

**Comment by tmcw** [comment]
@mourner any way you can see this working in Leaflet?

**Comment by mourner** [comment]
I'll check this out.

**Comment by tmcw** [comment]
Waiting for the GridLayer refactor in Leaflet I assume. Retagging postv1

**Comment by hrwgc** [comment]
fwiw, a swipe demo using v1 would be helpful for us to build something for a Monday released blog post. It looks like it is a bigger challenge than originally expected, so we can plan on using previous mapbox.js unless I hear otherwise.  @tmcw

**Comment by jfirebaugh** [comment]
It looked difficult to reimplement swipe with Leaflet, so I would go with v0 if you're on a deadline.

**Comment by mourner** [comment]
@tmcw I rebuilt the swipe example in Leaflet, commiting it to mapbox.js examples now. Do we need to support IE9 in it? I'd love to use input type=range instead of using the old hacked-together custom slider.

**Comment by tmcw** [comment]
Examples don't need to support all browsers - implement it the way you think is best.

**Comment by mourner** [comment]
Awesome, will do.

**Comment by mourner** [comment]
https://www.mapbox.com/mapbox.js/example/v1.0.0/swipe-layers/

**Comment by tmcw** [comment]
![](http://media3.giphy.com/media/WKdPOVCG5LPaM/giphy.gif)

Tweeted from MapBox: https://twitter.com/Mapbox/status/415183516226564096
