### ISSUE TITLE
custom styles

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#169]
should we have custom control styles for zoom buttons, etc? /cc @tristen

**Comment by tristen** [comment]
Are you suggesting more flexibility than altering the default style and icons with css?

**Comment by tmcw** [comment]
Do you want more flexibility? Let's brainstorm for how we can play the idea of theming that gets us a strong win as far as 'mapbox doing beautiful well'.

Bootstrap!

**Comment by wboykinm** [comment]
+1000. Unless you're being sarcastic.

**Comment by tmcw** [comment]
@wboykinm not being sarcastic, I ran out of sarcasm last year :/

**Comment by tristen** [comment]
Starting sketching some of this out here: http://github.com/tristen/map-controls currently, I just have a light and dark theme with graphic src.

@tmcw and I talked about this and it would be great to see nice UI styles for each of the preset maps.

**Comment by wboykinm** [comment]
@tristen That's some serious hotness. One Q: is it contrary to your intended look to lighten the tooltip/associated text in the dark theme [like this](http://bl.ocks.org/wboykinm/4978655)? I just tried to match the contrast of the other UI elements.

**Comment by tristen** [comment]
@wboykinm Awesome! 

As for the tooltip in the dark theme, I wanted the content area of the tooltip to remain the same as I ultimately have no control over what goes in it and it should otherwise remain predictable.

I think the treatment you gave the tooltip in your example works great for this scenario.

**Comment by wboykinm** [comment]
Ah good point; dark text totally matches the Graphite theme better.

**Comment by jfirebaugh** [comment]
Let's start by getting @tristen's [demo](http://tristen.ca/map-controls/demo/) ported to mapbox.js v1 examples. @heyitsgarrett, want to take the lead on that?

**Comment by heyitsgarrett** [comment]
Yeah, I actually started in on some styles yesterday. I like the idea of light and dark theming, but don't want to go too much further than that. As @tristen hinted at above, mapbox.js is a utility and shouldn't do too much of the users customization for them. Making it easy to do that is a great idea though.

And as should be no surprise to anyone after that above comment, I hate Twitter Bootstrap :wink:

**Comment by heyitsgarrett** [comment]
I put in basic theme styles for light and dark, all graytones as @tristen had above. I also themed the geocoder and added the class `mapbox-button` for future use on any buttons inside the `leaflet-container`

Open to suggestions as to alternate ways of doing this, but this shows the general idea (also captured in new example `theme.html`)

`<div id='map'></div>`
![Screen Shot 2013-04-09 at 12 38 16 PM](https://f.cloud.github.com/assets/200357/358001/26b74a3c-a134-11e2-8696-24408a6cdcb6.png)

`<div id='map' class='dark'></div>`
![Screen Shot 2013-04-09 at 12 38 05 PM](https://f.cloud.github.com/assets/200357/358000/26b220e8-a134-11e2-8190-abede5faed46.png)

**Comment by tmcw** [comment]
@heyitsgarrett code-wise I think this is ready - can you write some docs to close out this ticket?

**Comment by heyitsgarrett** [comment]
Yeah, although it's a bit strange to fit it into the API.md file, as it's HTML and CSS markup. I suppose we could add a section for _Styling_ or _Theming_ at the bottom. Anyone object?

**Comment by tmcw** [comment]
Sounds good.

**Comment by heyitsgarrett** [comment]
Fixed with 6e752b8325de6767d71dea879a0a32f7a50c8a0f
