### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#170]
let's redo our testing framework. mocha is cool, but we need something that supports IE7 for assertions, so either we need chaijs to start doing that, or use something else.

**Comment by jfirebaugh** [comment]
Let's try [expect.js](https://github.com/LearnBoost/expect.js). Same syntax as chai's `expect`, but works in IE.

**Comment by jfirebaugh** [comment]
863a9a10d14f0f8e1ad0890e5d063f6ffe5fb465
