### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#171]
we need a good strategy for how to handle ssl as-is and as it could be improved in the future.

**Comment by jfirebaugh** [comment]
So, lots of URLs embedded in TileJSON. Can't really do much about those except maybe autodetect the MapBox ones and switch to https as appropriate.

I wonder if we can use protocol-relative URLs ubiquitously?

**Comment by tmcw** [comment]
Done, will make a private ticket for doc update
