### ISSUE TITLE
Kill powered by leaflet

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#172]
Hate this so much.

**Comment by mourner** [comment]
If you insist... :)

``` js
L.Control.Attribution.prototype.options.prefix = '';
```

I'll think about dropping the "powered by" part at least (leaving just the link) for default Leaflet maps too, won't be as obtrusive.

**Comment by tmcw** [comment]
Ref in 8e8ed6d572eeba03973565943cbb71f23866e1c2

**Comment by mourner** [comment]
@tmcw by the way, made it much less obtrusive — check it out :) https://github.com/Leaflet/Leaflet/commit/879b9f987b50f7674be3a87c74e215091fe66319
