### ISSUE TITLE
fullscreen

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#173]
http://elidupuis.github.com/leaflet.zoomfs/ - not buggy but does not do 'true' fullscreen. that's fine, but it replaces the zoom control, which is silly. maybe nogo.

**Comment by mourner** [comment]
There's also some code on this in open pull requests.
Didn't get my hands on this yet my seems like quite a simple thing, perhaps I should just write an officially supported plugin for fullscreen support.

**Comment by jfirebaugh** [comment]
Working on this. @tristen @samanpwbb anyone got a nice fullscreen icon?

**Comment by jfirebaugh** [comment]
Wait, what about http://brunob.github.com/leaflet.fullscreen/?

**Comment by samanpwbb** [comment]
@jfirebaugh here's one based on what we use on mapbox.com: http://cl.ly/3Y2o2C1f3E0j

included both 11x11 and 10x10, so you can ensure it's centered  whether you have an odd or even width container.

**Comment by tmcw** [comment]
@jfirebaugh that has some issues - https://github.com/brunob/leaflet.fullscreen/issues/1 and it also replaces/reimplements the zoom buttons.

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/Leaflet.fullscreen
