### ISSUE TITLE
to fix in leaflet: toGeoJSON

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#176]
https://github.com/Leaflet/Leaflet/issues/712

**Comment by mourner** [comment]
Haven't decided if this should be in Leaflet core or in the editing/drawing plugin (Leaflet.draw). The latter seemed like a better place. What do you think?

**Comment by jfirebaugh** [comment]
Reading through the various issues, it looks like there's significant demand for it independent of Leaflet.draw. If you're not sure about having it in core, what about an independent L.toGeoJSON plugin? Seems like it could be doable in a plugin using `L.Class.include`.

The main obstacle I'm seeing here is round-tripping Features and FeatureCollections. `L.GeoJSON` discards feature properties and I'm not seeing a clear way to keep those around for reserialization.

**Comment by jfirebaugh** [comment]
https://github.com/Leaflet/Leaflet/pull/1462

**Comment by jfirebaugh** [comment]
Not blocked on this for v1.
