### ISSUE TITLE
hash support

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#180]
https://github.com/mlevans/leaflet-hash is not buggy but really, really needs a throttle.

**Comment by wboykinm** [comment]
Seems to [work like a charm](http://bl.ocks.org/d/4617266/#7/48.045/-98.448). Compression might pick up 3KB, but is that really dragging things?

**Comment by tmcw** [comment]
Proofing and fixing hash now.

**Comment by tmcw** [comment]
Done in 9dc37c780c45d26e6cdebc1efff7668607805f3d to sub-issues.
