### ISSUE TITLE
require.js / amd / whatever compatibility

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#182]
this has come up in the past and we should think about playing nice with these.

**Comment by tmcw** [comment]
Ref: http://bit.ly/11SWWth https://github.com/umdjs/umd/blob/master/amdWeb.js

**Comment by mourner** [comment]
I was thinking about adding it in jQuery-like manner https://github.com/jquery/jquery/blob/master/src/exports.js (so that there's no need to do separate AMD builds).

**Comment by tmcw** [comment]
The wonderful (read horrible) thing here is that some our dependencies (reqwest, bean) try to support AMD themselves, and we can't easily package them as internal dependencies. Browser modules suck.

**Comment by mourner** [comment]
Maybe this will help https://github.com/umdjs/umd

**Comment by tmcw** [comment]
Fixed in dafa099a3176968b33120d8ac9283d12ff24e762
