### ISSUE TITLE
unifying components

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#183]
options:
- package.json / npm
- submodules
- 'user downloads for themselves'
- bower/component/whatever

**Comment by jfirebaugh** [comment]
Bower seems like the best bet. It's the only one that has all the packages we want and doesn't tie dependency management to the packaging format.

**Comment by tmcw** [comment]
Using a makefile in 7daa4518d9e2eaf1dd615c75c1fcb0c249fb6ac7

**Comment by tmcw** [comment]
The makefile approach is working well so far, remaining issues here are in other people's courts - getting leaflet and leaflet.hash on npm.
