### ISSUE TITLE
map destroy?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#185]
Does not look like Leaflet has a map destroy method. Maybe I'm missing this. It needs one.

**Comment by mourner** [comment]
Right. Although the resize handler seems like the only reason for it, so it was easy to overlook.

**Comment by jfirebaugh** [comment]
Leaflet/Leaflet#1434

**Comment by jfirebaugh** [comment]
@tmcw Please assign yourself if you are working on something so we can avoid duplicating work. :beers:
