### ISSUE TITLE
TileJSON/L.TileLayer impedance mismatch

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#186]
TileJSON does tile endpoint multihoming via an array of URLs. L.TileLayer does it via a URL template and subdomain string or array. In the general case, transforming the former to the latter is difficult. I've cooked up a [nasty hack](https://github.com/mapbox/mapbox.js/blob/a006857f0085b3f7a5b283febac535787cc8c13c/src/tilejson.js#L43-L54) but we need a better solution.

**Comment by tmcw** [comment]
What's wrong with the nasty hack? Seems like that's the right way to do things - I don't think that tilejson should change for this.

**Comment by jfirebaugh** [comment]
Mainly that it relies on several private methods of L.TileLayer.

**Comment by jfirebaugh** [comment]
Looks like it would be easy to eliminate that with a simple upstream change, will submit a PR.

**Comment by mourner** [comment]
John, sure, I'll be glad to merge it.

Nasty hacks for TileLayer involving private methods is not the best idea because that class is currently a bit of a mess and will probably undergo some refactoring in near future.

**Comment by jfirebaugh** [comment]
Fixed in bb226edb8b834bc57c5bb82996349216b0491add.
