### ISSUE TITLE
Simplify setting map limits

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#19]
Might be a nice feature in mapbox.js to make it easy to set map boundaries. This is currently [pretty modest mappy to do ..](http://tristen.ca/mm-examples/enforce-limits.html)

**Comment by ansis** [comment]
@tmcw Would it be appropriate to simplify this partially in MM?

**Comment by tmcw** [comment]
Sure, however works best

**Comment by ansis** [comment]
Added in 7037c733f8ad67974f986e93ff5618b79d9c0c33

Map limits can now be set using `map.setPanLimits(locations)` where _locations_ is either an instance of MM.Extent, or an array of locations in the order north, west, south, east.
