### ISSUE TITLE
tilejson issues

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#196]
Right now the approach does well with being minimal - no special code required for it to work with native attribution and mapbox.legend. But this needs some work:

Most importantly, there's a real race condition with layer addition - layers will not stay in the order in which they are added

**Comment by jfirebaugh** [comment]
Not sure how to fix the race condition. L.TileLayer constructed without a URL throws errors if added to a map, and Leaflet's support for manually ordering layers is limited to bringToFront/Back.

**Comment by tmcw** [comment]
> Leaflet's support for manually ordering layers is limited to bringToFront/Back.

We should improve this - the [modestmaps layer api is much more complete](https://github.com/modestmaps/modestmaps-js/blob/master/src/map.js#L399)

**Comment by jfirebaugh** [comment]
Leaflet itself doesn't even correctly preserve order: Leaflet/Leaflet#1422.

**Comment by jfirebaugh** [comment]
Fixed upstream, opacity example now has correct z-order.
