### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#197]
this worked pretty well last time:

Maintain an API.md file. Here [it is for mapbox.js](https://github.com/mapbox/mapbox.js/blob/master/API.md). This gets nicely formatted [on mapbox](http://mapbox.com/mapbox.js/api/v0.6.7/). Benefit here is that API is versioned w/ the code.

@jfirebaugh seem fine for this push? need to do a quick look at how leaflet is doc'ed

**Comment by mourner** [comment]
Leaflet docs are maintained as HTML in the gh-pages branch (and gh-pages-master which tracks master changes). Not markdown because there's lots of tables and it's easier that way. I wish GH could support custom tags in MD to make things easier.

**Comment by tmcw** [comment]
@mourner as far as mapbox.js documentation, I think we'll maintain the same flow as pre-leaflet - API.md processed with jekyll and versioned. Seeing some more needs on the leaflet side in #218
