### ISSUE TITLE
write pull request for leaflet for 'auto-new'

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#199]
We want to clear up the classname vs Classname debacle and write code so that

``` js
var m = new L.marker();
var m = L.marker();
var m = new L.Marker();
var m = L.Marker();
```

All work.

**Comment by jfirebaugh** [comment]
I would also push for deprecating the `L.marker` form and removing it for Leaflet 1.0. With auto-new it increases the API surface area for no gain.

**Comment by jfirebaugh** [comment]
Leaflet/Leaflet#1430

**Comment by tmcw** [comment]
This has been written and is aging like fine cheddar.
