### ISSUE TITLE
Document and unify CSS and element structure

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#20]
@tristen this might be interesting to you:

I'd like to start documenting the element structure in mapbox.js - the wax-generated elements, modestmaps, anything that's styled by the mapbox.min.css style - so that we know where things come from, their structure in the DOM, and can provide alternative styles - themes - and maintain them properly.

one upstream: mapbox/wax#101

**Comment by tristen** [comment]
@tmcw sounds good.

How are you seeing these documented? As a wiki page with alternate styles presented as code snippets in the page?

**Comment by tmcw** [comment]
Yep, like a snippet of what the HTML code 'looks like' in the DOM, the default style, and some tips?

**Comment by tristen** [comment]
Assigning. I've sketched some of this out here: https://github.com/mapbox/mapbox.js/wiki/HTML-and-CSS-markup

**Comment by tmcw** [comment]
Okay, added that to Wax https://github.com/mapbox/wax/blob/master/STYLE.md

The site-build script will add files called API.md and STYLE.md automatically to the manual. Assessing needs:
- Wax: done/in-progress
- Markers: no dom, but could use examples?
- Easey: no dom
- Modestmaps: no dom elements that should be styled, right?

I will throw together some examples in markers from 12-12:15

**Comment by tmcw** [comment]
Done in Markers.
