### ISSUE TITLE
naming layers

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#200]
Layers should be named. Right now we have the gotcha:

``` js
var map = L.map('map')
    .setView([0, 0], 3)
    .addLayer(L.TileJSON.layer('examples.map-zr0njcqy'));
// markers are magically added to the map as a layer. how do I access them?
```

mapbox.js/mm right now handle this with named layers, so you can call `getLayer` with a name (and all layers are explicitly added to the map). It doesn't look like Leaflet has this sort of API yet.

**Comment by jfirebaugh** [comment]
You can now do:

```
var layerGroup = new mapbox.layerGroup('examples.map-zr0njcqy');
layerGroup.tileLayer // get the tile layer
layerGroup.dataLayer // get the markers layer
```

And we'll probably do `layerGroup.gridLayer` too.

Is that enough to address this?

**Comment by tmcw** [comment]
I don't think so - a lot of users will want to do

``` js
map.addLayer(mapbox.layerGroup('examples.map-zr0njcqy'));
```

and be up a creek.

**Comment by jfirebaugh** [comment]
I'm not seeing a need to block on Leaflet for this feature. For the common cases, `map.tileLayer`, `map.gridLayer` are sufficient; users who create layers themselves can retain a variable reference to it. I haven't seen an example where this is onerous.

**Comment by jfirebaugh** [comment]
[Relevant](https://github.com/Leaflet/Leaflet/pull/1642)
