### ISSUE TITLE
what does L.TileJSON.layer return?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#203]
Is this a layer? Can you get to the layer that it adds? Need to figure out how to define and document this.

**Comment by jfirebaugh** [comment]
I would document it as such:

> `L.TileJSON.Layer` is a subclass of `L.LayerGroup` which will (when the TileJSON is resolved) contain a `L.TileLayer` and, if a "data" property is present in the TileJSON, a `L.GeoJSON` layer.

Furthermore if Leaflet/Leaflet#1411 is accepted we can say more about the names of the layers. They should be suffixed versions of a name given to the L.TileJSON.Layer, e.g. `<name>-tiles` and `<name>-data`. For MapBox-id-based construction the name can default to the id.

**Comment by tmcw** [comment]
Should it be named L.TileJSON.LayerGroup then?

**Comment by jfirebaugh** [comment]
Yup.

**Comment by tmcw** [comment]
I think we're going to need to refactor this so that it's a viable layer before async-calling TileLayer - plz check out 248c52ec09ab3dd1f412f9e918078ad92d38cdd7 and confirm/deny.

**Comment by jfirebaugh** [comment]
Hmm, if we're following `L.GeoJSON`, `L.TileJSON` should itself be the constructor. Not too crazy about `L.GeoJSON` though.

**Comment by jfirebaugh** [comment]
Confirm it's a problem. Not sure how to fix it though. `L.TileLayer` constructed without a URL throws errors if added to a map.

**Comment by tmcw** [comment]
> Not sure how to fix it though. L.TileLayer constructed without a URL throws errors if added to a map.

One option is to deliver all blank GIF tiles until the tilejson is loaded, or to overload the layer's render method. But both of these need the layer to re-notify the map of its addition when it's loaded.
