### ISSUE TITLE
mapbox.base + API urls

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#205]
`L.TileJSON.Layer#id` is setting the URL with a "a.tiles.mapbox.com" host. Should be "api.tiles.mapbox.com".

**Comment by tmcw** [comment]
Hm, why? Same host, but we can distribute reqs across a/b/c/d with a.tiles.mapbox.com

**Comment by jfirebaugh** [comment]
a/b/c/d aren't documented as API endpoints. Do we want to commit ourselves to supporting API requests on them? Seems like it would be better to have the flexibility of a different host. @yhahn ?

**Comment by yhahn** [comment]
We are def. committed to `a-d` so it should be fine to use them.

**Comment by jfirebaugh** [comment]
Alrighty
