### ISSUE TITLE
support tiled data URLs

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#207]
Probably depends on a symmetric L.GeoJSON API.

**Comment by jfirebaugh** [comment]
Also, do multihoming over the array of data URLs.

**Comment by jfirebaugh** [comment]
This may not be for v1 if we don't actually use it in the API.

**Comment by tmcw** [comment]
Yeah, this is a low priority until there's actually a source of tiled data.

**Comment by jfirebaugh** [comment]
Not for v1.
