### ISSUE TITLE
Include leaflet-hash with package

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#216]
Upstream: https://github.com/mlevans/leaflet-hash/issues/22

**Comment by lxbarth** [comment]
Why was leaflet-hash not included in v1.0.0? Seems to come at negligible weight for functionality that's widely used.

**Comment by tmcw** [comment]
@lxbarth so we were originally wrapping & including a few leaflet plugins, but decided not to because we would have to re-document them (or figure some odd way to bring in docs) and it would be less transparent than having users actually just use the plugins directly. Let's discuss when I get in, there might be other solutions.

**Comment by jfirebaugh** [comment]
Closing; we're going to CDN leaflet-hash (#517) but not bundle it.
