### ISSUE TITLE
Improve Leaflet documentation

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#218]
At the very least, we need much more precise sub-linking in leaflet docs and explicit versioning.

**Comment by mourner** [comment]
What do you mean by precise sublinking? E.g. highlighting the rows of anchored methods?
And how would you recommend to go about explicit versioning?

**Comment by tmcw** [comment]
> What do you mean by precise sublinking? E.g. highlighting the rows of anchored methods?

Ideally one can link to sub-methods, not just headings - like linking to `map.fitBounds` Also, we should use an anchor-link CSS trick like [mapbox's js docs do](http://mapbox.com/mapbox.js/api/v0.6.7/).

> And how would you recommend to go about explicit versioning?

(again kind of just pointing to mapbox.js's docs) - current versions have the API version in the URL http://mapbox.com/mapbox.js/api/v0.6.7/ and out of date versions get a header but stay available http://mapbox.com/mapbox.js/api/v0.6.6/ This way when we link to methods of a pinned version of Leaflet, the link sticks.

**Comment by paulovieira** [comment]
See also Leaflet/Leaflet#1327

**Comment by tmcw** [comment]
We can now deep-link Leaflet docs.
