### ISSUE TITLE
id for tilelayer does not load tilejson, should be documented

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#226]
This can be a leaky abstraction:

``` js
// gets bounds, attribution, legend
mapbox.tileLayer.url('http://foobar.com/foo.json');
// does not.
mapbox.tileLayer.id('foo');
```

**Comment by jfirebaugh** [comment]
Yeah, wasn't sure about this. I was preserving the behavior we had with `L.TileLayer.MapBox({id: 'foo'})`, but it feels like it should be consistent with `layerGroup` and `marker.layer`.

**Comment by jfirebaugh** [comment]
I think we should make this consistent and load the TileJSON.

**Comment by tmcw** [comment]
Yep.
