### ISSUE TITLE
rename mapbox.marker.layer to mapbox.dataLayer

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#228]

**Comment by tmcw** [comment]
:+1: for `markerLayer` instead of `dataLayer`. These may be separate endpoints in the future.

Also: kind of a fan of namespacing concerns, since we also want `mapbox.marker.style` to be accessible. I guess we can just camelCaseEverything instead?

**Comment by jfirebaugh** [comment]
It's more than just markers though -- it's loading from the TileJSON `data` property, which can be arbitrary GeoJSON, and making layers via `L.GeoJSON.geometryToLayer`, which can create polygons, polylines, etc.

**Comment by jfirebaugh** [comment]
Plus we can have a nice four letter symmetry: `tileLayer`, `dataLayer`, `gridLayer`, matching each of the TileJSON properties `tiles`, `data`, `grids`.
