### ISSUE TITLE
Rename mapbox.interaction mapbox.interactionLayer

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#234]

**Comment by jfirebaugh** [comment]
My suggestion is [`gridLayer`](https://github.com/mapbox/mapbox.js/issues/228#issuecomment-14063081).

**Comment by tmcw** [comment]
Hmm, will have to think about this. UTFGrid is somewhat well-known, but gridLayer makes me think that it will produce a visual grid.

**Comment by tmcw** [comment]
Renamed gridLayer in 453d721d6b906f368f0dede27c4b614132f01203
