### ISSUE TITLE
Point Selector double events

### ISSUE THREAD

**Issue by nickhudkins** [mapbox/mapbox.js#237]
mapbox.ui.pointselector adds another point after confirming deletion of a point added.

mapbox.uncompressed.js:7000 appears to hint that you may be aware of said circular reference.

Opening a bug to formalize the problem :)

**Comment by samvasko** [comment]
experiencing the same problem [example](http://bl.ocks.org/yhahn/4251201)

**Comment by tmcw** [comment]
Closing; v0.6.7 is deprecated.
