### ISSUE TITLE
setTilejson or setTileJSON

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#239]
God I hate camelCase.

**Comment by jfirebaugh** [comment]
`setTileJSON`. Matches `L.GeoJSON` and (hopefully soon) `#toGeoJSON`.

Leaflet can't really claim consistency though. `L.geoJson`, `L.DomUtil`, but `L.CRS`...

**Comment by tmcw** [comment]
^ what I said about camelcase, again. `setTileJSON` then.
