### ISSUE TITLE
layout options for controls.

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#24]
cc @yhahn @tmcw 

Tom and I talked about the possibility of introducing options in mapbox.js to control the layout position of map control elements. Options like:
- vertical/horizontal alignment
- area placement like top left, top right ..

Not sure if this is the best idea but it would make it easy for authors to control the design of controls without touching the css.

**Comment by yhahn** [comment]
I'm not a big fan of this level of configurability -- i think we should stick with a single, consistent layout.

If we allow several layouts, every control must concept its way into each possible layout and it will put more stress on being creative with additional controls that do are not simple toggle on/off buttons, e.g. share, geocoding, etc.

Example:

![geocoder](https://dl.dropbox.com/u/4521056/tmp-wax-geocoder.png)

**Comment by tristen** [comment]
Well there's a good use case right there and we shouldn't arrest flexibility like this. Closing.
