### ISSUE TITLE
markerLayer should be more marker-oriented

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#247]
- Don't support non-point geometries -- this isn't a general data layer.
- Rename get/setGeoJSON -> get/setMarkers

**Comment by tmcw** [comment]
What's the absolute reason why we'd restrict it like this?

**Comment by jfirebaugh** [comment]
Same reason why we're not supporting tiled data URLs -- mapbox.js is targeted to the MapBox API, which provides static markers. That gives us a well defined API surface area -- for both the API we consume, and the API we provide. If we want to support arbitrary GeoJSON, I think we should do a full TileJSON data implementation. In between, the requirements are less clear, and implementing to unclear requirements is dangerous when API-building.

In the meantime, if people want arbitrary GeoJSON, we can point them to L.GeoJSON.

**Comment by tmcw** [comment]
Okay, let's just do it that way then. fwiw, users will think `get`/`setMarkers` accepts/returns arrays of `L.marker` objects.

**Comment by jfirebaugh** [comment]
Good point. `get`/`setMarkersJSON`?

**Comment by tmcw** [comment]
They're going to think we invented MarkersJSON

**Comment by jfirebaugh** [comment]
Fine with this as is.
