### ISSUE TITLE
Examples of PHP / Python / whatever generating GeoJSON and feeding into markers?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#25]

**Comment by ansis** [comment]
What do you have in mind here? Generating GeoJSON from what?

**Comment by tmcw** [comment]
Not sure, really - like this would probably be a really tricky thing to demonstrate in a resuable way. But we get questions about how to get data out of systems, so like maybe pointers to [views_geojson](http://drupal.org/project/views_geojson/), [some wordpress plugin](http://wordpress.org/extend/plugins/tags/geojson) or something would be useful here?

**Comment by tmcw** [comment]
Too unclear; have other ideas here.
