### ISSUE TITLE
make it work with browserify

### ISSUE THREAD

**Issue by max-mapper** [mapbox/mapbox.js#253]
hiya it'd be cool if this worked with browserify, e.g.

``` js
var mapbox = require('mapbox.js')
```

I tried to figure out your makefile and stuff but it was way too complicated for me

**Comment by tmcw** [comment]
There's now a proper entry for `"main"`, but somehow the pretty convoluted UMD-in-module-in-whatever setup is trying to init `L.Hash` before Leaflet itself, and failing there.

**Comment by jfirebaugh** [comment]
I think the problem is that the L [initializer](https://github.com/Leaflet/Leaflet/blob/master/src/Leaflet.js) gets run in a scope that has `exports` defined, so assigns to it rather than `window`.

**Comment by joeybaker** [comment]
Hmm… I'm still getting a build error:
`Error: module "Leaflet/dist/leaflet-src" not found from "node_modules/mapbox.js/index.js"`

**Comment by jfirebaugh** [comment]
Yep, there was a problem with the leaflet package. Please try alpha2.

**Comment by joeybaker** [comment]
Got it. thanks!
