### ISSUE TITLE
Enable/Disable event handlers 

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#254]
It would be nice to provide a means to enable or disable particular UI interactions such as scrollZoom when you are, say in fullscreen mode. Currently, after the map is initialized, it doesn't appear as though you can remove or add interactions from the eventhandlers array.

**Comment by tmcw** [comment]
You can [enable and disable event handlers after map initialization](http://bl.ocks.org/tmcw/4724143). It could be made easier, though.
