### ISSUE TITLE
border-bottom should be zero

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#256]
http://support.mapbox.com/discussions/general-questions/14151-marker-click-area-in-ie-too-small#comment_26105443

**Comment by heyitsgarrett** [comment]
I've removed borders from any marker styles in mapbox.js v1, so shouldn't be an issue there. Added new tag "legacy" to keep track of < v1 issues.

**Comment by jfirebaugh** [comment]
Obsolete with v1.
