### ISSUE TITLE
Update L.UTFGrid

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#257]
https://github.com/nprapps/Leaflet.utfgrid/commit/9553d2c246f4471d08832036f93c471e4916bd85

**Comment by jfirebaugh** [comment]
What is it you want from that fork?

**Comment by tmcw** [comment]
The current implementation doesn't register any listeners for when tile loads complete - ideally we can support an api like `gridAtPt(xy, cb)`

**Comment by tmcw** [comment]
All right, so Leaflet's API for event-data is strictly sync, so no real wonderful moment there, but the refactored api should allow for programmatic events.
