### ISSUE TITLE
Check and log arguments

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#258]
So @heyitsgarrett & @jfirebaugh I have been thinking about one angle of the API: arguments validation.

In the field, we see a fair amount of people writing stuff like

``` js
geoJsonLayer.setGeoJSON('myfile.geojson');
```

And getting a cryptic error since you should give it an object, not a string. I'm wondering if, for certain methods or possibly all, we should have code to check and assist users in this case. For instance, Google Maps produces console messages like

```
Uncaught Error: Invalid value for property <center>: foo 
```

This is a potential kludge and not very javascripty but may add a touch of 'friendliness' that makes mapbox.js more appealing to new users.

```
 _________
< discuss >
 ---------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by mourner** [comment]
I think this makes a lot of sense for a limited selection of methods. You won't do that for every method of course, but adding this in e.g. just 5-10 places that usually cause the most confusion can make things easier.

**Comment by heyitsgarrett** [comment]
Ditto @mourner - creating a general handler that throws a console log hint seems perfect, especially as the library is intended to work for folks who aren't too keen on the nitty gritty of JavaScript.

**Comment by tmcw** [comment]
First pass in a71404902f570c61a20d110b397cb80bf22fceb4

**Comment by tmcw** [comment]
Done with `mapbox.strict` and `mapbox.strict_oneof`
