### ISSUE TITLE
Map reattachment

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#260]
A common error with mapping libraries is a tendency to conflate initializers with access.

So, the jQuery pattern of

``` js
$('#foo').attr('foo', 'bar');
$('#foo').attr('foo', 'baz');
```

Is used like

``` js
mapbox.map('foo').addLayer(mapbox.layer('foo'));
mapbox.map('foo').addLayer(mapbox.layer('baz'));
```

Obviously the answer to both is "variables" but that is not always common.

The question is: if calling `mapbox.map` on a div twice has no discernable meaning or use, should it be an accessor the second time instead of a constructor?

```
 _______
< MAYBE >
 -------
        \   ^__^
         \  (xx)\_______
            (__)\       )\/\
             U  ||----w |
                ||     ||
```

**Comment by mourner** [comment]
Leaflet throws "map container already initialized" so that people could learn to put it in a variable for reuse already, you can adopt the same strategy. :)
