### ISSUE TITLE
geocoder autocomplete

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#264]

**Comment by jfirebaugh** [comment]
Autocomplete using the forward geocoder with partial input?

**Comment by tmcw** [comment]
Using globs: http://api.tiles.mapbox.com/v3/examples.map-vyofok3q/geocode/aust*.json

**Comment by gajus** [comment]
Based on this post, I am guessing that MapBox does not offer autocomplete functionality, supposedly, similar to https://developers.google.com/places/documentation/query.

**Comment by tmcw** [comment]
@gajus we offer it in the REST API, as in comment 2, but have not wrapped it in a MapBox.js UI, as in the title of this issue.

**Comment by gajus** [comment]
I must be missing something.

   http://api.tiles.mapbox.com/v3/examples.map-vyofok3q/geocode/aust*.json

This should supposedly complete "aust" query? To be precise, I want user to enter their post code, which could then be translated to their location.

**Comment by tmcw** [comment]
So, like http://api.tiles.mapbox.com/v3/examples.map-vyofok3q/geocode/20009.json ? Please open a ticket at [support.mapbox.com](http://support.mapbox.com/) - this ticket is for the MapBox.js integration only, not the REST API behavior.

**Comment by gajus** [comment]
I see. This doesn't work with UK/FR or other countries in Europe that I've tried. Thank you. I might look for an alternative solution.

**Comment by vicmosin** [comment]
So finally, do you have plans for implementing this feauture or not? This ticket is open for more than 1 year...

**Comment by jfirebaugh** [comment]
This was added in 2.1.0.
