### ISSUE TITLE
Camelcase rules!

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#268]
Actually, camelCase sucks but we need some camelCase rules.
- `foo.setURL` or `foo.setUrl`
- `foo.setGeoJSON` or `foo.setGeoJson`

My golden rule lately has been _honest acronyms, no exceptions_. This is not how Leaflet rolls - L.GeoJSON versus L.geoJson for some weird reason.

/cc @heyitsgarrett @jfirebaugh

**Comment by jfirebaugh** [comment]
+1 honest acronyms

**Comment by tmcw** [comment]
Cool, covered in https://github.com/mapbox/mapbox.js/blob/v1/DESIGN.md
