### ISSUE TITLE
better looking marker popups

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#273]

**Comment by heyitsgarrett** [comment]
![Screen Shot 2013-04-10 at 10 51 14 AM](https://f.cloud.github.com/assets/200357/362640/21a1a7e4-a1ee-11e2-8973-c774f8506697.png)

Ahhhh, that's the ticket.

**Comment by tmcw** [comment]
@heyitsgarrett will this stand out enough on light styles like https://tiles.mapbox.com/tmcw/edit/map-ap45hcor#10.00/38.9747/-76.9316 ?

**Comment by heyitsgarrett** [comment]
Good point, it does run into some issues with very light land, etc. Drat.

![Screen Shot 2013-04-10 at 10 59 37 AM](https://f.cloud.github.com/assets/200357/362695/5e60817c-a1ef-11e2-8cf3-b18f92207612.png)

I'd rather not add a border to the markers, at least not by default. Will think on it.

**Comment by tmcw** [comment]
basically the default style needs to be aggressively middle-of-the-road and we can make things look nicer in themes.

**Comment by heyitsgarrett** [comment]
I agree re:middle-of-the-road.

Adding a 2-3px gray stroke seems like kind of a cruddy solution, but is a possibility. We could also consider either extending L.Popup with a `backgroundColor` property or, and this is growing on me, going a bit more whole-hog on theming. Something like `map.setTheme( themeName [, options])`

``` js
map.setTheme('dark',{
    'popupBackground' : '#ccc'
});
```

This potentially reeks of bloat, but I like the idea of mapbox.js hooking into MapBox's larger design-focused goals.

**Comment by yhahn** [comment]
FWIW I think no stroke is fine, esp. if it's easy for a designer to adjust in a straight CSS override.

In my experience, there is no one-size-fits-all here -- someone will always throw a custom map at you where the solution you thought was robust starts looking cruddy.

**Comment by heyitsgarrett** [comment]
FWIW, I've added the relevant CSS to style a marker to the [theme example](https://github.com/mapbox/mapbox.js/blob/d9412c18c999f4193f9e051f97912512bd618326/examples/theme.html)

**Comment by heyitsgarrett** [comment]
I'm satisfied with our CSS override in the theme example - tooltips look great for most map styles, so I'm comfortable closing.
