### ISSUE TITLE
refactor mapbox.* functions

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#277]
we shouldn't have this many functions living under the mapbox namespace - I've started moving stuff into util, but will work on better logical groups.

**Comment by jfirebaugh** [comment]
We can also consider not exposing all of them as public API.

**Comment by tmcw** [comment]
yes, definitely - stuff like lbounds should not be exposed. but we need better internal groupings.

**Comment by tmcw** [comment]
mapbox functions moved to url and util, no public utils on mapbox.\* at this pt.
