### ISSUE TITLE
Kill setUrl and other methods from mapbox.tileLayer

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#278]
This will mess up / do nothing.

**Comment by tmcw** [comment]
Killed in c05ca90cbc4044fe9ac514da48743da7916ae408

**Comment by kevinschaul** [comment]
Would be great if this (and any other changes to L.TileLayer) were documented: https://www.mapbox.com/mapbox.js/api/v2.1.5/l-tilelayer/
