### ISSUE TITLE
tileLayer.setOptions

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#279]
What should be the pattern for setting options on objects like markerLayer and tileLayer instances after creation? There's a [util setoptions method](http://leafletjs.com/reference.html#util) but that isn't exposed in classes by default afaik.

**Comment by jfirebaugh** [comment]
Setters for individual options. TileLayer#setOpacity, MarkerLayer#setFilter.

**Comment by tmcw** [comment]
Yeah... I've added a `tileLayer.setOptions` atm - seems like adding lots of setters will bloat the api, and it would be great to have a jquerystyle `.attr(foo, bar)` interface if possible.

**Comment by jfirebaugh** [comment]
Individual setters seem better to me:
- I doubt changing options like `tileSize` or `detectRetina` will work post-initialization.
- Setting `opacity` or `zIndex` won't do the correct things that `setOpacity` and `setZIndex` do, giving users a way to get confused.

If we get lots of options on top of what Leaflet supports, then let's worry about API bloat. Right now there are only a couple.
