### ISSUE TITLE
Push to s3 architecture

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#28]
Discussed this with @willwhite yesterday: our gameplan is
- Push this library, versioned, to js.mapbox.com which is an s3 repo
- Make sure to set very-long expires on all of the component files
- Make a shell script or makefile to make this clearer

**Comment by willwhite** [comment]
Looks like we have to solve the gzip problems on S3 as well. It'll be good to have automation for that.

**Comment by tmcw** [comment]
Started in 03deb5344a3cf2c50248fc59c7a17410c7b487be

**Comment by tmcw** [comment]
Pushed & live.
