### ISSUE TITLE
grid layer by default?

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#286]
Should `mapbox.map` default to creating a grid layer or not? v0.6 didn't, many existing examples don't expect it. But 'just do what the TileJSON says' is a good default.

**Comment by tmcw** [comment]
Right now the state of layers in Leaflet is 'bad': going from

``` js
var map = mapbox.map('foo', 'bar-interactive');
```

Into an interactive map is fraught. There's no simple way to grab the grid layer so you can reference it in a gridControl. Erring towards deemphasizing `mapbox.map` and having it do as little as possible until this is more mature.

**Comment by jfirebaugh** [comment]
`new mapbox.gridControl(map.gridLayer)`?

**Comment by tmcw** [comment]
We're restricting maps to a single gridLayer?

**Comment by jfirebaugh** [comment]
No, but if you create them yourself you probably have a reference to them.

**Comment by jfirebaugh** [comment]
On by default seems good.
