### ISSUE TITLE
remaining examples

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#292]
- [x] [Custom Marker](http://mapbox.com/mapbox.js/example/custom-marker/)
- [x] [Custom Marker Tooltip](http://mapbox.com/mapbox.js/example/custom-marker-tooltip/)
- [x] [Cycle Markers](http://mapbox.com/mapbox.js/example/cycle-markers/)
- [x] [External Layers](http://mapbox.com/mapbox.js/example/external-layers/)
- [x] [Interactive External](http://mapbox.com/mapbox.js/example/interactive-external/)
- [x] [Layers](http://mapbox.com/mapbox.js/example/layers/)
- [x] [Linking Externally](http://mapbox.com/mapbox.js/example/linking-to-external-data/)
- [ ] ~~[Load](http://mapbox.com/mapbox.js/example/load/)~~ (doesn't seem relavent to this version. -ansis)
- [x] [Marker Movement](http://mapbox.com/mapbox.js/example/marker-movement/)
- [x] [Marker Load](http://mapbox.com/mapbox.js/example/markers-load/)
- [x] [Non Exclusive Markers](http://mapbox.com/mapbox.js/example/non-exclusive-markers/)
- [x] [Pan and Vertical Zoom](http://mapbox.com/mapbox.js/example/pan-and-vertical-zoom/)
- [x] [d3](http://mapbox.com/mapbox.js/example/vectors-with-d3/)
- [x] [YouTube](http://mapbox.com/mapbox.js/example/youtube-embed/)
- [x] [Zoom Bar](http://mapbox.com/mapbox.js/example/zoom-bar/)
- [x] [Zoom Lens](http://mapbox.com/mapbox.js/example/zoom-lense/)
- [ ] ~~[Marker CSV](http://mapbox.com/mapbox.js/example/marker-csv/)~~
- [x] [Toggling UI](http://mapbox.com/mapbox.js/example/toggling-ui/)

**Comment by tmcw** [comment]
Will grab the linking externally example next.

**Comment by ansis** [comment]
Looks like these are all done, closing.
