### ISSUE TITLE
decide what to do about Hash and Fullscreen

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#293]
Do we bundle these or not?
If so, what do we do about fullscreen's CSS and PNG assets?
If not, what's our story for how people should use them?

**Comment by tmcw** [comment]
Hmm. Maybe keep them out of this repo entirely? I worry a bit about having like a `mapbox.js` that's just a collection of things rather than does more to control how they're namespaced/introduced etc - since even if we have L.Hash roll separately, we'll probably want it in the bundle, right?

**Comment by jfirebaugh** [comment]
If we're going the L.mapbox approach I think it definitely makes more sense just to let them live as Leaflet plugins. We can curate and host a plugin list, but bundling some semi-arbitrary set seems odd.

**Comment by jfirebaugh** [comment]
Now we don't do anything with L.hash and L.fullscreen except include them in the bundle: https://github.com/mapbox/mapbox.js/blob/6e752b8325de6767d71dea879a0a32f7a50c8a0f/index.js#L16-17

Any objections to removing them? The toggling-ui example is the only one to use them, and I'll update it to use direct `<script>` tag.

**Comment by tmcw** [comment]
+1 removing
