### ISSUE TITLE
Disparity between marker geometry lat/lon and setView lat/lon

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox.js#305]
Marker expects:

`[-74.00, 40]`

but in setView land:

`[40, -74.00]`

**Comment by tmcw** [comment]
Leaflet is lat, lon and GeoJSON is lon, lat. This is not exactly a bug, this is that Leaflet copied the Google Maps API too much. See https://github.com/Leaflet/Leaflet/issues/1455

**Comment by heyitsgarrett** [comment]
Well ugh. _(closing as duplicate as it's tracked there)_
