### ISSUE TITLE
attribution.basic_terms

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#307]
Many maps have an attribution like

```
<a href="http://mapbox.com/about/maps">Terms &amp; Feedback</a>
```

We should make it easier to add this as your map's attribution.

**Comment by jfirebaugh** [comment]
Doesn't this usually just come from the TileJSON?

**Comment by tmcw** [comment]
Yes, so like:

``` js
map.addLayer(mapbox.tileLayer('foo'));
```

unless we can automatically have the attribution update when the layer is loaded... but maybe we can?

**Comment by tmcw** [comment]
Yeah, the default attribution code has a bug somewhere.
