### ISSUE TITLE
Write 'including' docs

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#31]
We should have one or two _full html_ examples of how to include mapbox.js like [google maps's getting started](https://developers.google.com/maps/documentation/javascript/tutorial) guide - that frame what to do with the script and link tags on the homepage.

**Comment by tristen** [comment]
I've added a, creating your first map example here: http://mapbox.com/developers/mapbox.js also as discussed in chat referenced eloquent js in a prereq section.

**Comment by tmcw** [comment]
Counting this as done.
