### ISSUE TITLE
pretty transitions for tooltips

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#313]
So this is something we had with mapbox.js v0 and it requires detecting transitions and listening for their end events - it's less than fantastic. maybe there's a better way to do it now.

**Comment by heyitsgarrett** [comment]
What do you mean by pretty transitions? I noticed that leaflet fades in tooltips by default.

**Comment by tmcw** [comment]
Yeah, so this is for fixed tooltips that the gridControl adds - v0 will fade them out with a css transition, but we don't do that here yet. The fade is somewhat functional because it reduced tooltip flicker when crossing from one tooltip to another.

**Comment by heyitsgarrett** [comment]
Remaining work on this being tracked in #324
