### ISSUE TITLE
map is limited to zoom 18

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox.js#317]
Maps shouldn't be limited to 18 by default.

**Comment by ansis** [comment]
The same cause as #308 

Leaflet assumes that most layer options won't change after being loaded. Is it worth trying to get this changed in Leaflet, or should mapbox.map only add the layers after they are ready, as Leaflet expects? Is there any point to adding a layer before its loaded?

**Comment by jfirebaugh** [comment]
The reason we add layers before they are loaded is that leaflet has limited ability to reorder layers, and added layers should have ordering based on when they were added, not when their loads happened to complete. Though maybe we can do something with `TileLayer#setZIndex()`.

**Comment by ansis** [comment]
Fixed by #331
