### ISSUE TITLE
need to sanitize or disallow HTML in tooltips

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#323]
In 0b890830cc629e671dbb3812179b71390d47268c we started putting raw properties from GeoJSON into HTML. Need to fix that, following what v0 does.

If sanitizing, follow how LegendControl does it, with a `sanitizer` property.

**Comment by heyitsgarrett** [comment]
Good call, see above commit. I like having HTML in there, especially as we allow it to be input on the tiles.mapbox.com side.

**Comment by heyitsgarrett** [comment]
Fixed in f2e5670d7d3903cc96c34c27afc1fdf4cba09dcd
