### ISSUE TITLE
gridControl flickers

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#324]
v0 http://mapbox.com/mapbox.js/example/interactive-layer/ -> no flicker
v1 grid-control.html example -> lots of flicker

**Comment by jfirebaugh** [comment]
Now only flickers slightly, and only with `follow: true`.

**Comment by ansis** [comment]
last flickering fixed in 5a269af25f2c8a96fdde132ad8769a291ebaedd9
