### ISSUE TITLE
Bug? Have to set imagepath manually

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox.js#339]
Had to set image path to avoid [this error](https://github.com/Leaflet/Leaflet/issues/766#issuecomment-7741039).

```
L.Icon.Default.imagePath = 'http://api.tiles.mapbox.com/mapbox.js/v1.0.0beta0.0/images';
```

After this fix, standard Leaflet marker images show up.

**Comment by tmcw** [comment]
Another build step we go

**Comment by mourner** [comment]
@tmcw you're so sweet. :) Any tips on avoiding the script autodetect hack? I'd love to get rid of it.

**Comment by tmcw** [comment]
@mourner heh, my anger is towards OL2 8 years ago.

So, options:
- Use sprites instead of img elements, and CSS can relatively reference them
- Use data-urls in CSS to remove the requirement of images entirely.

**Comment by mourner** [comment]
- Sprites can't be used for markers becase of printing issues (most browsers don't print CSS backgrounds)
- During initial Leaflet development, IE6-7 still needed to be supported, and it can't use data uris — so maybe I'll switch to them after I drop IE6-7 support

**Comment by tmcw** [comment]
Okay, this is set for now, let's just push on a better fix once IE6-7 support is dropped.

**Comment by sebastialonso** [comment]
The URL doesn't work anymore. How could I set the path locally? I'm importing leaflet from my project's node_modules folder, but I get a 404 in the developer console.

**Comment by ericmconnelly** [comment]
anyone?

**Comment by thbar** [comment]
@sebastialonso did you find how to fix this for local work?

**Comment by sebastialonso** [comment]
Yes, I'm currently using a custom icon, following the docs. In my case it
was required by the client, but it's a solution nonetheless.
On 11 May 2016 08:33, "Thibaut Barrère" notifications@github.com wrote:

@sebastialonso https://github.com/sebastialonso did you find how to fix
this for local work?
