### ISSUE TITLE
RequireJS loading broken or something

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#345]
Because script tags are just too simple

**Comment by yoannisj** [comment]
I'm also experiencing issues with shim configuration of mapbox.js : 

``` javascript
shim : {
    'js/libs/mapbox' : {
        exports: 'L'
    }
}
```

All I get when requiring 'js/libs/mapbox' in one of my modules is an empty JSON and a TypeError :
_TypeError: n.parse is not a function **mapbox.js (line5)**._ (sorry for the line number, I could not find an uncompressed version of mabox.js)

Hope this can help fixing this issue

**Comment by ansis** [comment]
When JSON3 detects `define` it breaks its support for `exports`. To push a fix out quickly I added an unfortunate hack in https://github.com/mapbox/mapbox.js/commit/24dd5ffa9f227f24e6d108d195da636647a22c7a I'm going to try to get a fix in upstream.

**Comment by ansis** [comment]
Opened an issue upstream at https://github.com/bestiejs/json3/pull/33

**Comment by zzolo** [comment]
Hey, I am getting the same behavior as @yoannisj described, even on the current version (1.4.2).  But it looks like this is fixed.

**Comment by Patryk1098** [comment]
I'm also getting this error; request.js is trying to call JSON3.parse() on a geocoder.query() response. Using the latest MapboxJS (manual build -had to fix something with the geocoder.query call manually), latest require.js.

**Comment by Patryk1098** [comment]
~~FYI @ansis -I tried applying your patch 24dd5ff but haven't had any success. I'm fairly certain I'm doing something (simple) wrong.~~

Got it. That should tide me over. Thanks!

**Comment by ansis** [comment]
If you use the latest build without your custom fix, do you still hit a requirejs error?

**Comment by Patryk1098** [comment]
Just downloaded the latest .zip, ran a build, still got the error:
request.js:18 "Uncaught TypeError: undefined is not a function"
