### ISSUE TITLE
Custom marker example broken in Firefox

### ISSUE THREAD

**Issue by eddietejeda** [mapbox/mapbox.js#347]
Using Firefox 20, going to the custom marker example:

http://mapbox.com/mapbox.js/example/v1.0.0/custom-marker-tooltip/

The first time you click a marker you get "Undefined" the second time you click the marker you get the correct contents. Screenshots attached.

Doesn't appear to be a problem in Chrome.

![Screen Shot 2013-04-19 at 10 23 15 PM](https://f.cloud.github.com/assets/669988/404786/13acc620-a97b-11e2-9e18-98582380dd61.png)
![Screen Shot 2013-04-19 at 10 23 28 PM](https://f.cloud.github.com/assets/669988/404787/13d7df40-a97b-11e2-8c2a-d66a686f7aa3.png)

**Comment by heyitsgarrett** [comment]
Great catch, thanks @eddietejeda. Firefox wasn't quite ready with the tooltip content on click, so I changed the example to assign custom tooltips once the geoJson was ready instead.

**Comment by eddietejeda** [comment]
Weird. That didn't seem to fix the issue. Clicking on the marker in Firefox still gives "undefined"

**Comment by heyitsgarrett** [comment]
Had the fix pushed to the wrong branch - operator error. The example is now updated with the new code. Thanks again.
