### ISSUE TITLE
map.setView to take in geoJSON

### ISSUE THREAD

**Issue by jlord** [mapbox/mapbox.js#348]
So you don't have to do this:

map.setView(geoJSON[0].geometry.coordinates.reverse(), 8)

**Comment by tmcw** [comment]
Cool, this will be upstream in Leaflet - I think there's a relevant ticket for the GeoJSON layer type exposing an extent property but will look around.

**Comment by mourner** [comment]
map.fitBounds(geojson.getBounds());

**Comment by tmcw** [comment]
@mourner cool, so that isn't documented via GeoJSON, though it is for the primitives L.GeoJSON contains and for FeatureGroup. Should inherited methods be documented everywhere?

**Comment by mourner** [comment]
@tmcw I wouldn't document inherited methods in children because this will lead to lots of duplication and hard-to-maintain docs.

BTW, just commited a shorthand to master — now you can just do `map.fitBounds(geojson)`.

**Comment by jlord** [comment]
Yay, nice!

**Comment by ansis** [comment]
Awesome, closing

**Comment by avances123** [comment]
Is it really done?

```
var map = L.map('map').fitBounds({ "type": "Point", "coordinates": [ -3.7176997, 40.4216234 ] })

```

Uncaught TypeError: Cannot read property 'lat' of undefined

**Comment by jfirebaugh** [comment]
@avances123 You can pass an instance of `L.LatLngBounds` or of `L.GeoJSON`, but not raw GeoJSON.
