### ISSUE TITLE
Feature request: custom build

### ISSUE THREAD

**Issue by yoannisj** [mapbox/mapbox.js#350]
A great feature from Leaflet is the ability to build a custom version of it so we can leverage only the minimal code needed to our users : 
http://leafletjs.com/download.html#building-a-custom-version-of-leaflet

Since mapbox comes with the whole Leaflet library built-in, we lose that possibility.
Releasing mapbox.js as an independent Leaflet plugin and providing a good documentation for its dependencies would fix this.

A public uncompressed version of mapbox.js would also be usefull.

**Comment by tmcw** [comment]
> A public uncompressed version of mapbox.js would also be usefull.

http://api.tiles.mapbox.com/mapbox.js/v1.0.0/mapbox.uncompressed.js

**Comment by tmcw** [comment]
We should work in this direction, but currently have a bit of a blocker - mapbox.js includes and requires an unreleased, very new version of Leaflet, so it will not mix with master leaflet versions.

**Comment by jfirebaugh** [comment]
This is [available in v1.1.0](http://www.mapbox.com/mapbox.js/api/v1.1.0/#Standalone MapBox.js).
