### ISSUE TITLE
add geojson example

### ISSUE THREAD

**Issue by hrwgc** [mapbox/mapbox.js#353]
@ansis - With the leaflet changes on the mapbox.js documentation, I noticed we do not have an example showing GeoJSON loading through the mapbox.js library. 

Could you add an example showing a non-MapBox marker layer GeoJSON file added on top of a MapBox map? 

How significantly would the example need to be altered if the GeoJSON were to contain polygon or line geometry rather than points?

cc @tmcw

**Comment by ansis** [comment]
added a geojson example with a point, line, area and popups showing properties 2ca8f9cd0d0009197a213f88c1ee982e9afc4f06
http://bl.ocks.org/ansis/392ad4f4436ff0831e89

Is this fine?

**Comment by hrwgc** [comment]
Awesome - exactly. Thanks @ansis.
