### ISSUE TITLE
markercluster

### ISSUE THREAD

**Issue by Integral** [mapbox/mapbox.js#354]
According to you blog post related to 1.0 API:
"The Leaflet marker cluster plugin is just one example of the many great Leaflet plugins now compatible with MapBox.js (click to see interactive version)."
So, this example in your blog post taken from plugin page. In real life markercluster tried to find marker icons in this urls:
http://api.tiles.mapbox.com/mapbox.js/1.0.0/images/marker-icon.png
http://api.tiles.mapbox.com/mapbox.js/1.0.0/images/marker-shadow.png
And of course can't do it.

**Comment by tmcw** [comment]
See #349 - this will be fixed in the next release.
