### ISSUE TITLE
SCRIPT5: Access is denied.

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox.js#355]
> In IE (7/8/9) the map does not load, and i get a 'script5 access is denied' error. This also happens when viewing the example http://mapbox.com/mapbox.js/example/v1.0.0/ using IE.

**Comment by ansis** [comment]
Current v1 branch works fine. Could try to find out what made the difference, but.. eh... its ie

**Comment by tmcw** [comment]
@ansis Can you run out a v1.0.1 release with IE tested + RequireJS fix + #349 ?

**Comment by ansis** [comment]
v1.0.1 deployed with both fixes.
