### ISSUE TITLE
deprecating and uprecating

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#359]
With v1 launched, it's time to re-sort!
### deprecate
- markers.js
- clustr
- wax
### uprecate
- leaflet.fullscreen
- leaflet-pip and/or leaflet-knn?

**Comment by tmcw** [comment]
Necessary things have been deprecatedflagged

**Comment by wboykinm** [comment]
Is this "deprecated" like "No Bill, stop asking for help with your [old-ass gmaps/wax projects](http://dev.geosprocket.com/hon/)" or "deprecated" like "the entire codebase is in mapbox.js now so we can stop calling it 'Wax'"?

**Comment by tmcw** [comment]
We'll continue to support old code, but don't recommend anyone start new projects with deprecated libraries - OpenLayers adopted UTFGrid so integration is unnecessary, and integrating against Google has become annoying enough that we'd rather just not do it in official projects.

**Comment by wboykinm** [comment]
Word. No plans to go back to Wax-on-Google after the census dotmap kerfuffle. Thanks!
