### ISSUE TITLE
Polyline does not wrap

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox.js#360]
It is not possible to draw a polyline crossing the International Date Line.

In this example, two polylines should meet at the International Date Line to link Tokyo and Los Angeles across the Pacific Ocean. Instead, the polylines do not wrap and the link is broken. 

![la-tokyo-polyline](https://f.cloud.github.com/assets/934388/427541/ba0c12bc-ade7-11e2-8226-bbe5adebab63.png)

**Comment by tmcw** [comment]
Upstream in Leaflet and there are workarounds:
- https://github.com/Leaflet/Leaflet/issues/82

**Comment by tmcw** [comment]
Possible in example: http://mapbox.com/mapbox.js/example/v1.0.0/cross-date-line/

world wrapping captured in #357

**Comment by ghost** [comment]
Thanks Tom. We would like to use valid lat/lon coordinates, and for the vector elements to repeat as you pan the map from one world view to another, or when more than one world view is visible at low zoom levels. In the attached image for example, the Pacific Ocean is rendered twice, while the line crossing the Pacific is rendered once.

![date-line-issue](https://f.cloud.github.com/assets/934388/431077/84bb3bfe-ae7f-11e2-9dea-8be32297094a.png)

This map is an example of the correct behavior, using Google Maps: http://submarinecablemap.com/

Vector Google Map elements behave the same way.

We would certainly prefer to use an open source mapping api in place of Google Maps, if it behaved similarly.

**Comment by tmcw** [comment]
Hi Lairson, there are two different issues here:
- Polylines and LineStrings crossing the dateline. There is no standard solution for this, here or in google maps, etc. The example you point to is using raster features, not Google Map's vectors. You can split lines if you wish to emulate the same kind of behavior, but it's hacks all around.
- World wrap & vector repeat. This is upstream in [Leaflet](https://github.com/leaflet/leaflet) and would be better filed there.

**Comment by ghost** [comment]
Thanks, yes vector repeat is the more pertinent issue. Our data is clipped at the IDL so that it will repeat properly without lat/lon hacks.

The example posted above uses rasters, but like I said Google Map vectors behave the same way. Here is a screenshot of the same data using vectors.

![google-vector-polylines](https://f.cloud.github.com/assets/934388/431235/5af92cbe-ae83-11e2-8001-d8588fe1b3a6.png)

**Comment by tmcw** [comment]
Then please file this ticket on the [Leaflet tracker](https://github.com/leaflet/leaflet) rather than this one.
