### ISSUE TITLE
Include viewport scaling in examples

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox.js#365]
Is there a reason we do not include viewport scaling for the mapbox.js examples?

``` html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```

I know these are _just_ examples but I think for quick maps people are creating and sharing on Twitter, it is important to have in there.

**Comment by tmcw** [comment]
Y, we should do this. It's a bit of an assumption, but probably a safe one. @rsudekum additionally it would make sense to write up a 'using mapbox.js on mobile doc'. Would you be interested in writing that? Maybe like
- Use retina (and how to do that - detectRetina, retinaVersion)
- Do this ^ with your viewpoint
- Avoid full-screen maps that kill panning in pages

**Comment by bsudekum** [comment]
Sure thing, where do you think this will live? Maybe add tips section to the bottom of http://mapbox.com/mapbox.js/api/v1.0.1/ ?

**Comment by tmcw** [comment]
Y, definitely a halfway step in site organization (we should have multiple pages of mapbox.js docs, etc), but adding this near the top of API.md where we're keeping some 'basic tips' would be great.

**Comment by bsudekum** [comment]
@tmcw [took a stab](https://github.com/mapbox/mapbox.js/commit/5622feed4dc81450df8e5668d0c7f98bd0174d67) at this evening. Let me know if this is mergeable.

**Comment by jfirebaugh** [comment]
@rsudekum The API docs are generated from [API.md](https://github.com/mapbox/mapbox.js/blob/v1/API.md), so you'll want to make those changes there. Looks good otherwise.

**Comment by bsudekum** [comment]
Ah okay, I was wondering why the formatting looked off. I'll make this change tonight.

**Comment by gabrielflorit** [comment]
On Android, Chrome, adding viewport breaks the map when attempting a pinch zoom. Example: http://bl.ocks.org/gabrielflorit/raw/5888240/ (uses Mapbox.js 1.1.0).

**Comment by gabrielflorit** [comment]
Uh, wrong link, that one works fine. The Mapbox embed map is the buggy one: http://a.tiles.mapbox.com/v3/gabriel-florit.map-ydjizrs7.html#11.00/42.3411/-71.0584.

**Comment by tmcw** [comment]
@gabrielflorit this ticket is about v1.1.0, which is what the mapbox embeds will use once a pull req is merged for tiles.mb
