### ISSUE TITLE
versioning API/example URLs

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#366]
Our URL structure is confusing and inconsistent:

http://mapbox.com/mapbox.js/api/ redirects to http://mapbox.com/mapbox.js/api/v1.0.1/

but http://mapbox.com/mapbox.js/api/v1.0.1/ says "v1.0.0" and links to http://mapbox.com/mapbox.js/example/v1.0.0/

but http://mapbox.com/mapbox.js/example/v1.0.0/ says "v1.0.1" and links to http://mapbox.com/mapbox.js/examples/

but http://mapbox.com/mapbox.js/examples/ is v0.6.7

Creating separate versions for API docs but not for examples is going to lead to confusion, and I question the value of creating separate API docs for every point release. We shouldn't be removing any documented functionality. Adding functionality should only happen in minor versions and can be accompanied with "added in v1.x.0" in the documentation.

I suggest:
- api/v1/
- examples/v1/

These would be the canonical URLs, and we'd redirect existing v1.0.x stuff to v1. I believe we would have to do this individually for each v1.0.0 example, which sucks, but since we've published those URLs we need to keep them alive.

Also, we should set up redirects from unversioned example URLs (which currently serve v0.6.7 examples) to the equivalent v1 examples. Where there isn't an equivalent yet, it should redirect to v0/<example>.

Existing api/v0.6.x/ pages would be left alone.

**Comment by incanus** [comment]
On the iOS side I've been keeping version out of the URLs and just continually updating http://mapbox.com/mapbox-ios-sdk/api/ in place with a new version in the title. _Examples_ and _Guide_ don't mention version number. 

Just for parity reference.

**Comment by jfirebaugh** [comment]
I fixed the most confusing discrepancies in afb1c29128b6ed74e00eb9ed3710d061b8d76df0 and 044a1db74545dd1f499be5e7d3bad2e82f66b15f, but I still think we should consider having just `v1` in the URL.

**Comment by tmcw** [comment]
> but http://mapbox.com/mapbox.js/examples/ is v0.6.7

This is because we did not want to break existing links, and could not just redirect all examples - since not all are available in v1.

> Creating separate versions for API docs but not for examples is going to lead to confusion

It never led to confusion in any known instance for the long time we had this same setup with v0.6.x.

**Comment by jfirebaugh** [comment]
> This is because we did not want to break existing links, and could not just redirect all examples - since not all are available in v1.

See #368 for potential solution.

> It never led to confusion in any known instance for the long time we had this same setup with v0.6.x.

Ok, maybe we're fine then with the above fixes.
