### ISSUE TITLE
Reset markers via setGeoJSON([]) doesn't work as expected

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox.js#369]
After setting markers via setGeoJSON:

``` js
map.markerLayer.setGeoJSON({
    type: 'FeatureCollection',
    features: features
});
```

resetting them by passing an empty array doesn't actually clear the markers:

``` js
map.markerLayer.setGeoJSON([]); // Markers persist
```

**Comment by sxalexander** [comment]
I understand that this was unintentional behavior, but what is the appropriate way to set multiple GeoJSON's FeatureGroups on a map without this method?

**Comment by jfirebaugh** [comment]
You have several options:
- Merge the GeoJSON features yourself before calling `setGeoJSON`
- Use multiple L.mapbox.markerLayers
- Use L.GeoJSON, which has an additive `addData` method
