### ISSUE TITLE
Leaflet.Draw compatibility?

### ISSUE THREAD

**Issue by kirkedev** [mapbox/mapbox.js#372]
Using Leaflet.Draw with mapbox throws an error, because it calls `map#addLayer` [here](https://github.com/Leaflet/Leaflet.draw/blob/master/src/draw/handler/Draw.Polyline.js#L49) with an instance of [LayerGroup](http://leafletjs.com/reference.html#layergroup) (not extended with events) and mapbox's `map#addLayer` method tries to attach a "ready" listener to it. 

The easiest fix for me was to change Leaflet.Draw to use a FeatureGroup instead of a LayerGroup. I've opened a [pull request](https://github.com/Leaflet/Leaflet.draw/pull/135) over there, but I wouldn't be surprised if it was rejected. I'm not sure that mapbox should assume that all layers added are at least FeatureGroups.

**Comment by jacobtoye** [comment]
I would think that this should be fixed in mapbox.js as this would break for anyone who adds a `L.LayerGroup` to the map. Could you check for event support on the layer and only attach the listener if support?
