### ISSUE TITLE
Share links extension

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#376]
For sharing on twitter/facebook/etc

**Comment by jfirebaugh** [comment]
Initial commit: https://github.com/mapbox/mapbox.js/tree/share

@heyitsgarrett, ready for some CSS magic.

It's currently set up to be included in the build by default at L.mapbox.shareControl. Seem ok?

**Comment by heyitsgarrett** [comment]
Terrific, will take a look. Seems okay on the build front.
