### ISSUE TITLE
movetip example behaves erratically after clicking

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#382]
http://mapbox.com/mapbox.js/example/v1.0.0/movetip/

After clicking, it seems very unpredictable where and when the tooltip will show up again.

**Comment by jfirebaugh** [comment]
This regressed in 1.0.2 due to a Leaflet change. Something related to the `closePopupOnClick` option, will bisect.

**Comment by jfirebaugh** [comment]
Bisect failed, but it got close enough to Leaflet/Leaflet@7cb7993571a4078161bc4168f29232f936cfc3ca that I'm pretty sure that was the cause.

@mourner, seems like `closeOnClick` should be a per-Popup option, do you agree?

**Comment by mourner** [comment]
Maybe, but I can't come up with many use cases for this. I think we should keep the option in both Map and Popup — setting it in the map is more convenient for a global switch that passing options to each bindPopup method just because of this.
