### ISSUE TITLE
WMS layer loads only on first zoom

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox.js#388]
I honestly have no idea why I'm spending time on WMS compatibility :v: - but I noticed that in both the [v1 example](http://mapbox.com/mapbox.js/example/v1.0.0/wms/) and in [this implementation](http://bl.ocks.org/wboykinm/5578714) the called WMS layers briefly flash on page load but are then invisible until the user's first zoom in or out.

Is this one to run down here or should I look upstream?

**Comment by jfirebaugh** [comment]
This is Leaflet/Leaflet#1683.
