### ISSUE TITLE
If ui is called after adding layers, zoombox is under them

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#39]
This is, I think, an issue upstream in the control styles w/ wax.

**Comment by ansis** [comment]
Possibly to do with UI controls being added into a separate `controls` div. Is this necessary?

**Comment by tristen** [comment]
The controls div is necessary so the map controls can have a single box-shadow underneath them. It also simplifies the positioning code in css as a z-index only needs to be applied to the parent (control) element.

**Comment by ansis** [comment]
Unable to reproduces this. Was this fixed in Wax?

**Comment by ansis** [comment]
Works, closing.
