### ISSUE TITLE
Tooltips outside of maps example

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox.js#393]

**Comment by jfirebaugh** [comment]
Is this http://www.mapbox.com/mapbox.js/example/v1.0.0/interactivity-outside-map-layer/, or something else?

**Comment by tmcw** [comment]
@jfirebaugh it's like that, but with markers: http://www.mapbox.com/mapbox.js/example/v0.6.7/external-marker-tooltip/
