### ISSUE TITLE
Search icon for geolocation control rather than 'Locate'

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#397]
One more icon resource > a string that potentially needs translations

**Comment by tmcw** [comment]
Done

**Comment by moasth** [comment]
I use icon-gpsoff-gps and icon-gpson from [WebHostingHub Glyphs](http://www.webhostinghub.com/glyphs/).
Oups, too late... but if it can help...

**Comment by heyitsgarrett** [comment]
Thanks, @moasth - we rolled our own to match Maki/general MapBox look 'n feel.
