### ISSUE TITLE
zoom lens gets stuck with wrong tiles

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#399]
Seen on http://www.mapbox.com/blog/before-after-moore-tornado/ after zooming in.

![image](https://f.cloud.github.com/assets/98601/561672/26e6554c-c494-11e2-86b6-f5e1f934adf7.png)

**Comment by jfirebaugh** [comment]
Haven't been able to reproduce this with http://www.mapbox.com/mapbox.js/example/v1.0.0/zoom-lens/, might be specific to the Tornado map.

**Comment by tmcw** [comment]
Stale
