### ISSUE TITLE
Eat map-site

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#4]
This code should make a lot of the things in map-site less necessary.

**Comment by jueyang** [comment]
@tmcw 

Some thoughts:

For those who are not front-end developers, one current advantage of map-site template is that the user is dealing with less abstracted (and thus less advanced) tasks. I wonder if that can be a way to have that kind of "kit" with mapbox.js - basically having things set up in DOM and the users can tweak from there if they don't want to get involved with the code.

Having worked with the template, I do find it inflexible. These are some the resulting work-arounds:

1) [optional toggling](https://github.com/developmentseed/amnesty/commit/1dc3d010f177bae4b329e51865bcdd73d24a92ed) 
2) [optional hash](https://github.com/developmentseed/amnesty/commit/0f3e6708b4db5b0ac9a74858478e2093e61cda4b)
3) [enabling both tooltip and movetip](https://github.com/developmentseed/amnesty/commit/5c1f2c99661924849b9fe4841587b9a1b80ac6c9)

**Comment by ansis** [comment]
Pull requests have been opened on all map-sites. Functionally, they should be exactly the same as the old templates (share control just added), so review whenever its convenient.

**Comment by tmcw** [comment]
Done
