### ISSUE TITLE
Test failures for mapbox.interaction

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#40]
Is this code correct: https://github.com/mapbox/mapbox.js/blob/master/src/map.js#L17

Tests fail because `mapbox.interaction` doesn't exist. /cc @aibram

**Comment by ansis** [comment]
Yeah, it was just `build-dev.sh` being out of date. Fixed in 7e6a4e73227e1bbdba9f8853c88ae1e2b6a2be20
