### ISSUE TITLE
Simple marker styles only work when set directly on a feature object

### ISSUE THREAD

**Issue by caged** [mapbox/mapbox.js#400]
According to the ["Styling markers" docs](http://www.mapbox.com/developers/simplestyle), simple styles should be set on the `feature.properties`, but this doesn't seem to work in any version I've tested (1.0.2 and 1.0.3).  However, if you set the style properties directly on the `feature` object, everything works as expected.  The latter seems to be what the [source](https://github.com/mapbox/mapbox.js/blob/v1/src/marker.js#L17-L19) expects.

Here is a JSFiddle reproducing the issue.  Note where the marker styles are set in each feature:  http://jsfiddle.net/vxB4U/1/

/cc @benbalter @skalnik

**Comment by skalnik** [comment]
For what it's worth, this morning I made a map with a few markers (http://a.tiles.mapbox.com/v3/skalnik.map-vuuen0rh/page.html) and grabbed the markers down via http://a.tiles.mapbox.com/v3/skalnik.map-vuuen0rh/markers.geojson and they were in `feature.properties`.

**Comment by caged** [comment]
Just had a moment of clarity :)  I believe `fp` in the source means feature properties.  Passing in `feature.properties` works great.  The [documentation for mapbox.icon](http://www.mapbox.com/mapbox.js/api/v1.0.2/#L.mapbox.marker.icon) implied the entire `feature` object should be passed.

**Comment by tmcw** [comment]
You're right - those docs are too unclear. Fixed in 17e29b2390066211095401d7858ddab0b7e96f49
