### ISSUE TITLE
Add to Bower

### ISSUE THREAD

**Issue by tysonnero** [mapbox/mapbox.js#404]
It would be great to get mapbox.js into the Bower registry :-)

**Comment by tmcw** [comment]
We've discussed this a bit, and are open to the possibility but it's not as easy as adding a `bower.json` - right now mapbox.js does not include dists in its repo and is built with browserify. This will have to change if we support bower, and our tagging strategy will have to get more sophisticated as well.

**Comment by tmcw** [comment]
Bower is more trouble than it's worth. Closing.

**Comment by adamnbowen** [comment]
For anyone interested in cheating this into your bower.json file without requiring browserify, you can run this in the command line:

```
$ bower install mapbox.js=https://api.tiles.mapbox.com/mapbox.js/v1.4.2/mapbox.js --save
```

and

```
$ bower install mapbox.css=https://api.tiles.mapbox.com/mapbox.js/v1.4.2/mapbox.css --save
```

That will let you incorporate the compiled files into your usual build process.

That doesn't get you the required images, however, so I'll have to investigate that a bit.

**Comment by amir20** [comment]
I think this ticket should be reopened because I don't think it is more trouble that one thinks. You could do what angularjs does which have a distribution just for the compiled version. Seems like you can automate it for every release.

**Comment by tmcw** [comment]
I'm open to a PR that implements & automates this process, or a third-party adapter.

**Comment by Anahkiasen** [comment]
You could just add the ZIP of each release to the Github releases in the meantime, that would make them easier to find.

**Comment by nerik** [comment]
Here's a quick and dirty grunt task to make a local copy of the mapbox assets (including images)
https://gist.github.com/nerik/64e4798d2bf1c19800f6
(also does other things related to our assets pipeline)

**Comment by sanketsahu** [comment]
Bower support is much needed.

**Comment by Nolski** [comment]
+1 for bower support. I understand that it may take time due to the way things are set up but closing a ticket because it takes work doesn't seem like a valid excuse to me.

**Comment by tmcw** [comment]
`¯\_(ツ)_/¯` I'll reopen the ticket, but as before, open to PRs here - they get stuff done faster than +1ing
