### ISSUE TITLE
people don't understand ready

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#405]
Lots of people are [thinking that ready will fire](http://support.mapbox.com/discussions/general-questions/16269-problem-using-marker-popupcontent-in-internet-explorer) when they use `setGeoJSON`. How do we resolve this?
- Make `ready` fire when markers are set in any fashion
- Add another event
- Document this

**Comment by jfirebaugh** [comment]
We should switch all the marker examples to use `layeradd` rather than `ready`, I think that will fix most cases of this.

**Comment by jfirebaugh** [comment]
Changed in fc1ae05fe7d6106d2a74218e7a1965d7fe89ec6a and a7d89b14a3282c8dab02cc395789e8d880f2b659.
