### ISSUE TITLE
Not adding animate to MM functions

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox.js#41]
ModestMaps centering and zooming functions were extended with another argument, _animate_. Would it be a good idea to simplify these cases in Easey instead of extending the MM functions?

For example:
`map.centerzoom(location, level, true)`
becomes `map.ease.center(location).zoom(level).run()`
or perhaps just `map.ease.centerzoom(location, zoom)`?

If we override as little of MM as possible then mapbox.js stays as simple as possible.

If we avoid extending the MM functions like this we could say here's a regular MM map, with interaction, ui, and easey attached for convenience and with .auto() and .refresh() functions, instead of having to also document a whole bunch of functions.

Do we want to merge the projects together into one api, or just glue various individual components together?

@tmcw what do you think?

**Comment by tmcw** [comment]
Let's think about enhancements like this after we have all bugs from the internal release fixed; I'd rather not tweak until we have actual feedback

**Comment by ansis** [comment]
Sounds good, definitely a good idea to wait for feedback. Closing
