### ISSUE TITLE
example markerLayer.setGeoJSON(geojson: object) does not work

### ISSUE THREAD

**Issue by ajjoshi** [mapbox/mapbox.js#413]
I copied what was on the example for setGeoJSON but it did not work. Nothing shows up

var map = L.mapbox.map('map', 'ajoshi.map-uvje52mb');
var markerLayer = L.mapbox.markerLayer(geojson).addTo(map);
// a simple GeoJSON featureset with a single point
// with no properties
markerLayer.setGeoJSON({
    type: "FeatureCollection",
    features: [{
        type: "Feature",
        geometry: {
            type: "Point",
            coordinates: [102.0, 0.5]
        },
        properties: { }
    }]
});

**Comment by tmcw** [comment]
Hi,

This is a bug tracker rather than a support channel - please post in [http://support.mapbox.com/](http://support.mapbox.com/).
