### ISSUE TITLE
Handling of UTF-Grid responses from Mapbox

### ISSUE THREAD

**Issue by caseycesari** [mapbox/mapbox.js#417]
I recently updated [this map](http://apps.axisphilly.org/avi-map/) with new tiles and started using mapbox.js instead of wax. The [tiles](https://tiles.mapbox.com/axisphilly/edit/avi-diff-v4) are hosted on MapBox. There UTF-Grid responses are coming back in two slightly different forms.

The beginning of some look like...

```
grid({...
```

...which is what `request.js` is expecting. However, a lot of responses start as

```
grid && grid({...
```

which causes a `Unexpected character &` error. Here's an [example](http://c.tiles.mapbox.com/v3/axisphilly.avi-diff-v4/17/38175/49615.grid.json) URL that returns the `grid && grid` style response. 

To fix this, I modified `request.js` like so:

```
module.exports = function(url, callback) {
    ...
         if (!err && resp) {
             // hardcoded grid response
             if (resp.responseText[0] == 'g' && resp.responseText[4] != ' ') {
                 resp = JSON3.parse(resp.responseText
                     .substring(5, resp.responseText.length - 2));
             // hardcoded grid && grid response
             } else if (resp.responseText[0] == 'g' && resp.responseText[4] == ' ') {
                 resp = JSON3.parse(resp.responseText
                     .substring(13, resp.responseText.length - 2));
             } else {
                 resp = JSON3.parse(resp.responseText);
             }
    ...
 };
```

I didn't submit a pull request because I wasn't sure what the expected behavior is and even if `mapbox.js` should be patched, or if there is something odd with the tiles.

**Comment by tmcw** [comment]
Hey - this is a recent regression on the server side. Looking into it now.

**Comment by jfirebaugh** [comment]
This has been fixed server-side.

**Comment by caseycesari** [comment]
Thanks!
