### ISSUE TITLE
Maki Icons not available

### ISSUE THREAD

**Issue by skalnik** [mapbox/mapbox.js#422]
Perhaps this isn't the best place to put this, so if it's not, just tell me where to redirect this :smile:

I can't get all Maki icons to load using mapbox.js. Specifically when testing the "building" icon, I get a broken image. Checking the console, I see that I get a 400 back from the CDN saying that `Marker "pin-s-building@2x" is invalid.`

**Comment by wboykinm** [comment]
This one is already [sort of flagged](https://github.com/mapbox/maki/issues/72). Not sure who decides when to push them downstream. @ajashton or @yhahn?

**Comment by skalnik** [comment]
:cool: Closing in favor of https://github.com/mapbox/maki/issues/72.

**Comment by benbalter** [comment]
Bump. Any chance of updating the MapBox API with the latest version of Maki?

(or documenting instructions on how to swap out a self-hosted version for the MapBox hosted version?)

**Comment by wyattp11** [comment]
Can we re-open this? Add latest Maki to MapBox JS API... trying to use volcano and mountain but getting invalid response...
