### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox.js#428]
The MapBox API is adding some more solid SSL support soon and MapBox.js should take full advantage. Kicking on that discussion here.

I think this will mostly be an internal change, correct? @tmcw do you want to try to auto detect when a page is SSL and switch into SSL mode? Not sure how safe that is. Or maybe there should be an option like:

```
var map = L.mapbox.map('map', 'examples.map-4l7djmvo', {secure: true});
```

Or both?

**Comment by jfirebaugh** [comment]
:+1: for autodetection.

What's necessary from a technical side? Is it as simple as using an https scheme everywhere?

**Comment by tmcw** [comment]
Grabbing this, gonna kick tires on ssl detection

**Comment by tmcw** [comment]
k, google has it: `('https:' == document.location.protocol ? 'https://ssl' : 'http://www')`

**Comment by tmcw** [comment]
Pull in https://github.com/mapbox/mapbox.js/pull/431
