### ISSUE TITLE
`html_sanitize` no longer available in the global scope

### ISSUE THREAD

**Issue by benbalter** [mapbox/mapbox.js#435]
Followed the example as described in [the geojson example](https://github.com/mapbox/mapbox.js/blob/v1/examples/geojson.html#L46) and it appears that after upgrading to 1.1.0, `html_sanitize` is no longer defined.

Trying to backtrace the change without luck. Was the scope change? It appears to still be included.

**Comment by jfirebaugh** [comment]
It was accidental global scope pollution, removed in 06059e7.

**Comment by benbalter** [comment]
Is it possible to access from the global scope? e.g., `L.mapbox.html_sanitize`?

**Comment by jfirebaugh** [comment]
It's accessible as the default value of a marker layer `sanitizer` option, e.g. `map.markerLayer.options.sanitizer`. We'll make it available as an `L.mapbox` property too at the same time as #385.

**Comment by benbalter** [comment]
Ahh thanks. So to be clear, if as in the geojson example, there's a callback to bind popups, does the content automatically get sanitized before being added to the layer, or would we still need to sanitize it?

**Comment by jfirebaugh** [comment]
Yeah, if you are not using L.mapbox.markerLayer and loading arbitrary external content, you would still need to sanitize it.
