### ISSUE TITLE
SSL docs potentially out of date

### ISSUE THREAD

**Issue by benbalter** [mapbox/mapbox.js#436]
Given #431 merging in 1.1.0, are the [SSL docs](http://www.mapbox.com/developers/ssl-api/) still accurate?

It appears the `HTTPS_URL` [is now branded](https://github.com/mapbox/mapbox.js/pull/431/files#L1R13) and included in the library (so no longer need to specify)?

**Comment by tmcw** [comment]
Yep, we're waiting for another blog post to announce & re-document :)

**Comment by benbalter** [comment]
![tumblr_lxt5tjb9tf1qd8nujo1_500](https://f.cloud.github.com/assets/282759/717138/7a13f104-df45-11e2-942a-222f5f00d879.gif)

:)

**Comment by tmcw** [comment]
SSL docs are now updated :)
