### ISSUE TITLE
Touch events don't work on Chrome Mobile

### ISSUE THREAD

**Issue by gabrielflorit** [mapbox/mapbox.js#441]
When I create a map using mapbox.js, touch events don't work on Chrome Mobile. However, if I use the http://a.tiles.mapbox.com/v3/***.html map, touch events work just fine, on any browser.

**Comment by tmcw** [comment]
Hm, can you post an example and specify which point version of mapbox.js you're using?

**Comment by gabrielflorit** [comment]
Sure thing.

This works: http://a.tiles.mapbox.com/v3/gabriel-florit.map-ydjizrs7.html#11/42.34109999999998/-71.05839999999999

This doesn't: http://bl.ocks.org/gabrielflorit/raw/5888240/ (using latest mapbox.js).

**Comment by gabrielflorit** [comment]
More details:

I'm using Samsung Galaxy SII (Sprint), running Android 4.04 .

This map http://bl.ocks.org/gabrielflorit/raw/5888240/ works fine on:
- the Android 4.04 stock browser
- Dolphin

It doesn't work (by that, I mean touching the dots doesn't invoke the teaser box on top-right) on:
- Chrome
- Firefox

**Comment by gabrielflorit** [comment]
More testing:

The map also doesn't work on neither:
- Safari (iPhone 5)
- Safari (iPhone 4S)
- Chrome (iPhone 4S)

**Comment by tmcw** [comment]
The behavior of v1.1.0 is different from v0.6.7 with touch events + teaser interaction as in your example - there's no teaser -> full fallback. Will think about a proper solution for that...
