### ISSUE TITLE
Marker for restaurant "large" size doesn't use 24px+ Maki icons (or an older version of it?)

### ISSUE THREAD

**Issue by louh** [mapbox/mapbox.js#447]
(not sure if this is the best place to file this, but I encountered this through using mapbox.js)

When I use the "simplestyle" declaration for obtaining this marker: "marker-style: restaurant; marker-size: large" I get http://a.tiles.mapbox.com/v3/marker/pin-l-restaurant+cd0000.png

It resembles the 18px one rather than the 24px icon. The middle-size restaurant icon doesn't look as good scaled up to larger sizes. I've had to roll my own version for my site (http://codeforamerica.github.io/lv-trucks-map/) but thought I'd let someone know.

Thanks.

**Comment by tmcw** [comment]
Hey Lou,

The issue is that Maki has been redesigned and the new version hasn't been deployed to tiles.mapbox.com yet - we're working on a redeploy currently.

**Comment by louh** [comment]
Got it. Thanks. Is there a Maki-icon-generator repo somewhere?

**Comment by jfirebaugh** [comment]
The new maki icons have been deployed to tiles.mapbox.com.
