### ISSUE TITLE
Dojo AMD require in IE

### ISSUE THREAD

**Issue by iH8** [mapbox/mapbox.js#454]
I'm having issues with loading mapbox.js by Dojo AMD require call in IE.  I've tested the same scenario with other AMD loaders (Require/Cujo) and browsers (name them) but only i observe this problem with IE and Dojo. 

```
require([
    '//api.tiles.mapbox.com/mapbox.js/v1.2.0/mapbox.js'
], function() {
    window.hasOwnProperty('L'); // Works
    window.L.hasOwnProperty('mapbox'); // Fails
});
```

My best guess is that the Leaflet object is being sent to the loader before the mapbox plugin is attached. I think that Dojo/IE are faster than other loaders/browsers and trip over this. I've tried  setting a 500ms timeout in the factory function before testing L.mapbox, which does the trick.

Dojo 1.8.4 & 1.9.1, Mapbox 1.1.0 & 1.2.0 in IE 10.0.9200.16635

Testcase at bl.ocks: http://bl.ocks.org/iH8/raw/5995073/

**Comment by tmcw** [comment]
Source of loader.js for reference: https://github.com/dojo/dojo/blob/master/_base/loader.js

will look into this. in the meantime, workaround is not to use dojo's require.

**Comment by tmcw** [comment]
Yeah, looks like dojo's odd searching-for-legacy-module-patterns is finding one and using it incorrectly. Let me know if you can figure out a fix here, but it's not super-high priority - supporting raw-js+browserify+requirejs+'bower' makes everything fight and I'm a bit afraid of cross-system regressions.

**Comment by iH8** [comment]
My first recommendation would be to lay down some tests for these scenarios. I'm totally aware of the complicity and can't think/find a clean fix for now. Poked @dojo, maybe they'll have some input. Otherwise chalk down as irregularity. #fine

**Comment by tmcw** [comment]
Punting on this; the combination of IE + dojo requires its own team of developers.
