### ISSUE TITLE
Double tooltip in youtube example

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox.js#460]
Vie [tender](http://support.mapbox.com/discussions/mapboxjs/62-youtube-embed-sample-double-windows-user-experience-thoughts)

> The youtube sample is great because you can use it to embed any content in an infowindow defined by HTML in the source data. So far I have a few thoughts: 1) for some reason, there are 2 infoWindows popping up when I run the sample locally - and you can even see it in the sample window as well. Have you all noticed this? See the attached PNG. 2) You gotta be pretty quick on the mouse to actually move your cursor from the map feature all the way to the infowindow (depending on the size of the map window, that is!) before the window closes. In a fullscreen example, the infowindow closes if you don't race over to the infowindow...that makes it kinda hard to use! This UX question has got me thinking of whether i should use the 'tooltips outside map' example/concept to do this instead... Any thoughts on all of that?

**Comment by tmcw** [comment]
This is a bug in the example code, not mapbox.js. The L.mapbox.map constructor creates one gridControl and we create another.

**Comment by tmcw** [comment]
Fixed in 4f4447e0c0f8b7acfb2c1b45f41fb4491464f7e9
