### ISSUE TITLE
background-size not supported in IE8

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#462]
The geocoder control uses this property to handle retina-always

may or may not be a bug: @heyitsgarrett make the call

**Comment by tmcw** [comment]
also hits the share dialog, hard

![](http://dl.dropbox.com/u/68059/Screenshots/y1990by4xgg7.png)

**Comment by heyitsgarrett** [comment]
Handsome. Looks like some z-index nonsense going on there too? Will check this out too while I'm inside the machine.

**Comment by tmcw** [comment]
The marker-stack bug in that screenshot has been fixed already in f8fa27f61cbb33f5ea8f7ac06ec63676198ba555

**Comment by tmcw** [comment]
Fixed in #466
