### ISSUE TITLE
Marker arrows not working in IE10

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#463]
![](http://dl.dropbox.com/u/68059/Screenshots/bn384rwzakkm.png)

**Comment by tmcw** [comment]
@heyitsgarrett got any theories here? if this is not shallow, I'm fine with punting

**Comment by heyitsgarrett** [comment]
Ah, it's the border-radius hack we use for arrows. I have one idea which I'll try first thing in the A.M., falling back on a png if that doesn't work. Either way, fixable and should be priority since folks love IE10.

**Comment by tmcw** [comment]
Note this _does_ work outside of frontend and is thus some result of style clashing

**Comment by tmcw** [comment]
@heyitsgarrett this is fixed, right?
