### ISSUE TITLE
Not usable from browserify

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#468]
main points to `index.js`, `index.js` doesn't export anything.

**Comment by joeybaker** [comment]
FWIW, I've gotten it to work with browserify okay. The only catch is that mapbox.js needs to be installed via npm (and not bower).

**Comment by tmcw** [comment]
Actually, yeah - the catch is that `var L = require('mapbox.js')` doesn't work, but that's probably fine. window.L it is. closing.

**Comment by joeybaker** [comment]
Ah, yea. It's kinda non-good to have the package auto-create a global, but that appears to be a leaflet, not a mapbox problem :)
