### ISSUE TITLE
Make tooltips match tiles.mapbox

### ISSUE THREAD

**Issue by dhcole** [mapbox/mapbox.js#47]
![](https://img.skitch.com/20120717-8877j1a87r2jyhadfh2cjpkauh.jpg)

**Comment by dhcole** [comment]
@tristen what do you think about making these consistent too, like the zoom controls? I know @samanpwbb spent some time on the tiles.mapbox tooltip design.

**Comment by tristen** [comment]
Yeah - good call. Added here: https://github.com/mapbox/markers.js/commit/5d3d53831975367a4ca0c0f684668060559eb2df#commitcomment-1592162
