### ISSUE TITLE
HTTP scheme missing in examples

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox.js#478]
The MapBox.js examples such as http://www.mapbox.com/mapbox.js/example/v1.0.0/ no longer have an HTTP scheme associated with them, so the copy-and-pasted code doesn't work out of the box, as I just discovered. 

e.g. 

```
<script src='//api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.js'></script>
<link href='//api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.css' rel='stylesheet' />
```

**Comment by willwhite** [comment]
Hrm what doesn't work about them? These should default to the protocol of
the page that they are embedded on.

On Wednesday, August 7, 2013, Justin R. Miller wrote:

> The MapBox.js examples such as
> http://www.mapbox.com/mapbox.js/example/v1.0.0/ no longer have an HTTP
> scheme associated with them, so the copy-and-pasted code doesn't work out
> of the box, as I just discovered.
> 
> e.g.
> 
> <script src='//api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.js'></script>
> 
> <link href='//api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.css' rel='stylesheet' />
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mapbox/mapbox.js/issues/478
> .

## 

202-250-3633 | will@mapbox.com | @willwhitedc

**Comment by incanus** [comment]
Really, I've never seen that before. 

All I know is I was just sitting with someone, showing them the examples. I copied one out, pasted into an HTML file, opened it in Chrome from the Finder (local, no server) and the page was blank...

Ahhhhh, that makes sense. It was the `file://` protocol. Must not work there.

**Comment by jfirebaugh** [comment]
Those are [protocol-relative URLs](http://www.paulirish.com/2010/the-protocol-relative-url/).

It works fine except if you try to view it via a file:// URL, which is best avoided for other reasons, like CORS not working.

**Comment by incanus** [comment]
![](http://3.bp.blogspot.com/-t4oVWrNA7i0/Tc2KE8mQVNI/AAAAAAAACK0/bIVhL93wUO0/s1600/the_more_you_know2.jpg)

**Comment by tmcw** [comment]
> Ahhhhh, that makes sense. It was the file:// protocol. Must not work there

Nevereveruse the file protocol, it will give you unreproducible bugs. Use SimpleHTTPServer or [serve](https://github.com/visionmedia/serve) or your built-in-OSX-crApache

**Comment by incanus** [comment]
Right, that's great for someone who's not a beginner programmer. Agreed, but it's just a bit of a hurdle when you are staring down "what is JavaScript" at the same time.

**Comment by tmcw** [comment]
Protocol oddities are not a choice we can make - using http here could patch together things for a lil bit, but then you'll run into CORS acting weird and so on. This is why we have [links to Javascript bits in the prerequisites section of our documentation.](http://www.mapbox.com/mapbox.js/api/v1.3.1/)

**Comment by incanus** [comment]
Good call. I'll keep this in mind going forward. One step at a time.
