### ISSUE TITLE
"Uncaught SyntaxError: Unexpected end of input" when loading grid

### ISSUE THREAD

**Issue by annapawlicka** [mapbox/mapbox.js#479]
I have exported MBTiles using TileMill, extracted them to local file system, and I'm now trying to create a leaflet map using mapbox plugin:

var map = L.mapbox.map('map', relationships_tilejson, {gridControl: false});

```
map.gridLayer
        .on('mousemove',function(o) {
            console.log(o.data);
        }).on('mouseout', function(o) {

        });
```

relationships_tilejson looks like this:

```
 var relationships_tilejson = {
    "grids": ["http://localhost:8081/data/relationships_tiles/{z}/{x}/{y}.grid.json"],
    "tiles": ["http://localhost:8081/data/relationships_tiles/{z}/{x}/{y}.png"],
    "attribution": "",
    "description": "",
    "center": [-2.0654,52.8956,6],
    "bounds": [-6.6028,49.689,1.9446,55.943],
    "minzoom": 6,
    "version": "1.0.0",
    "template": "{{#__location__}}{{/__location__}}{{#__teaser__}}<b> Output Area: </b>{{{OA11CD}}} <br />\n<b>Sub: </b>{{{sub}}} <br />\n<b>Average: </b>{{{r-avg}}}{{/__teaser__}}{{#__full__}}{{/__full__}}",
    "maxzoom": 15,
    "name": "oa_relationships_avg"
};
```

This works fine when I use leaflet and wax 6.4.0 (which is now deprecated and therefore I'm trying to move to mapbox.js). However, when I use version 1.3.0 of mapbox.js I get the following error:

```
Uncaught SyntaxError: Unexpected end of input mapbox.js:6
(anonymous function) mapbox.js:6
s
```

I have tried using actual tilejson file instead of having it stored in a var, but I got the same error. Tiles are loaded, but the grids are not. Is there a different tilejson needed to use with mapbox.js? Or maybe something else to make it work locally?

**Comment by annapawlicka** [comment]
I got the map to work by using a different set of grids - instead of using the one created by TileMill, I used one created by create-utfgrids (https://github.com/Ecotrust/create-utfgrids). And now the grids are being loaded ok.

JSON files created by TileMill are wrapped in grid(), while the ones created by create-utfgrids are not. Is there a way to load TileMill's grids from a local host?

**Comment by tmcw** [comment]
This is fixed on the mb-util side by adding a callback parameter as added in the last PR.
