### ISSUE TITLE
Marker Size?

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox.js#480]
So why are markers 35 x 90 pixels in size? As it stands now, you can click ~40px below the marker to trigger a click event. Why not make the image size flush at 35px x 40px? There is probably a legit explanation, just curious. 

![screen shot 2013-08-14 at 10 57 06 am](https://f.cloud.github.com/assets/1058624/962538/bc29b9da-04f1-11e3-8824-bbca4be60098.png)

cc @tmcw

**Comment by tmcw** [comment]
/cc @yhahn 

The reason is that the center of the marker will be the center of the image, regardless of scale.

**Comment by incanus** [comment]
FYI this has been handy on iOS as well, where taps on the transparent parts don't register anyway.

**Comment by mourner** [comment]
@tmcw can't we just adjust `iconAnchor` depending on the scale?

**Comment by tmcw** [comment]
Context from chat:
- we already use iconAnchor for positioning. The reason I posted was historically why not currently why
- Serving a new marker image size by default requires a new rest api version, which is not justified by this
- this is something we should queue up for a future version or for a clever fix. If we used background images, or `clip()`, or something else, we could fix this without changing the rest api.

**Comment by mourner** [comment]
Fiddled a bit with this, clip seems to work fine:

``` css
clip: rect(auto auto 55px auto);
```

**Comment by jfirebaugh** [comment]
Hmm, I couldn't get `clip` to work. @mourner you applied it to the `leaflet-marker-icon` elements? That doesn't seem to affect pointer events.

**Comment by mourner** [comment]
Yes, and it limits pointer events as expected for me in Chrome at least. BTW, I wonder why is there no pointer cursor on markers, this feels super weird.

**Comment by jfirebaugh** [comment]
@mourner Can you PR your change? Something must be different. On [examples like this](https://www.mapbox.com/mapbox.js/example/v1.0.0/centering-markers/) there are pointer cursors and `clip` doesn't affect them.

**Comment by mourner** [comment]
@jfirebaugh it's nothing special, just `clip: rect(auto auto 40px auto)` on `.leaflet-container img.leaflet-marker-icon` set in dev tools (markers are smaller there).

**Comment by paulmach** [comment]
+1 Clicking right at the end of the arrow will open the top bike marker vs. the bottom one that it's closest too.

![strava](https://cloud.githubusercontent.com/assets/366320/4053027/2a3b4de4-2d73-11e4-8e5f-3badf228d51b.png)

**Comment by tmcw** [comment]
Closing; legacy.
