### ISSUE TITLE
race condition with map.markerLayer.loadURL()

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#481]
If you call `map.markerLayer.loadURL()` immediately after initializing the map, there's a race between the map TileJSON load and the markerLayer GeoJSON load. If the map loads first, it works as expected, but if the GeoJSON loads first then it will be overwritten by the TileJSON markers when they load.

map._initialize has some code to prevent the manual `setGeoJSON` case but not this one.

**Comment by loganfuller** [comment]
I seem to be running into the same situation by calling `setGeoJSON` immediately after initializing the map. Even though I wrap my `setGeoJSON` call in the `map.whenReady` callback the race condition seems to still be present.

**Comment by jfirebaugh** [comment]
@loganfuller First thing to check is that you're using v1.0.4 or later -- the prevention code for the `setGeoJSON` case was added in that version. If so, can you post your code?

**Comment by loganfuller** [comment]
Hmmm... I'm using the latest version of the mapbox.js library. Here's the code I'm calling which is running into a race condition:

``` javascript
var map = L.mapbox.map("map", "oikoi.map-gyc97fdh", {
    zoomControl: false,
    attributionControl: false,
    detectRetina: true,
    retinaVersion: "oikoi.map-12iwue78",
    features: [
        'bwdetect',
        'zoombox'
    ]
});

map.setView([data.latitude, data.longitude], that.getMapCenter().zoom);

map.whenReady(function(){
    map.markerLayer.on('click', function(e) {
        App.router.navigate("listing/" + e.layer.feature.properties.id, true);
    });
    map.markerLayer.on('mouseover', function(e) {
        that.cancelMarkerHover();
        e.layer.openPopup();
        that.handleMarkerHover(e);
    });
    map.markerLayer.on('mouseout', function(e) {
        that.cancelMarkerHover();
        e.layer.closePopup();
    });

    // Render markers
    map.markerLayer.setGeoJSON(JSON.parse(App.listings.toGeoJSON()));
}, this);
```

**Comment by jfirebaugh** [comment]
@loganfuller Yeah, that's another case. I'll fix it at the same time. In your case though you don't need to use `whenReady` -- just bind the events and `setGeoJSON` immediately and you should be good.
