### ISSUE TITLE
Manually clear tile cache?

### ISSUE THREAD

**Issue by robertjwhitney** [mapbox/mapbox.js#483]
I have changes to my tiles that I'd like to appear as I am currently in development. How are tiles being cached and is there a way to clear or disable it?

**Comment by tmcw** [comment]
That's a bit outside the scope of MapBox.js, and depends on how you're changing your tiles and where they're being served from.

**Comment by robertjwhitney** [comment]
@tmcw Hey, thanks. What is that inside of the scope of, and where can I find some documentation on how to adjust for it so I can develop my map at more than a snails pace?

**Comment by tmcw** [comment]
Depends on how you're changing your tiles. Are they MapBox Streets, an independent tile server, something generated from TileMill, or...?

**Comment by robertjwhitney** [comment]
They are mapbox tiles.

**Comment by tmcw** [comment]
There's currently no manual way to clear MapBox tile caches - the cache expiration is managed automatically so that traffic bursts don't affect performance.

**Comment by mnquintana** [comment]
@tmcw Is this still the case now? Just wanted to check. :smile: (To clarify, I'd like to bust the cache on end users' browsers.)
