### ISSUE TITLE
Redesign attribution control

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox.js#485]
_[Internal MapBox context here](https://github.com/mapbox/frontend/issues/172)_

As part of our work with promoting the relationship between OSM and MapBox maps, I built a lightweight Leaflet plugin ([demo](http://www.mapbox.com/labs/attribution)) that combined attribution and an 'Improve this map' link.

![cap](https://f.cloud.github.com/assets/200357/1050950/70c0fe40-10c2-11e3-8725-cf70cda6d916.gif)

This style could be refactored nicely as the default attribution for mapbox.js, with an optional 'improveMapLink' boolean attribute.

**Comment by incanus** [comment]
This button borrows heavily from the iOS look, which doesn't look like that anymore on iOS 7. 

![6-7](https://f.cloud.github.com/assets/17722/1077335/546c80e8-14fa-11e3-8eb1-fb5fa8aafc56.png)

**Comment by heyitsgarrett** [comment]
Would like to consider this for mapbox.js 1.5, including thinking about how the above 'Improve this map' interaction ideas could play a part in connecting dots between consumers of the map and OSM contributors.

**Comment by tmcw** [comment]
@heyitsgarrett the time is now: Leaflet v0.7.0 is launched and work is happening in the v1.5.0 branch. Would love to see if you can knock this out this week?

**Comment by tristen** [comment]
Taking this one on in https://github.com/mapbox/mapbox.js/tree/mapbox-attribution-control

**Comment by heyitsgarrett** [comment]
@tristen is a super:star:

**Comment by tristen** [comment]
Merged!
