### ISSUE TITLE
Mapbox sometimes doesn't resize

### ISSUE THREAD

**Issue by joeybaker** [mapbox/mapbox.js#488]
I don't have much data yet. Anecdotally, I know, that at somepoint after mapbox load, it will no longer load in new tiles to fill an expanded container when the window is resized.

**Comment by tmcw** [comment]
Hm, how is the window resized? If programmatically, the trick is probably `map.invalidateSize()`

**Comment by joeybaker** [comment]
Nope, just a straight up, manual, window resize. I've seen it for sure in Chrome and Chrome Canary. Looks like: 
![16bc62ac-1b14-11e3-96fa-8fa0cfcb4905](https://f.cloud.github.com/assets/36662/1125718/82e0cfde-1b16-11e3-8ea7-bf354ee2880f.png)

**Comment by joeybaker** [comment]
Also, I've got the `trackResize` option on:

``` js
L.mapbox.map(this.$el.attr('id'), 'xxxx', _.extend({
        trackResize: true
        , detectRetina: true
        , retinaVersion: 'xxxx'
      }
    , this.options.mapOptions))
```

**Comment by tmcw** [comment]
Hm, will need a more robust test case/live example to debug this. Cannot replicate it on vanilla maps.

**Comment by joeybaker** [comment]
@tmcw totally fair. I'll work on that.

**Comment by tmcw** [comment]
Closing for now, will need a robust test case.

**Comment by sethships** [comment]
I am seeing this as well.

Edit: Figured it out. I was using a callback debouncing function to avoid excessive calls. Binding to the normal window.resize callback instead resolved the issue.

**Comment by gingur** [comment]
running into the same issue, I'm dynamically resizing an outer container via js which doesn't trigger a "resize" event. hoping I can resolve by manually invoking a window resize event to trigger internal logic, but if there is anything available globally that directly relates to mapbox resize events that would be _stellar_

**Comment by garrett-thompson** [comment]
Manually triggering a window.resize event fixed for me
`window.dispatchEvent(new Event('resize'));`

**Comment by codingedward** [comment]
With jQuery, this worked for me:
```javascript
$(function() { map.resize(); });
```

**Comment by hlthi** [comment]
Resize when just in time.
```javascript
mapboxObj.on('dataloading', () => {
      window.dispatchEvent(new Event('resize'));
      // mapboxObj.resize(); also work
});
```

**Comment by NickCarducci** [comment]
````
this.mapRef.getMap().on("move", e => {
  if(this.state.notFlying){//low performance since flying (& resizing window) counts as move
    if (
      this.state.lastWidth !== window.innerWidth ||
      this.state.lastHeight !== window.innerHeight
     ) {
      clearTimeout(this.resize);
      this.resize = setTimeout(() => {
        this.setState({
          lastHeight: window.innerHeight,
          lastWidth: window.innerWidth,
          viewport: {
            ...this.state.viewport,
            width: "100vw",
            height: "100vh"
          }
        });
        this.mapRef &&
        this.mapRef.getMap() &&
        this.mapRef.getMap().resize();
      }, 200);
    }
  }
})
````

**Comment by stanjdev** [comment]
I'm using React.
I put this into my handleClick function on a button that I am using to toggle the map visible and invisible. I placed it AFTER my setState boolean logic to trigger the map's visibility
```
    setTimeout(() => {
      window.dispatchEvent(new Event('resize'))
    }, 0)
```

**Comment by Sefibrah** [comment]
Using **Angular**, try using ```delay(50)```, It worked for me. Useful info maybe on this link: https://gist.github.com/danswick/fc56f37c10d40be62e4feac5984250d2
