### ISSUE TITLE
How should this handle styles?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#5]
Should there be a mapbox.css? Should this implementation of MM.Map detect for zero-width & zero-height maps and correct them?

**Comment by tristen** [comment]
I wish we could avoid doing this. Not only to avoid another include but also to not make any assumptions of the design. 
A MM.Map detect makes sense to me for implementations that have not accounted for height or width. Also some sort of z-indexing on map controls that are attached to the map to ensure they are placed on top?

**Comment by tmcw** [comment]
Right now mapbox.min.css is something you would include yourself, and could not include or include a different version.

The z-indexing / controls issue is definitely a bug and should be fixed on another level, too, I think - like possibly putting them in a controls div separate from the map div.

**Comment by tmcw** [comment]
mapbox.css is the answer. Going that way.
