### ISSUE TITLE
Show CHANGELOG

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#50]
@tristen How do you think we should show the changelog online? Linking to GitHub might be a fine solution, though it'd be nice to have it front and center for early users.

**Comment by tristen** [comment]
How about in a post like format? The jQuery project does this to some degree on new releases http://blog.jquery.com I'm not saying call this blog at all - but a changelog section in the docs thats formatted in a post layout. This would give us a nice url to share.

**Comment by tristen** [comment]
Note that I've added a changelog here: #104
