### ISSUE TITLE
Duplicate max-width style on .map-tooltip

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox.js#501]
`max-width:300px;` is overridden by `max-width:280px;` a few lines below
https://github.com/mapbox/mapbox.js/blob/v1/theme/style.css#L57-79

**Comment by yhahn** [comment]
Capturing notes from discussion here:
- TileMill has a `280px` width tooltip but is not in a `box-sizing: border-box` context. With padding + border, it ends up being `300px` wide.
- While it'll be painful to transition `box-sizing: border-box` is a more robust and easier model to use with responsive design. Make this an explicit part of `mapbox.css` in a future release.
- Final width will be `300px`.

**Comment by tristen** [comment]
Captured in master and will be released in the next `v1.4.1` + versions
