### ISSUE TITLE
Sorting needed for API Examples

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox.js#509]
Looks like the sorting is off on the [API example list](https://www.mapbox.com/mapbox.js/example/v1.0.0/) (e.g. _Searching for Points_. On that note, it's been hit or miss when searching for examples. Is there a way to categorize examples into their primary utility (Layers, geoJSON, Tooltips, etc.) for easier searching?
@tmcw @willwhite

**Comment by tmcw** [comment]
I think this page is getting rewritten, confirm or deny @tristen

**Comment by tristen** [comment]
Functionality is largely going to remain the same for now - at least in the first iteration of the redesign. 
For the maki search, we used a tag list for broader searching. Could do something like that here.

**Comment by willwhite** [comment]
@heyitsgarrett is about to start a big push here with a plan to sketch something new out. I don't think there is a quick fix so maybe it makes sense to wait.

Is the issue concerning sorting or search/filtering?

**Comment by heyitsgarrett** [comment]
Yes, as per https://github.com/mapbox/mapbox.github.com/issues/1855 this is something that can be addressed there. In the meantime, it's probably cool to wait.

**Comment by incanus** [comment]
Adding in https://www.mapbox.com/mapbox-ios-sdk/examples/ I make pretty heavy use of tags here for search relevance.

**Comment by tmcw** [comment]
This page is redesigned - categories > sorting.
