### ISSUE TITLE
Refine how errors are handled

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#51]
As @aibram pointed out, currently `mapbox.load` and `mapbox.auto`, as well as layers, don't have much of a framework to deal with loading errors. We should do this, and try to do it well.

First off this would include callbacks getting an error parameter, either first (ala node), second (ala google), or in a second argument (ala jquery?).

Second we should try to narrow errors down into their types - is it an error because the id was wrong, or because the server is down?

**Comment by ansis** [comment]
Work in the [error branch](https://github.com/mapbox/mapbox.js/tree/error).

**Comment by tmcw** [comment]
error branch is merged. closing.
