### ISSUE TITLE
utf grid tooltips stop if lon exceeds +/-180

### ISSUE THREAD

**Issue by hrwgc** [mapbox/mapbox.js#510]
Tooltips stop working when user pans the map and goes beyond +/- 180.

Example:
- http://a.tiles.mapbox.com/v3/herwig.map-cfqguxwr.html#3/48.75/51.59
- http://a.tiles.mapbox.com/v3/herwig.map-cfqguxwr.html#3/42.62/-666.12

**Comment by tmcw** [comment]
![](https://upload.wikimedia.org/wikipedia/en/6/6a/Mordor.png)

> the problem is that past 180 lie other words where our rules do not apply
