### ISSUE TITLE
Share modal is buggy

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox.js#514]
There are a few problems with the share modal.
1. The close button in the top right corner does not work.
2. Zooming the map with scroll wheel/touch zoom doesn't dismiss modal.
3. It is impossible to select the embed code.
4. Clicking the share icon when the share modal is already open causes weird buggy behavior. On the second click, nothing visibly happens. But you can now no longer dismiss the modal and from then on, it pans with your map. If you click a _third_ time, another modal appears (then on a fourth click, same behavior as on second click, but for the new modal).

**Comment by wboykinm** [comment]
Note that if you refresh the page after this initial lock it then works just fine. You can select the embed code etc.

**Comment by tristen** [comment]
Fixed in v1.4.1 will publish this version shortly.
