### ISSUE TITLE
Plugin CDN

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#517]
@rsudekum brought this up; let's do a think after v1.5.0 about how we can cdn & provide 1-5 key plugins.

**Comment by mourner** [comment]
:+1: This is asked about quite often.

**Comment by tmcw** [comment]
Okay, initial thoughtpiece:
- Plugins are managed as npm modules and our plugin api specifies ranges of versions supported. Same basic deal as mapbox.js.

### Each plugin will require:
- semver
- API.md?
- How to represent compatible versions of Leaflet/MapBox.js?

### Potential starting choices:
- https://github.com/mlevans/leaflet-hash
- https://github.com/Leaflet/Leaflet.markercluster
- https://github.com/Leaflet/Leaflet.draw
- https://github.com/mapbox/leaflet.fullscreen

## URLs

Right now we have

```
//api.tiles.mapbox.com/mapbox.js/v1.4.0/mapbox.js
```

Plugins at

```
//api.tiles.mapbox.com/leaflet-hash/v0.2.1/leaflet-hash.js
```

Not seeing a huge reason to segment the namespace here or have a `/plugin/` url segment.

**Comment by wboykinm** [comment]
Ayup. :+1:  Those are the 4 that I always end up looking around for in crazy file trees. A CDN would rock.

**Comment by tmcw** [comment]
-> https://github.com/mapbox/mapbox.js-plugins

**Comment by heyitsgarrett** [comment]
![](http://media2.giphy.com/media/qHho9D3nk3nS8/giphy.gif)
