### ISSUE TITLE
Refine how ui works

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#52]
I'm not clear on how people will use the UI - there doesn't seem to be any way to access the actual control instances, so you can't remove or modify them, is that correct? @aibram

**Comment by ansis** [comment]
New UI api will look like this:

```
var ui = mapbox.ui.map(map);

ui.pointselector.add()  // Create control
ui.pointselector.locations() // Access pointselector functions as if ui.pointselector were an instance of wax.mm.pointselector
ui.pointselector.remove() // Remove control
```

There are two parts to this:
1. Adding `.remove()` to all controls in Wax.
2. Adding `add()` to all controls in a wrapper in ui.js, which will initialize the control and add elements/callbacks to the map.

**Comment by tmcw** [comment]
Sound good.

**Comment by tmcw** [comment]
Done friday, needs packaging.

**Comment by tmcw** [comment]
Done, needs to be formalized into an example. Will do that now.
