### ISSUE TITLE
Support Polygon Options

### ISSUE THREAD

**Issue by jlord** [mapbox/mapbox.js#523]
I'd like to style the (color, line width, opacity...) the polygons in my geoJSON. You can do this through the Leaflet API but it doesn't look like it's supported through Mapbox.js. If I go the Leaflet route, however, I lose the lovely Mapbox markers :(

I've searched around but haven't found a good solution/compromise. 

**with L.mapbox.markerLayer**

![screen shot 2013-11-03 at 4 40 55 pm](https://f.cloud.github.com/assets/1305617/1461338/fdf75c88-44a6-11e3-9ffc-49a9fbe09b8f.png)

**with L.geoJson(features, {"style": {"fillColor": "#ff00ff", "weight": "2", "color": "#333"}})**

![screen shot 2013-11-03 at 4 41 29 pm](https://f.cloud.github.com/assets/1305617/1461342/37b61e0a-44a7-11e3-85bf-c27ec5e399fd.png)

**Dreamland**
It would be awesome to be able to add polygon styles to the geoJSON itself the way Mapbox does with marker styles versus having to add them as an option as Leaflet does now. Something like this:

``` javascript
{
  "type": "Feature",
  "geometry": {
      "type": "Polygon",
      "coordinates": [
          [
              [
                  -122.41790771484375,
                  37.740381166384914
              ],
              [
                  -122.41790771484375,
                  37.74520008134973
              ],
              [
                  -122.40966796874999,
                  37.74520008134973
              ],
              [
                  -122.40966796874999,
                  37.740381166384914
              ],
              [
                  -122.41790771484375,
                  37.740381166384914
              ]
          ]
      ]
  },
  "properties": {
      "fillColor": "#9C9B9A",
      "wieght": "2"
  }
},
{
  "type": "Feature",
  "geometry": {
      "type": "Point",
      "coordinates": [
          -122.295856,
          37.826057
      ]
  },
  "properties": {
      "marker-size": "small",
      "marker-color": "#D4E487"
  }
}
```

Also, I :heart: Mapbox!

**Comment by jfirebaugh** [comment]
This gets you the MapBox marker style with normal Leaflet styling capabilities for other feature types:

```
L.geoJson(geoJson, {
    pointToLayer: L.mapbox.marker.style,
    style: {...}
});
```

The `style` option can also be a function that takes the GeoJSON feature, so you could do something like:

```
L.geoJson(geoJson, {
    pointToLayer: L.mapbox.marker.style,
    style: function(feature) { return feature.properties; }
});
```

(Untested, but you get the idea.)

**Comment by jlord** [comment]
Ah! Victory! Thank you @jfirebaugh!

![screen shot 2013-11-04 at 9 44 47 am](https://f.cloud.github.com/assets/1305617/1463737/d5bcf720-4535-11e3-8c1c-866374ddc070.png)

**Comment by tmcw** [comment]
Reopening to make an example for this - it's one of those special easter-egg functions we should document better :)

**Comment by tmcw** [comment]
Exampled: https://www.mapbox.com/mapbox.js/example/v1.0.0/geojson-marker-style/

**Comment by jlord** [comment]
@tmcw This is what I was secretly hoping would happen! Yay!
