### ISSUE TITLE
mixed content in examples

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#528]
- [x] https://www.mapbox.com/mapbox.js/example/v1.0.0/custom-marker/
- [x] https://www.mapbox.com/mapbox.js/example/v1.0.0/custom-marker-tooltip/
- [x] https://www.mapbox.com/mapbox.js/example/v1.0.0/external-layers/
- [x] https://www.mapbox.com/mapbox.js/example/v1.0.0/markers-with-image-slideshow/
- [x] https://www.mapbox.com/mapbox.js/example/v1.0.0/plain-leaflet/
- [ ] https://www.mapbox.com/mapbox.js/example/v1.0.0/wms/

**Comment by tmcw** [comment]
Put out a tweet about a SSL WMS server. If nobody responds today, I think we should just close here - the WMS example will always be connected to a failure point.

**Comment by tmcw** [comment]
Punting on WMS.

![](http://media.giphy.com/media/12QqHhlcsHEFsA/giphy.gif)
