### ISSUE TITLE
dead WMS source in WMS example

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#529]
The http://gis.srh.noaa.gov/ URL is giving me nothing but 400s.

**Comment by tmcw** [comment]
RIP only WMS server I thought was reliable

**Comment by wboykinm** [comment]
I mean it's ugly as hell, but there's always [BISON species abundance](http://bl.ocks.org/wboykinm/7312731)

**Comment by mourner** [comment]
One of the Leaflet examples (mesonet.agron.iastate.edu) is dead too it turns out. Using http://maps.opengeo.org/geowebcache/service/wms for a working one though :)

**Comment by tmcw** [comment]
It's back online. WMS!
