### ISSUE TITLE
Remove wax connector and mapbox.provider

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#53]
We should remove one or switch to the core modest maps version. Right now the wax provider is slightly different. Not sure whether we _need_ to have the wax.mm.connector interface still available; I don't think we do.

**Comment by ansis** [comment]
Removed mapbox.provider in e5298791ef0f7ada2a9742b3f9000abf0ff04944

Leaving the wax provider for now since it handles bw control stuff and tms tiles (not useful for mapbox, but probably makes sense in Wax).

**Comment by tmcw** [comment]
Okay, this is basically waiting on a big wax refactor, so closing.d
