### ISSUE TITLE
MapBox with Leaflet 0.7

### ISSUE THREAD

**Issue by luizgarruda** [mapbox/mapbox.js#532]
Is it possible to replace current MapBox version 0.6.4 of Leaflet with 0.7-dev?

Some of the Leaflet.label plugin features only work with 0.7.

Thanks.

**Comment by mourner** [comment]
@luizgarruda 0.7 will get released in about a week, with MapBox 1.5 to follow, so so it won't be an issue soon.

**Comment by jfirebaugh** [comment]
See also https://www.mapbox.com/mapbox.js/overview/#standalone-mapboxjs
