### ISSUE TITLE
Jitter on dynamically drawing a line

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#536]
I made this example since this question comes up a bit: https://www.mapbox.com/mapbox.js/example/v1.0.0/dynamically-drawing-a-line/

@mourner - calling setView repeatedly with monotonic movements seems to jitter the map back and forth on some systems - is there some way I can avoid this in the example or we can avoid it in Leaflet?

**Comment by bsudekum** [comment]
Pinteresting.

On Fri, Nov 8, 2013 at 9:49 AM, Tom MacWright notifications@github.comwrote:

> I made this example since this question comes up a bit:
> https://www.mapbox.com/mapbox.js/example/v1.0.0/dynamically-drawing-a-line/
> 
> @mourner https://github.com/mourner - calling setView repeatedly with
> monotonic movements seems to jitter the map back and forth on some systems
> - is there some way I can avoid this in the example or we can avoid it in
>   Leaflet?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mapbox/mapbox.js/issues/536
> .

## 

Bobby Sudekum
@bobws

**Comment by mourner** [comment]
Wow, that looks horrible. Seeing this for the first time. Will investigate.

**Comment by mourner** [comment]
@tmcw not reproducible on Leaflet master for me. But that example is for 1.0.0, could you update it to the latest mapbox.js version?

**Comment by tmcw** [comment]
That's a layout/design bug that @heyitsgarrett is working on - it's on v1.4.0, which means Leaflet v0.6.4

**Comment by mourner** [comment]
@tmcw all right, so it was probably fixed in master. Could you try that?

**Comment by tmcw** [comment]
Works in master, so will work in the next release of MapBox.js. For the time will tolerate the jitter.
