### ISSUE TITLE
mapbox.js vs MapBox.js

### ISSUE THREAD

**Issue by hrwgc** [mapbox/mapbox.js#540]
The [docs page](https://www.mapbox.com/mapbox.js/overview/) uses both MapBox.js and mapbox.js to refer to the library. What's the convention you want to go with here @tmcw? 

![](http://i.imgur.com/NSfM9W3.png)

**Comment by tmcw** [comment]
It is `MapBox.js`. Please prioritize this lower than shipping product, spelling, and everything else.

With the exception: if anything is stylized as a domain name, url, path, or anything even vaguely like a URL or URI, it is lowercase always. mapbox.com is not MapBox.com, geojson.io is not GeoJSON.io, and so on.
