### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#544]
https://github.com/mapbox/mapbox.js/blob/master/src/share_control.js#L85

**Comment by mourner** [comment]
If the repo still doesn't do jshinting in travis, it should — very useful.

**Comment by tmcw** [comment]
We haven't included it yet; right now we use the non-function form of `'use strict'` that makes jshint whine.

**Comment by mourner** [comment]
http://jshint.com/docs/options/#globalstrict
