### ISSUE TITLE
Icons glitch

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#549]
https://github.com/mapbox/mapbox.js/commit/703dd9e11d3a99797fa2e88b832dfb2235c216bc#diff-ee410c26af104479299e1544b3b88c40R468

Is this a shipped problem with v1.4.2 and we should publish a duplicate icon sprite as a stopgap? @tristen

**Comment by tmcw** [comment]
Via voice with @tristen: we are going to switch back to 26x26 for 1.5.0

**Comment by tristen** [comment]
stopgap is in place.
