### ISSUE TITLE
Fullscreen icon broken

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#551]
![](https://i.cloudup.com/uW2zlySjoc.png)

**Comment by tmcw** [comment]
This is more accurately described as:

Replacing the default Leaflet styles makes all plugins that make assumptions about them, like [leaflet.draw](https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-draw/) and any plugin that adds UI, have some quirks.

The question is whether @tristen can deal with these quirks and make them twerk, or if the meditation will lead him in another direction.

**Comment by tristen** [comment]
Switching back to 26x26 for 1.5.0

**Comment by tmcw** [comment]
Fixed in a18a4dc27bcfdec7cd79029a604bd798733f34a2
