### ISSUE TITLE
Markers list UI

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#553]
The new markers list in spaceship is cool! Now, should we have something similar for MapBox.js that people can include on API-embedded maps? Should it be a subset, or the whole thing?

These questions and more will be answered by you!

**Comment by tristen** [comment]
Related http://support.mapbox.com/discussions/general-questions/43859-mapbox-list-of-markers

**Comment by tmcw** [comment]
Too sprawly for core. Example: https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-list-click/
