### ISSUE TITLE
TileLayer options

### ISSUE THREAD

**Issue by chrisbartolo** [mapbox/mapbox.js#557]
L.mapbox.tileLayer is not working properly when using minZoom, maxZoom, and maxNativeZoom. These options are being ignored.

**Comment by tmcw** [comment]
Are you specifying them [as the second argument, as in the API documentation](https://www.mapbox.com/mapbox.js/api/v1.4.0/#L.mapbox.tileLayer)?

**Comment by chrisbartolo** [comment]
Yes, of course

**Comment by tmcw** [comment]
Note that `maxNativeZoom` is a new feature in Leaflet 0.7, and MapBox.js 1.4.2 is on Leaflet v0.6.4.

**Comment by tmcw** [comment]
The tileLayer is setting these options from TileJSON: if you want to override them, wait for `.on('ready'` and change them manually with `layer.options`.
