### ISSUE TITLE
`detectRetina` example on mapbox.js overview page appears incorrect

### ISSUE THREAD

**Issue by rdmurphy** [mapbox/mapbox.js#562]
After really struggling to figure out why `detectRetina` wasn't working on a map of mine, I finally put it together.

In the mapbox.js overview page's ["Retina" section](https://www.mapbox.com/mapbox.js/overview/#retina), the example has `detectRetina` being passed to a `L.mapbox.map` call, like so:

``` javascript
var map = L.mapbox.map('map', 'examples.map-y7l23tes', {
  detectRetina: true
}).setView([40, -74.50], 9);
```

But that's not how options [currently get passed](https://github.com/mapbox/mapbox.js/blob/master/src/map.js#L29) to the internal `tileLayer` call within `L.mapbox.map`. Instead it likely should be:

``` javascript
var map = L.mapbox.map('map', 'examples.map-y7l23tes', {
  tileLayer: {
    detectRetina: true
  }
}).setView([40, -74.50], 9);
```

Not sure if that's a future plan, but currently it's a little off.

**Comment by tmcw** [comment]
Looks like a bug in the docs.
