### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#564]
MapBox.js has user-facing strings in geocoder_control.js and share_control.js, and [info_control.js](https://github.com/mapbox/mapbox.js/pull/563) will add a few more.

Minimal i18n support would be pulling the strings into initialization options with English defaults.

**Comment by tmcw** [comment]
Would love to defer this as long as possible. Our user-facing strings should be minimal.

**Comment by tmcw** [comment]
The string in infoControl is pushed out, it's now in tilejson. There's very little to translate here.

**Comment by jfirebaugh** [comment]
Ok, punting.
