### ISSUE TITLE
Discrepancy between csv2geojson.js versions on examples and repo

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox.js#566]
There is a discrepancy between the [csv2geojson.js](https://github.com/mapbox/mapbox.js/blob/gh-pages/assets/csv2geojson.js) that is used in the [markers from csv example](https://www.mapbox.com/mapbox.js/example/v1.0.0/markers-from-csv/) and the [csv2geojson](https://github.com/mapbox/csv2geojson) repo. 

Tender: http://support.mapbox.com/discussions/mapboxjs/2910-mapbox-csv2geojson

**Comment by tmcw** [comment]
Dup #552 - will hit this tomorrow.
