### ISSUE TITLE
Mobile and Theme sections not populating in the sidebar

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#569]
The section names should be filterable in the sidebar

**Comment by connor** [comment]
@tristen is that what you wanted? 

![screen shot 2013-11-25 at 4 16 23 pm](https://f.cloud.github.com/assets/97697/1617610/41a7bb74-561f-11e3-8034-3a2ad4217b68.png)

**Comment by tristen** [comment]
@connor the [API docs are generated automatically](https://github.com/mapbox/mapbox.js/blob/gh-pages/_docs/generate.js). Need to investigate why those menu entries are not added to the generated front matter.

**Comment by tmcw** [comment]
-> #578

**Comment by connor** [comment]
Boom. ^:hand:, Tom.
