### ISSUE TITLE
Data Visualizations example not working

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox.js#570]
https://www.mapbox.com/mapbox.js/, switch to "Data Viz" tab:

```
Uncaught ReferenceError: statesData is not defined
```

cc @tristen

**Comment by mourner** [comment]
The problem is `http` in `http://leafletjs.com/examples/us-states.js`. It needs to be on `https`. And lets not hotlink anything from the Leaflet website — bad practice.

**Comment by tmcw** [comment]
Yes, @tristen plz no outside-of-mapbox links to js / data in any mapbox.js stuff.

**Comment by tristen** [comment]
Yep sorry about that! Fixed in https://github.com/mapbox/mapbox.js/commit/6c6e9a3686d0e4688430cd83b1d497e9205302ec
