### ISSUE TITLE
infoControl is off-grid

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox.js#573]
Seems odd that the infoControl is bumped a bit over the right, rather than lining up with the other UI controls when active.

![screen-shot-2013-11-21-at-2 19 37-pm](https://f.cloud.github.com/assets/200357/1596424/85b80ebc-52fb-11e3-98d3-0cfc923c9736.jpg)

**Comment by tristen** [comment]
This is probably an artifact of me rushing to fix support for positioning options. I'm on it.

**Comment by tristen** [comment]
Fixed in master. will be updated in the next tag.
