### ISSUE TITLE
Bug in mapstories

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#576]
```
mapstories.setView(chapters[i].getLatLng(), 13);
```

**Comment by wboykinm** [comment]
? Plan for this in 1.6?

**Comment by tmcw** [comment]
This is still a bug.

**Comment by wboykinm** [comment]
Not sure if it's related, but on my first visit to the new mapbox.js web home the "Storytelling" link pulled up exactly the same map and code as the "Basic" link. A refresh cleared it a few minutes later and [the right view came up](http://www.flickr.com/photos/vtcraghead/11183834693/), but you might be on the lookout for cache problems with that example.

**Comment by tristen** [comment]
There's no more map stories example on the frontpage as they are all being redirected to /examples. Closing this one.
