### ISSUE TITLE
Autoname marker layers

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox.js#58]
Naming the marker layers would make it easier to get/set/remove/enable/disable them. Maybe name them to `markers-layernamehere` or `layernamehere-markers`?

**Comment by tmcw** [comment]
Markers are automatically named `markers` - https://github.com/mapbox/markers.js/blob/gh-pages/src/markers.js#L41

Would this be a change at the mapbox.js level when markers are created with `mapbox-auto`?

**Comment by ansis** [comment]
Yeah, this would be set in `mapbox.load()` so that names are kept mostly unique. Do you have a preference for either?

**Comment by ansis** [comment]
Since we've switched to using ids instead of names for regular layers users are likely to rename manually anyways, so I don't think this is really necessary.
