### ISSUE TITLE
Zoom center inaccurate after scrolling

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#580]
Open http://www.washingtonpost.com/wp-srv/special/local/dc-shot-spotter/ scroll down, double-click on the map. The zoomed-around center is incorrect on my machine (Chrome Beta). /cc @mourner

**Comment by mourner** [comment]
Works fine for me on Chrome stable. I'll check it out on beta.

**Comment by connor** [comment]
Works fine for me, too.

**Comment by tmcw** [comment]
Cool, must be a beta bug.
