### ISSUE TITLE
tilejson spec parse problem

### ISSUE THREAD

**Issue by mgiraldo** [mapbox/mapbox.js#581]
(Tested this on Chrome 31 and Firefox 24 Mac)

Notice this (working) map: 

http://jsfiddle.net/r78Vv/1/

This is what you should see (a dotted red polygon on top of an old map):

![map with polygon](https://f.cloud.github.com/assets/133020/1635452/b41c4a04-57ae-11e3-8e01-7e36f9fecd8d.png)

The tileset has this TileJSON spec: https://s3.amazonaws.com/maptiles.nypl.org/859-final/859spec.json

If you use this other (valid) TileJSON spec: https://s3.amazonaws.com/maptiles.nypl.org/859-final/859specbug.json

Like so:

http://jsfiddle.net/r78Vv/3/

This is what you get:

![unresponsive map with botched polygon](https://f.cloud.github.com/assets/133020/1635480/2429d7d0-57af-11e3-935f-e0968541be2c.png)

The map is unresponsive, the polygon is botched, there are no JS errors in the console.

This problem was very difficult to isolate since we had no issues most of the time.

**Comment by tmcw** [comment]
On first glance, `specbug` has a flipped x/y coordinate for center and advertises `autoscale: true` but doesn't include a high-res version. Besides that, specbug has strict maxbounds that might be too strict. I can try reducing this test case but can you provide a JavaScript variation? CoffeeScript is not exactly the best platform on which to debug.

**Comment by mgiraldo** [comment]
Here you go:

Working: http://jsfiddle.net/gm2BV/1/

Not working: http://jsfiddle.net/gm2BV/2/

**Comment by mgiraldo** [comment]
By the way: the spec that has inverted x/y and has `autoscale: true` is the one that is working. The non-working does not have that. I did not add that since it was not a feature we needed but since a [MapBox tileset version](http://jsfiddle.net/r78Vv/2/) worked I decided to copy/paste all that was in it to test. I then just added a center point.
