### ISSUE TITLE
attributionControl v1.5

### ISSUE THREAD

**Issue by Martindelataille** [mapbox/mapbox.js#582]
Hi

it doesn't seem to work anymore on v1.5

L.mapbox.map(div, auth, {zoomControl: false, attributionControl: false})

**Comment by tristen** [comment]
@Martindelataille the attribution control in v1.5 is a newly named control called info. You can disable it with `infoControl: false`

**Comment by wboykinm** [comment]
[The UI toggle example](https://www.mapbox.com/mapbox.js/example/v1.0.0/toggling-ui/) needs to be updated to reflect this.
