### ISSUE TITLE
my geoJSON for markersLayer is lost

### ISSUE THREAD

**Issue by Siarhei-Hanchuk** [mapbox/mapbox.js#584]
in mapbox.js on init

```
if (this.markerLayer && !this.markerLayer.getGeoJSON() && json.data && json.data[0]) {
       this.markerLayer.loadURL(json.data[0]);
}
```

while markerLayer.loadURL wait response from server my app sets geoJSON for markers layer, and this code clears my data

**Comment by tmcw** [comment]
If you'd like to have a custom marker layer with custom GeoJSON, don't use `map.markerLayer`, create a new layer with `L.mapbox.markerLayer()`.
