### ISSUE TITLE
Upgrade the "Storytelling" promo example

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox.js#585]
The new frontpage "Storytelling" example is barebones compared with [Young's original Sherlock piece](https://github.com/mapbox/tutorial-sherlock). Is this a UX decision to keep things open for the users or are you guys just pressed for time to refactor the full-fledged interactive from MM to leaflet?

I've been using the danged thing so often I've been meaning to do it myself; should I?

**Comment by tmcw** [comment]
You mean easing? That would be in #204

**Comment by tristen** [comment]
I wanted to keep the storytelling example simple so that the code snippet for it would be much more digestible.

**Comment by wboykinm** [comment]
"Coordinated Easing" [Like this](http://wboykinm.github.io/geosprocket-labs/linear/)

But @tristen answered the main Q. Thanks!
