### ISSUE TITLE
geoJson points return "invalid latLong"

### ISSUE THREAD

**Issue by DDDgfx** [mapbox/mapbox.js#588]
Hi - there. Im trying to use mapbox.js to load some points with geojson. Ive grid to do it with the conventional method of loading geoJson from this page: http://leafletjs.com/examples/geojson.html

and with the pointToLayer solution. Both are returning errors of invalid latLong, but I've had no trouble at loading polygons and lines. Any suggestions?

**Comment by tmcw** [comment]
Please post a ticket at [http://support.mapbox.com/](support.mapbox.com) - this issue tracker is for confirmed bugs and improvements only.
