### ISSUE TITLE
Legend needs max-width

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/mapbox.js#592]
![screen shot 2013-12-06 at 2 23 46 pm](https://f.cloud.github.com/assets/200357/1695087/3387569a-5eac-11e3-9d35-51cc4d16223b.png)

For testing: http://mapbox-yh.s3.amazonaws.com/tornadoes-legend.mbtiles

**Comment by tmcw** [comment]
We should land this before 1.5.2 launch today/tomorrow, can you grab it @tristen ?

**Comment by tristen** [comment]
Caught this.
