### ISSUE TITLE
Real-world markers and areas

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#597]
This is a rising support concern, a Leaflet.realworld module might be in order
- geographical circles
- area of rectangles
- lines of some distance in some direction

**Comment by mourner** [comment]
BTW, geographical circles can be approximated by ellipses, right? I'll look into this after finish vector refactoring in Leaflet. Ellipses: https://github.com/Leaflet/Leaflet/pull/1993

**Comment by tmcw** [comment]
- http://mapbox.github.io/leaflet-geodesy/
- https://github.com/mapbox/leaflet-geodesy
