### ISSUE TITLE
Expose non-magic constructors

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#599]
Right now non-magic constructors are internal only and are not accessible on the API level. The only drawback of this is that it's not possible to extend the classes we create: that might be useful, though, and I want to see whether it's a possibility to expose the raw constructors as well.

**Comment by eyeseast** [comment]
+1

I've thought about asking for exactly this. I wrote the first iteration of [this app](http://stateimpact.npr.org/pennsylvania/drilling/) using Leaflet and wax (before there was mapbox.js), and putting utilities for loading and rendering data on the Map class really helped with code organization.

I got around this by simply extending the map instance (`_.extend(map, {...})`) but that's ugly.

Full source: http://si-fracking.s3.amazonaws.com/js/maps/big.js

**Comment by jfirebaugh** [comment]
I don't object to exposing them, though I prefer the module extension pattern for my own code:

```
function myMap(...) {
  var map = L.mapbox.map(...);

  map.extension1 = function() { ... };
  map.extension2 = function() { ... };

  return map;
}

var map = myMap(...);
```
