### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by mroswell** [mapbox/mapbox.js#601]
I'd like to be able to implement these examples. So far I'm encountering two issues:
1.  All of the examples in the master branch have dependencies such as the following:

```
    <link rel="stylesheet" href="../dist/mapbox.css"/>
    <link rel="stylesheet" href="embed.css"/>
    <script src="../dist/mapbox.js"></script>
```

however, I don't see any of these files.
1. The directions call for 
   npm install mapbox.js --save

I tried running this after the following:
git clone https://github.com/mapbox/mapbox.js.git
cd mapbox.js/
npm install

when I run the mapbox.js  install, I get "Refusing to install mapbox.js as a dependency of itself" Here are the details.

$ npm install mapbox.js --save
npm WARN package.json expect.js@0.2.0 No repository field.
npm WARN package.json sanitize-caja@0.0.0 No repository field.
npm WARN install Refusing to install mapbox.js as a dependency of itself

This is the third time I've tried to tackle these examples in earnest, without success. So, reaching out and asking for help.

**Comment by tmcw** [comment]
> All of the examples in the master branch have dependencies such as the following:

Use [these examples](https://www.mapbox.com/mapbox.js/example/v1.0.0/) - the dev branch examples are for testing only.

> The directions call for npm install mapbox.js --save

Only if you are using `browserify`: that isn't the default route, and you can just copy & paste the online examples.

**Comment by jfirebaugh** [comment]
@tmcw Let's move the dev branch examples directory to `test/manual` or something.

**Comment by mroswell** [comment]
Thanks. 
It might be helpful to link those examples to here:
https://www.mapbox.com/developers/api/

(that's where Google brought me when I searched for 
mapbox API

Also, you get there if you click on "Developers"
at the bottom of 
https://www.mapbox.com/s/
and then click on "How our maps work" or "Core API"

I very much look forward to working through these examples

**Comment by tmcw** [comment]
@jfirebaugh did that.

**Comment by tmcw** [comment]
MapBox.js is itself - the core api page should document our REST API. Since this README.md pushes to examples and so does everything else that's labeled MapBox.js, I think the IA is clear enough here.
