### ISSUE TITLE
Gaps when zooming

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox.js#605]
@tmcw @mourner -

Since recently, there are gaps when zooming in/out on a map. I noticed this first on the [Klondike map](https://www.mapbox.com/labs/klondike/) (mapbox.js 1.5.0) by @geraldarthur 

Here's an example zooming today on [this map](https://a.tiles.mapbox.com/v3/codeforamerica.map-mx0iqvk2/page.html#2/45.3/-32.3). Mapbox.js version 1.5.1. This is Chrome but I observed the same behavior on Safari:

![gaps](https://f.cloud.github.com/assets/98233/1764686/861800a4-672a-11e3-9b43-1b96cb3ab4dc.gif)

Likely an upstream issue w/ Leaflet if at all, but I wanted to report first here as I discovered this working with Mapbox.js 1.5.x

**Comment by mourner** [comment]
I'm also seeing it Chrome now, and this looks like a browser regression. Safari did this for a while. It's a bug with hardware accelerated scale transitions of tiled images. I'll look into it, but probably not easily fixable.

**Comment by mourner** [comment]
Hmm interesting, I don't see this effect in Chrome in Leaflet (both stable and master), but see it in mapbox.js, so it must be something in mapbox.js stylesheet causing this issue. cc @tristen

**Comment by mourner** [comment]
The culprit is probably the `-webkit-backface-visibility` hack for Android that got removed in CSS in 0.7.1 but not reflected in mapbox.js CSS.
