### ISSUE TITLE
Weird feature json shortcut

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#606]
https://github.com/mapbox/mapbox.js/blob/cfc221f03c2e853c233255a5e252c4aa05cf6640/src/marker_layer.js#L91

Why this? This is bad.

**Comment by jfirebaugh** [comment]
It's required for `toGeoJSON` to round-trip correctly, see [here](https://github.com/Leaflet/Leaflet/blob/cd84d75005ded20ad8eda89dfaa22a5efafb8c87/src/layer/GeoJSON.js#L163-L167).

/cc @mourner

**Comment by mourner** [comment]
@tmcw do you have an alternative solution for this?

**Comment by tmcw** [comment]
I assumed that `L.GeoJSON.geometryToLayer` would mean that the layer would properly roundtrip?

**Comment by mourner** [comment]
@tmcw it's called `geometryToLayer` because it only handles geometries, and roundtripping means saving feature properties.

**Comment by tmcw** [comment]
Okay, this is fine for an implementation detail.
