### ISSUE TITLE
Publish 1.6.0

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#611]
Waiting on https://github.com/isaacs/npm/issues/4405 , can't push npm package right now.

**Comment by tmcw** [comment]
@jfirebaugh can you try pulling & hitting `npm publish` here?

**Comment by jfirebaugh** [comment]
Published at `v1.6.0` tag.

**Comment by tmcw** [comment]
Thanks, https://github.com/mapbox/mapbox.js/pull/615 is the next step to publishing

**Comment by wboykinm** [comment]
Woooooooooo Leaflet docs!

One downside: the "Theming" section is currently [throwing a 404](https://www.mapbox.com/mapbox.js/api/v1.6.0/mapbox-theming)

**Comment by tmcw** [comment]
-> #620
