### ISSUE TITLE
How to preload full map before website is displayed?

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox.js#614]
I am using mapbox.js as a fullscreen background of a website. Depending on the server connection, the map is sometimes loading very slow and sometimes even stops so that you can see the different map-tiles loading after each other, which does not look very nice.

Is there a way to preload the whole map in the local cache, before the website is fully displayed?

There was a similar discussion about 2 years ago (http://bit.ly/1bKP7EN). 

Has there been an update so far?

**Comment by tmcw** [comment]
You can listen for the [load event on map.tileLayer](http://leafletjs.com/reference.html#tilelayer-load) and any other layers you add to the map, and then display the map when that fires.
