### ISSUE TITLE
mmg marker overlay overlaps tooltips

### ISSUE THREAD

**Issue by mayarichman** [mapbox/mapbox.js#62]
![](https://img.skitch.com/20120723-m63xw7neie47qxi7knkqiwubfb.jpg)

Each point has content that  displays with hover over, but because the tooltip is being created within the markers overlay, the z-index defaults to it's parent, the markers layer, and all points are shown above the tooltip.

There are ways to get around this, for example grabbing the content and plugging it into a div that falls above the markers layer, but I think there is a better more efficient solution for this problem, which I see occurring frequently as more sites are made with markers.js and mapbox.js.

**Comment by tmcw** [comment]
Is this using something similar to `markers.css`, which adds a high z-index to tooltips? https://github.com/mapbox/markers.js/blob/gh-pages/src/markers.css#L1

**Comment by mayarichman** [comment]
Yes, the z-index for the markers is the same.

**Comment by tmcw** [comment]
Can you post a link to a live example of this happening?

**Comment by mayarichman** [comment]
I changed the design of the site so the tooltips appear in a consistent place so I can't show you a live url of this anymore. But the original site in the photo is [developmentseed.org/nigeria-oil-mapping](developmentseed.org/nigeria-oil-mapping).

**Comment by tmcw** [comment]
Haven't been able to confirm. Closing.
