### ISSUE TITLE
Add Location Selected Event To geocodercontrol

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox.js#622]
I would like to be able to have an event emitted by the geocodercontrol when a location is selected (either from the list or automatically when just 1 result is returned) so that the selected location data can be used in parallel by other parts of the map.  For example when one searches for "Austin" on the MapBox Geocoding Dev example (see URL below) 11 different results are returned.  When one is selected the map immediately pans to this location at which I'd like to have moved a marker or other data there too.  The same use case would be when searching for a term that only returns 1 result (ex: "Seattle") and the map automatically pans to the new location.

https://www.mapbox.com/mapbox.js/example/v1.0.0/geocoding/

Looking at the API it looks like this event would be best accessed via the geocodercontrol.on() function, where currently only "found" and "error" events are supported.

https://www.mapbox.com/mapbox.js/api/v1.6.0/mapbox-controls#geocodercontrol.on

Thank you!

**Comment by tmcw** [comment]
Sounds like a reasonable addition, we'll work on this in the next release.

**Comment by bleege** [comment]
Awesome!  Thanks for making this happen!
