### ISSUE TITLE
Messed up docs links on individual pages

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox.js#624]
E.g. go to this page and try following any of the type links (LatLng, CRS, etc.):
https://www.mapbox.com/mapbox.js/api/v1.6.0/leaflet-map-class

**Comment by tmcw** [comment]
@mourner open to any ideas about how to fix this: we can either try to detect & rewrite all Leaflet embedded links, or stop recognizing those links altogether and try to automagically link up function references across the whole thing. Or if the Leaflet links are made to be more precise / easy to compose then maybe we have to do less tweaking to get them up to snuff.

**Comment by mourner** [comment]
A quick temporary fix would be to fix up all embedded links to link to the single page (unless the referenced id is present on the current one), and I'll look at improving this in Leaflet later.

**Comment by tmcw** [comment]
I'm planning on pushing improved docs for the next mapbox.js release and keeping this one the same. I'd rather fix a batch of issues at the same time and keep versions consistent.

**Comment by tmcw** [comment]
Worked around leaflet issues for now with b0cd8f960432f463127ee5bcc5632d78ba47edd1 and filed https://github.com/Leaflet/Leaflet/issues/2366 as a possible future path.
