### ISSUE TITLE
Improved examples pages

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#626]
I'm working on a new landing page for the site and want to emphasize our examples as a way to get started. In general, I would like to see a better search for examples implemented on this page and trying out a full width example layout. Here's a quick wireframe of what I have in mind:

![examples-wireframe](https://f.cloud.github.com/assets/61150/1887263/5f7288d4-79f9-11e3-99e1-95df284a5597.png)
- Searching for examples is emphasized at the top.
- Example subject with links are exposed in a pane. I think this column layout will lend itself some stronger readability over what we currently have:

![examples-wireframe-contents](https://f.cloud.github.com/assets/61150/1887285/dc162e72-79f9-11e3-8ae0-e069a386389a.png)
- Code output is toggled and contained in the same panel as the example.
- Optional content space below to walk through more elaborate examples.

cc @geografa @tmcw

**Comment by tristen** [comment]
Also to circumvent any losing cursor to scrolling in the map container when trying to read content below adding an example play mode might be worth doing. Like in http://bl.ocks.org/tmcw/7361200

**Comment by tmcw** [comment]
Can we pull up a bit and figure out what the issues with the existing page are, and how this solves them? Like:
- The example on top and then big listing under the fold has been tried and reverted
- Searching for examples has never worked well, this is a browsing-focused interface
- Why would we want to toggle code output and the map view on this page: this page is about looking at the two at the same time and understanding the connection between the two.

**Comment by tristen** [comment]
> The example on top and then big listing under the fold has been tried and reverted

I am not proposing that. I'm saying the reverse - listing above + search with example below. This gives us the affordance of a wider width map for examples that could use the space. 

> Searching for examples has never worked well, this is a browsing-focused interface

Cool, but right now I would argue its hard to browse this long vertical nav and a column structure would be a better layout. This is kind of silly:

![screenshot_2014-01-10screen shot 2014-01-10 at 9 12 33 am](https://f.cloud.github.com/assets/61150/1887664/5400b338-7a01-11e3-9c0f-4d5659c4088e.png)

> Why would we want to toggle code output and the map view on this page: this page is about looking at the two at the same time and understanding the connection between the two.

Yeah, I agree here.

**Comment by tmcw** [comment]
Would it work to just make the left sidebar `overflow: auto`?

**Comment by mourner** [comment]
I agree with @tristen's point about layout. The same problem is on the reference pages — browsing the sidebar with lots of empty space on the right sucks.

**Comment by tmcw** [comment]
My point is about amount of suck: this sucks but is usable. I think it would be more useful to work on stuff like the crashcourse and plugin cdn and queue up design tweaks like this for when we have time to hit non-essential tweaks.

**Comment by mourner** [comment]
I'd argue about this being non-essential. Users should be able to quickly glance at the list on both examples and reference pages to immediately see what's possible. While they scroll down, they loose context. This makes it harder to get started.

**Comment by tmcw** [comment]
Okay, so we add overflow: auto to the list, make it scroll, and that issue is done.

**Comment by tristen** [comment]
Um that wouldn't look great at all and removes the ability to browse them faster. The example panel and code snippets are variable width - applying a fixed height to the navigation with overflow:auto would be jarring.

The search interface I proposed gives us:
1. Better scanning between sections
2. Browser searching
3. Retains the option to filter.
4. Better scalling.

I'm jfdi in a branch over the weekend.

**Comment by samanpwbb** [comment]
I think @tmcw is saying make the listing overflow-auto in the current left-sidebar based layout. Always felt myself like left contents lists are the way to go for documentation, but that we should fix position + overflow auto them. This is a problem on our docs everywhere. Usually fixed + scrollable makes me happiest on other sites. see http://backbonejs.org/ / https://www.dropbox.com/developers/datastore/docs/js

This has added advantages of a) keeping search/filter bar accessible all the time (which you'd lose with a top search bar) and b) being applicable to all docs and examples everywhere on our site.

**Comment by tmcw** [comment]
Yep, that. An uncollapse click -> new page -> uncollapse again -> click again flow works worse than scrolling, especially if scrolling is done well like backbone's docs.

**Comment by tristen** [comment]
That works well because the layout has a fixed left sidebar. The current layout as it is would not bode well for an overflow:auto applied to the sidebar.

**Comment by tristen** [comment]
OK I'm on the same page with a fixed layout like this. example docs either look different from the current site or we design the site around a layout like this.

**Comment by tristen** [comment]
Closed in favour of https://github.com/mapbox/mapbox.js/pull/629
