### ISSUE TITLE
Marker rotation example

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#628]
Using uber makes me wonder if people think this is hard. Gottadoit.

**Comment by tmcw** [comment]
https://twitter.com/Mapbox/status/422532237276741632

**Comment by mourner** [comment]
Nice! BTW, it may appear in upstream Leaflet soon https://github.com/Leaflet/Leaflet/pull/2362

**Comment by tmcw** [comment]
Cool, yeah - when we update to the new release of Leaflet there'll probably be a few examples that could benefit from some refactoring.
