### ISSUE TITLE
Mapbox 1.6.0 standalone + Leaflet 0.7.1 css breaks tooltips

### ISSUE THREAD

**Issue by tcql** [mapbox/mapbox.js#630]
Using mapbox 1.6.0 standalone along with leaflet 0.7.1's css causes tooltip styling to be broken. Tooltip tails and close buttons don't work right at all.

Including leaflet CSS followed by 1.6.0 standalone, I see this:

![2014-01-14-100824_3286x1080_scrot](https://f.cloud.github.com/assets/348805/1911644/44c1235e-7d2f-11e3-9256-9682fba05f74.png)

If I remove the leaflet CSS and switch to 1.6.0 full, I see a proper tooltip
![2014-01-14-100905_3286x1080_scrot](https://f.cloud.github.com/assets/348805/1911658/6dda9342-7d2f-11e3-94ce-c017f60e5161.png)

**Comment by mourner** [comment]
Mapbox.js is not meant to be used with Leaflet CSS, just use Mapbox.js CSS and you'll be good to go.

**Comment by tcql** [comment]
Oh, well that makes sense. I guess I misunderstood that. Out of curiousity, what then would be a use case for mapbox.standalone.css?
