### ISSUE TITLE
"Legend" toggle in "Toggling UI" example doesn't work

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#634]
The example code uses `document.getElementById('legend')`, and there are conflicting elements with `id=legend` on the page (the other one is the "Legend" section in the examples list).

I think we should reserve the id space for the examples, and avoid using ids in the examples list.

**Comment by tmcw** [comment]
we could also scope our getElementByID calls off of the map container or such?

**Comment by jfirebaugh** [comment]
A little more verbose, but probably a practice that should be encouraged. :+1:
