### ISSUE TITLE
Fix hashes to doc IDs from the API toc

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#637]
This is a tricky one as we are generating the docs by reading API.md in master, re-writing the html output and breaking sections into separate pages.
### Problem example ..

In the TOC of the API we have a method name like **L.mapbox.gridControl(layer, options)**

It has a link to `api/v1.6.0/mapbox-controls/#l.mapbox.gridcontrol` that's derived from the title L.mapbox.gridControl

In actuality though it should link to `#l-mapbox-gridcontrol-layer-options-` which is the id that's generated in the docs. Albeit `#l-mapbox-gridcontrol-layer-options-` looks a little gross with the hyphen appended at the end, we need to either:
- Re-write the id in the docs to match method name minus the parenthesis.
- Don't write the parenthesis into the title and replace `.` with `-`
- Add a new field in navigation: front matter that has a hash entry matching that of the id.

**Comment by tmcw** [comment]
The switchup with ids may or may not be due to the markuku/markdown/whatever switch.

**Comment by tristen** [comment]
Woot! Solutions! Fixed in the merged branch of `fixed-layout`
