### ISSUE TITLE
Supporting legacy versions of the documentation.

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#638]
Currently mapbox.js supports legacy versions of examples and docs which is a bit of a time suck and leads to some wacky logic in the templates. Are there better options here? I would love to drop older versions from mapbox.com/mapbox.js and just support them from GitHub. As in, Looking for v0.6.7 documentation? Go to https://github.com/mapbox/mapbox.js/blob/v0.6.7/API.md

**Comment by tmcw** [comment]
Yes for 0.6.7. I don't see supporting v1.x documentation as onerous at this time.

**Comment by aaronlidman** [comment]
Why not include them in deployed versions on s3? Zip up the entire thing assets and all and put it in there.

**Comment by tmcw** [comment]
Before we get into the weeds here, what's the root problem we're trying to fix?

**Comment by tristen** [comment]
I find it onerous on the time it takes to build the site.

**Comment by tmcw** [comment]
https://github.com/mapbox/mapbox.github.com/issues/3112

**Comment by tmcw** [comment]
Closing; we should work around technical causes for this rather than cutting old docs.

**Comment by tristen** [comment]
Really though? How do propose working around the technical causes? https://github.com/mapbox/mapbox.github.com/issues/3112 isn't going to work. I don't know what supporting old docs buys us. We already have tagged states for an API.md from the repo. Why not link to this? Keeping v0.6.7 examples around is a burden and so will future tagged versions of the api.

**Comment by tmcw** [comment]
> I don't know what supporting old docs buys us.

We should not break links on the site without good reason. API docs are exactly the things that people link to from the internet and expect the link to stay around Forever with Very Good Reason. We do not break links.

If Jekyll is crapping out on the 245 HTML files it needs to concat between things, we should work on that, whether it's figuring out how to get Young's hack to work or switching some parts away from Jekyll.

**Comment by tmcw** [comment]
The implication, of course, is that if you want to write the redirects to make this work, then go for it.

**Comment by tristen** [comment]
> switching some parts away from Jekyll.

I think this needs to happen then. With sections of the API now being cut into their own posts this is going to be a rebuild suck for Jekyll. 

Also, If the analytics are not high on examples/ usage for the v0.6.7 version I would be a heavy :thumbsup: on dropping this.
