### ISSUE TITLE
Release 1.6.1 with Leaflet 0.7.2

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox.js#639]
Leaflet 0.7.2 fixes a critical issue introduced by Chrome 32 stable update — mouse events are shifted on maps when the page is scrolled down.

**Comment by tmcw** [comment]
Cool, would love to hear from @tristen about whether we could wrap up fixed-layout and roll documentation fixes and updates into this release.

**Comment by tristen** [comment]
Yes! Let's aim for a release tonight?

**Comment by jfirebaugh** [comment]
:beers:
