### ISSUE TITLE
Document addLayer, addTileLayer

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#64]
These are overridden and the behavior is not necessarily expected (I'm not confident that it's really that absolute a question... there may be semi-transparent layers that people do want over markers).

Regardless, if we're going to keep it, it needs to be documented and explained.

**Comment by ansis** [comment]
Is it a good idea to override addLayer? Or should we just provide addTileLayer?

**Comment by ansis** [comment]
automatic use of addTileLayer has been removed, and addTileLayer is documented
