### ISSUE TITLE
Passing TileLayer options to L.mapbox.Map

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox.js#640]
The docs are a little ambiguous / don't actually tell you that you can pass TileLayer options when you're creating a map.

![screen shot 2014-01-20 at 5 55 39 pm](https://f.cloud.github.com/assets/515424/1959784/acb23fcc-8237-11e3-818a-6b71a11785bf.png)

Unclear as evidenced by my attempts to support retina displays...

``` javascript
var map = L.mapbox.map('map', 'rclark.map-hibbity', { detectRetina: true });
```

which didn't work so...

``` javascript
var map = L.mapbox.map('map', 'rclark.map-hibbity', { tileLayer: false });
L.mapbox.tileLayer('rclark.map-hibbity', { detectRetina: true });
```

which seemed redundant.

Then I [read the code](https://github.com/mapbox/mapbox.js/blob/master/src/map.js#L34-L37) and found out that you can just

``` javascript
var map = L.mapbox.map('map', 'rclark.map-hibbity', { tileLayer: { detectRetina: true } });
```

I'm happy to take a stab at adjusting the docs if it seems useful to others.

**Comment by tmcw** [comment]
Definitely could be clearer here: take a shot at improving this & PR it.

**Comment by rclark** [comment]
Related things that came up = 
- there are other options for any of the different controls / layers that could be defined by TileJSON. Worth documenting?
- I didn't find any developer docs about how to build docs locally to see your changes. This is what I did, but maybe there's a better way or I missed something? I'd like to write some instructions into a readme if that's okay.

``` sh
git clone git@github.com:mapbox/mapbox.js && cd mapbox.js
# ... make changes ...
git checkout -b update-docs
git commit -am "changed API.MD file"
npm link
cd .. && git clone git@github.com:mapbox.js mapbox.js.docs -b gh-pages
cd mapbox.js.docs/_docs
npm install
npm link mapbox.js
./build.sh
cd .. && jekyll serve
```

**Comment by tmcw** [comment]
Can you add more detail to documentation at https://github.com/mapbox/mapbox.js/blob/master/DOCUMENTING.md ?

Also, if you're going to advise an `npm link` approach please be super explicit that the result of that should never be deployed: docs are deployed off of tagged versions, and never updated in place unless absolutely necessary.

**Comment by rclark** [comment]
> Also, if you're going to advise an npm link approach

I'll write what I did up in that file, but if you have a smoother approach I'm all ears.

**Comment by jfirebaugh** [comment]
> docs are deployed off of tagged versions, and never updated in place unless absolutely necessary.

In my opinion, we should modify this guideline because it conflicts with our goal of having the best possible documentation. Gating documentation changes by Mapbox.js releases mean errors and shortcomings in the documentation remain around for longer than necessary. Documentation changes should have a lower barrier than code changes.

I propose the following guideline instead: if we find an error or want to make an improvement, we update the documentation for the most recent release in place.

To facilitate this, we may need to make the deployment process for documentation updates easier.

**Comment by tmcw** [comment]
Word, I'm more or less in a state of agreement after this push.

> To facilitate this, we may need to make the deployment process for documentation updates easier.

Definitely. Would very much appreciate any help here: the `generate.js` and `_build.sh` scripts are very unloved and only really @ansis and I have dared to touch them.

**Comment by tmcw** [comment]
Okay: follow-up tasks re: fixing the flow of doc updates in general are at #652
