### ISSUE TITLE
'Hosted on github' notice: change

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#643]
![](https://dl.dropboxusercontent.com/s/jqcjrp6mkxpe08s/2014-01-22%20at%2011.30%20AM.png)

I don't think this is an effective callout. We should point people to a feedback form or support or something, and not at the bottom of every documentation page.

**Comment by incanus** [comment]
Why, to open it up to non-GitHub users, too? Or something else?

**Comment by tmcw** [comment]
So this is based on:
- The actual number of documentation fixes that have come through this channel is very very low
- People who know what Github is and will do the full PR cycle will do it regardless of shoutout
- We link to Github elsewhere and I think we should make better use of this screen real-estate, making a clearer path for all users to report issues or get help

**Comment by incanus** [comment]
Awesome, thanks. Makes sense to me.

**Comment by tmcw** [comment]
Removed this for now.
