### ISSUE TITLE
Remove section headers when filtering

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#649]
If there are no contents within a subject when filtering, we should hide them

![screen shot 2014-01-22 at 5 09 44 pm](https://f.cloud.github.com/assets/61150/1979467/f50acc14-83b1-11e3-9ca1-60b1de5be3bc.png)

**Comment by jfirebaugh** [comment]
:+1: Was just going to file this.

**Comment by aaronlidman** [comment]
Fixed 9278d6f7e3553283a8bf15938542482c12356ceb
