### ISSUE TITLE
tone down "Select" UI on plugins page

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#650]
![image](https://f.cloud.github.com/assets/98601/1980398/1aac119e-83c1-11e3-92f2-811dd4c69fb4.png)

The blue bars are visually the heaviest and most eye-catching elements on the page -- a bit out of proportion to their importance.

**Comment by aaronlidman** [comment]
These and all mapbox.js docs 'select' buttons are going to be zeroclickboard buttons, #644, which should be much smaller. I'll hopefully get to that soon.

**Comment by aaronlidman** [comment]
![screen shot 2014-01-25 at 7 33 15 pm](https://f.cloud.github.com/assets/58878/2002977/81fa4336-8621-11e3-8984-980175b26eb6.png)
