### ISSUE TITLE
make doc updates easier and more timely

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#652]
Splitting off of #640.

Goal: make it so that if we find an error or want to make an improvement, we can quickly update the documentation for the most recent release in place.

To facilitate this, we need to make the deployment process for documentation updates easier.

First thing I want to investigate is merging gh-pages into a `docs` subdirectory on master, so you don't have to have two checkouts of the repository or switch between branches a lot. This will require publisher support for publishing from a branch other than gh-pages.

**Comment by jfirebaugh** [comment]
The Jekyll maintainers are having a similar discussion: https://github.com/jekyll/jekyll/issues/1964.

**Comment by tmcw** [comment]
This is merged, and awesome.
