### ISSUE TITLE
Swipe Layers example - Issue in IE 11

### ISSUE THREAD

**Issue by gouilaz** [mapbox/mapbox.js#655]
Hi 

Just wanted to post a problem with the swipe layers example in IE : 
https://www.mapbox.com/mapbox.js/example/v1.0.0/swipe-layers/

Somehow dragging the input slider doesn't update the map immediately. The map only updates itself when one is panning or zooming into it. I am using Windows 7 and IE 11.0.9600.16476. It works fine on other browsers.

**Comment by tmcw** [comment]
There's not much we can do on this issue - if IE11 doesn't support `clip()` correctly, it's a browser bug that should be fixed on that side.
