### ISSUE TITLE
Docs sidebar scrollbar is weird in the bottom position

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox.js#656]
When you scroll the sidebar down to the bottom, it doesn't stop like it would at the top, but disappears (partially in Chrome, completely in FF), which leaves an impression that something weird is going on, e.g. there are more items in the list that are clipped.

**Comment by tmcw** [comment]
@tristen could you take a look at this? Combined with the base bug I just filed, it seems like this sidebar html/css could use some robusting or simplifying.

**Comment by tristen** [comment]
Yep - assigning.

**Comment by tmcw** [comment]
Sidebar rewritten, closing.
