### ISSUE TITLE
Filtering not working when search string is deleted after searching a not found result.

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#658]
That title is a mouthful. Here is an example:

![filter-bug](https://f.cloud.github.com/assets/61150/2014771/27ad4736-87aa-11e3-8936-b5165a57709c.gif)

@aaronlidman pretty sure this bug was introduced with this commit https://github.com/mapbox/mapbox.js/commit/9278d6f7e3553283a8bf15938542482c12356ceb

**Comment by tmcw** [comment]
Closing: rewriting filtering / searching this morning, we need better-than-incremental improvements here.

**Comment by tmcw** [comment]
Closing: rewriting filtering / searching this morning, we need better-than-incremental improvements here.

**Comment by tristen** [comment]
:thumbsup:
