### ISSUE TITLE
Broken link from L.mapbox.map page to L.map

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#661]
It links to .../l-map, but actual page is .../l-map-class!

See #654.

/cc @lyzidiamond

**Comment by jfirebaugh** [comment]
The script that generates the links between the Mapbox.js and the Leaflet documentation assumes a particular convention for IDs, but the Leaflet documentation deviates from the convention [here](https://github.com/Leaflet/Leaflet/blob/d3435383e94e00c87e4988a05d45fde5e1e4223a/reference.html#L129), using `id="map-class"` rather than `id="map"`.

**Comment by tmcw** [comment]
(as you'll soon find out, we also have an overeager CSS rule that makes anything with `#map` big and white and rectangular like a map)

**Comment by lyzidiamond** [comment]
Ah, thanks for explaining! Was doing some Leaflet explaining at CfA and it was causing some problems for some folks.

**Comment by mourner** [comment]
Yeah, I think I made an exception in Leaflet docs for the same reason.

**Comment by geografa** [comment]
Tender link: http://support.mapbox.com/discussions/general-questions/44184-broke-links-in-api-docs
