### ISSUE TITLE
Not all examples are shown

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#666]
Specifically [this guy](https://github.com/mapbox/mapbox.js/blob/mb-pages/_posts/examples/v1.0.0/0100-01-01-plain-leaflet.html) - seems like the rework now has a hardcoded list of categories included? @tristen

**Comment by tristen** [comment]
This isn't an artifact of the rework. A hardcoded list of category names is how it was done previously. 

We could generate the list automatically but then we wouldn't have the [nice titles](https://github.com/mapbox/mapbox.js/blob/mb-pages/_layouts/pages.html#L2-L24)

**Comment by tmcw** [comment]
Okay, so let's just add the missing ones.

**Comment by tristen** [comment]
Looks like `leaflet` was the only one.
