### ISSUE TITLE
clarify changing navigation handlers in docs

### ISSUE THREAD

**Issue by mayarichman** [mapbox/mapbox.js#67]
The example for changing navigation options, found [here](http://mapbox.com/mapbox.js/example/disable-zooming-and-panning/), implies the following handler options are the accepted parameter names, i.e. drag, mousewheel, etc.

> //The 4th argument is a list of handlers (drag, mousewheel, doubleclick).

Could you change this or make a note elsewhere that lists the acceptable values, i.e. _easey_handlers.TouchHandler()_, etc.

**Comment by tmcw** [comment]
This is probably waiting till we integrate MM docs more fully in the next docs refresh.

**Comment by ansis** [comment]
Done in 30005bac9ac99558cb6bbac576ae23091669348c
