### ISSUE TITLE
which version to use?

### ISSUE THREAD

**Issue by mgiraldo** [mapbox/mapbox.js#670]
Hi

I cloned the repo and ran the make script. This produces several mapbox.js. I try all of them (renamed to `mapbox.js`) with my code and none works. If I just download the one available in `https://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.js` it all works. I know this is kind of the stupidest question ever but I haven't been able to make the npm-generated scripts to work for me.

What am I missing?

Thanks

**Comment by tmcw** [comment]
If you've followed [all the instructions under building, and haven't seen any error messages](https://github.com/mapbox/mapbox.js#building), use the files in `dist/` - mapbox.js, mapbox.css, and the `images/` directory

**Comment by mgiraldo** [comment]
Yes. No error messages. The tests ran fine. Then I deleted the whole `/dist` folder and re-ran. The new mapbox.js works. Maybe it does not overwrite if present? I did have a previous build from a few versions ago.

Thanks

**Comment by tmcw** [comment]
Hm - it should be have just like any other Make-based build system - if the mtimes of the source files are more recent than the mtime of the target files, then it'll rebuild (or if the target is missing)

**Comment by tmcw** [comment]
Closing - location of the files is covered in [Building](https://github.com/mapbox/mapbox.js#building), must have been an intermittent issue.
