### ISSUE TITLE
non-interactive variation of leaflet heat demo

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#672]
We need a simpler, more straightforward example of Leaflet Heat. People will not connect the dots.

**Comment by mourner** [comment]
Just revert commits then, it was simple initially

ÓÕÂÂÏÔÁ, 8 ÆÅ×ÒÁÌÑ 2014 Ç. ÐÏÌØÚÏ×ÁÔÅÌØ Tom MacWright ÎÁÐÉÓÁÌ:

> We need a simpler, more straightforward example of Leaflet Heat. People
> will not connect the dots.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mapbox/mapbox.js/issues/672
> .

## 

Vladimir Agafonkin
http://agafonkin.com/en
+380 (93) 745 44 61

**Comment by tmcw** [comment]
Oh, let's keep the fun version :). Just need a simpler one too
