### ISSUE TITLE
Add gridlayer interactivity examples

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox.js#677]
We're getting a few requests in Mapbox Support regarding gridLayer interactivity. We need more examples for:
- layer exclusivity (for legends and tooltips)
- images in tooltips (base64)
- tileLayers, gridLayers, gridControls, legendControls - examples using and defining each

**Comment by raphadasilva** [comment]
Hi ! I've published a type of "one at time" switcher here. The code is not very pretty, but it works and splits up steps between tileLayer, gridLayer and gridControl.

http://raphi.m0le.net/data/BAS/Exemples/Mapbox_switchers/layer_switcher_v1_gcfalse.html

I've got also one example, which includes a "for" loop. Here's the templante : 
https://github.com/raphadasilva/mapbox_switcher_layers/blob/master/layer_switcher_for_loop.html
