### ISSUE TITLE
Refocus Examples

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#685]
Examples are a great way to dive in, answer questions like what's possible, and stop gap support zombies.

The multiple roles they provide also make the list of examples impossible to navigate with your brain. Like https://www.mapbox.com/mapbox.js/example/v1.0.0/geocoder-keep-open/ shows what a "true" option does. Whereas https://www.mapbox.com/mapbox.js/example/v1.0.0/rotating-controlling-marker/ is much broader, touches on many components of the library and feels like a more complete thought.

I want to refocus the role examples play and this is important to get right. User's spend a lot of time on these pages and nailing the first impression is going to help in the long term.
### Action plan
- **Document [usage examples](https://www.mapbox.com/mapbox.js/example/v1.0.0/geocoder-keep-open/) in `api/`**. These should fall under a heading like _Example usage_ after a function name . These need to be easily linkable for support questions that come up.
- **Merge similar examples into one**. Our strategy should be that there is a single way to do this. Document any alternative approaches in the code if necessary.
- **Drop `v0.6.7` examples**. Let's focus on Leaflet. In the long term this drops questions related to older code.  We shouldn't officially support it in any capacity.
- **Strong contrasts**. Examples should have visual distinctions that are easy to remember and navigate to.  Cut a few great looking base maps to use in the [examples account](https://www.mapbox.com/projects/?id=examples) and pair them with nice simplestyles for features. If examples can't be represented by a screenshot then maybe they can be represented by a symbol or badge that describe what the example does. 
- **Rewrite any titles and description**. Titles make it easier to navigate to an example in the listings. These should be concrete and describe what an example does in a parsable way. The description fields allows for adding any specific plugin name or explanation of the example that otherwise feels ambigious as a title.

A refocused examples ticket is a detour from the [Docs Navigation quest](https://github.com/mapbox/mapbox.js/pull/681) but I think working on this will help me to feel more confident in changes to the site navigation.

**Comment by tmcw** [comment]
The bottleneck here, right now, is search. It's actionable and has been for weeks - can you do that first?

**Comment by tristen** [comment]
I'm fine with working on search but I'm talking about the role examples play here.

**Comment by tmcw** [comment]
Yes, let's talk about the larger questions once we've eliminated the straightforward tasks: the fact we can't say like "search for an example that uses tileLayer with the search function" makes this problem seem larger / more abstract than it is.

**Comment by incanus** [comment]
Could tags help with this without having to work on search specifically? e.g. https://github.com/mapbox/mapbox-ios-sdk/blob/mb-pages/_posts/examples/0200-01-01-marker-image-color.html#L7-L16

**Comment by tmcw** [comment]
@incanus we've got a clear way to do search with swiftype, so we don't need to punt w/ tags or similar

**Comment by lxbarth** [comment]
@tristen - I would love to see us move on navigation first:

https://github.com/mapbox/mapbox.js/pull/681#issuecomment-35523021

**Comment by yhahn** [comment]
@tristen's jumping on search + better titles/org here to start.

Examples has been a challenge to think through for coming up with a solid nav/IA across the board so I asked him to take this on as a way to simplify his thinking elsewhere.

**Comment by lxbarth** [comment]
@yhahn @tristen - cool.

**Comment by tmcw** [comment]
Okay, 0.6.7 is removed and the main action here, beyond search, is titles & descriptions, so let's move that remaining task to #690
