### ISSUE TITLE
Add Leaflet-minimap to plugins?

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#687]
Should we add Leaflet-minimap to plugins? I see we have an example for it and we require the file locally https://github.com/mapbox/mapbox.js/blob/mb-pages/assets/Control.MiniMap.js

**Comment by tmcw** [comment]
Would be game for this if you can convince them ( https://github.com/Norkart/Leaflet-MiniMap ) to tag a release. All plugins must have tagged releases with stable version numbers.

**Comment by tmcw** [comment]
Done https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-minimap/
