### ISSUE TITLE
Chrome popping up warning for using dpi instead of dppx in CSS

### ISSUE THREAD

**Issue by antidis** [mapbox/mapbox.js#695]
Chrome is having some trouble with the Mapbox CSS. In Chrome 33.0.1750.117/Mac, and Chrome 35.0.1866.0 canary/Mac, the following warning pops up as a result of the Mapbox CSS being loaded:

"Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)"

The source of this line is here:

``` css
@media
  (-webkit-min-device-pixel-ratio:2),
  (min-resolution:192dpi)
```

...which is missing a dppx declaration. The equivalent "future-proof" query, which _should_ work, is below:

``` css
@media
(-webkit-min-device-pixel-ratio: 2),
(min--moz-device-pixel-ratio: 2),
(-o-min-device-pixel-ratio: 2/1),
(min-device-pixel-ratio: 2),
(min-resolution: 192dpi),
(min-resolution: 2dppx)
```

...as detailed here: http://css-tricks.com/snippets/css/retina-display-media-query/

I say _should_ because Chrome seems to be falling over anyway, acting as if dppx isn't referenced: https://code.google.com/p/chromium/issues/detail?id=336276

Would it be possible to update the CSS to avoid this warning, once Chrome fixes its warning bug?

**Comment by tmcw** [comment]
@tristen does your commit above fix this?

**Comment by tristen** [comment]
I just fixed up that commit preserving 192dpi and adding 2dppx. Will return to this and make any adjustments when the warning bug is addressed.

**Comment by antidis** [comment]
Thanks @tristen

**Comment by awallace-ihouse** [comment]
So this hasn't made it into the production code yet? I see it on my pages now, using:
    https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.css

**Comment by antidis** [comment]
It has. Chrome is still reporting this error, but incorrectly so. Chrome will need to fix this on their end too, but it looks like there's a fix in review: https://code.google.com/p/chromium/issues/detail?id=336276

Chrome also reports it on its own default tab screen (!!!)

**Comment by awallace-ihouse** [comment]
Thanks for the info! Luckily it’s only annoying, as opposed to fatal.

————————————
Andrew Wallace
awallace@cisdata.net

**Comment by ghost** [comment]
I thought this had been fixed? 
I'm using v2.1.4 (linking from your api) and I still get the warning in Chrome 38.0.2125.122 m (64-bit) on Windows 7
![mapbox-warning](https://cloud.githubusercontent.com/assets/4698220/5025938/c7eff6e6-6b1e-11e4-9ed7-d9688687c524.jpg)

**Comment by jfirebaugh** [comment]
The remaining warnings come from Leaflet: https://github.com/Leaflet/Leaflet/issues/2258 (fixed on master branch but not in a release yet).
