### ISSUE TITLE
The zoomslider bar is missing

### ISSUE THREAD

**Issue by jeromegv** [mapbox/mapbox.js#699]
Hi all

When switching from Leaflet to Mapbox.js, I've noticed that the black bar to adjust the zoom with the plugin ZoomSlider is no longer working

The example has the same issue
https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-zoomslider/

![screen shot 2014-03-03 at 22 59 38](https://f.cloud.github.com/assets/86115/2317618/8545cc98-a351-11e3-8099-173082076417.png)

**Comment by tmcw** [comment]
Indeed, that looks a bit broken. We use a different stylesheet than default Leaflet and this might be an unintended style incompatibility. @tristen could you check this out?

**Comment by tristen** [comment]
Ah looks like this has something to do with the `box-sizing` rule in our css.

**Comment by jeromegv** [comment]
Thanks guys! Just switching from Leaflet/Cloudmade to Mapbox (following yesterday's announcement), this was the only issue I had. Great work.

**Comment by jeromegv** [comment]
hey guys, just noticed that the fix did not work in Firefox. It does work in Chrome and Safari thought.

**Comment by tristen** [comment]
@jeromegv Thanks for the catch. The commit above should fix things.
