### ISSUE TITLE
Max zoom may not be applied

### ISSUE THREAD

**Issue by dhcole** [mapbox/mapbox.js#70]
Looking at the main sample map and the simple timeline map, I noticed you can zoom one level too far:

http://mapbox.com/mapbox.js/

**Comment by ansis** [comment]
It doesn't automatically set a zoom range, so it defaults to 0-18. Should it try to handle this by finding the maximum zoom range of all its layers (which may have different zoom ranges)?

**Comment by dhcole** [comment]
I think adjusting the default to 0-17 to match mapbox-streets is probably fine. We should document / have an example on how to set the zoom range (and perhaps bounding box) though.

**Comment by ansis** [comment]
Sounds good, set in ed6ff35af0d23e3d71de557c1ea709df8738ed63
