### ISSUE TITLE
API for Custom Project?

### ISSUE THREAD

**Issue by justinbretting** [mapbox/mapbox.js#700]
Hi All - I was wondering if there are any plans in the works to expose an API for creating projects (IE, custom maps - the same projects that are available as a logged in user). We also have several other questions that we'd love to connect with the MapBox team on. If anyone is available to contact me directly, would certainly appreciate the chance to connect. Thanks!

**Comment by geografa** [comment]
Sure thing. Just email us at support@mapbox.com for technical questions specific to your maps, the editor, or APIs or sales@mapbox.com for plan and account info.

**Comment by justinbretting** [comment]
Thanks for the quick follow-up :) Sent an email to sales on Friday but hadn't heard back yet, figure this might be a decent alternative route for a fairly technical question. Will shoot one over to support now.

**Comment by geografa** [comment]
:+1:
