### ISSUE TITLE
Mapbox.js 1.6.2

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox.js#701]
@tmcw - 

When's a good time to roll 1.6.2? Can't wait to ship https://github.com/mapbox/mapbox.js/pull/673 for everyone.

**Comment by tmcw** [comment]
I've got time tomorrow night to review and deploy a revision, and then the blog post will go live friday? Would love to get #702 out there as well.

**Comment by jfirebaugh** [comment]
Would be nice to get a fix for https://github.com/Leaflet/Leaflet/issues/2510 in if it's ready in time. If not, not a big deal, we can reroll or make a special build for embeds when it becomes a hard blocker for instrumentile.

**Comment by tmcw** [comment]
@jfirebaugh let's do a special build for embeds instead of bundling that with a release, it'll keep the schedules for instrumentile & this release decoupled.

**Comment by mourner** [comment]
@jfirebaugh I've fixed that issue yesterday.

**Comment by jfirebaugh** [comment]
Thanks @mourner. I agree with @tmcw, this can wait for a separate release.

**Comment by tmcw** [comment]
Deployed npm+tag+cdn+mapboxjs+documentation.
