### ISSUE TITLE
Geocoder control should fallback to lat/lon when no bounds present

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox.js#702]
Currently geocoder_control is expecting bounds on all results. This assumption won't hold true for point results. https://github.com/mapbox/mapbox.js/blob/master/src/geocoder_control.js#L121-L122

Will look into a PR for the next release.

**Comment by tmcw** [comment]
the next release is nowsies so i'm just gonna pull together a fix.

**Comment by yhahn** [comment]
thx tom

**Comment by wraybowling** [comment]
Thanks!
