### ISSUE TITLE
Natural Earth 2 example in TileMill gallery doesn't load

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#703]
https://www.mapbox.com/tilemill/gallery/#mapbox.natural-earth-2

In JS console is: Uncaught TypeError: Cannot read property 'lat' of null

**Comment by tmcw** [comment]
Yep, a bug, but in YAML in tilemill, not in mapbox.js https://github.com/mapbox/tilemill/issues/2232

**Comment by tristen** [comment]
Fixing this in the `docq` branch. Sily yaml.
