### ISSUE TITLE
TileJSON link goes to wax docs

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox.js#711]
Was looking to change [this](https://www.mapbox.com/mapbox.js/api/v1.6.2/l-mapbox-map/) but I can't find where. Is this in mb-pages?

![screenshot 2014-03-10 13 28 45](https://f.cloud.github.com/assets/134753/2378756/bc9e291a-a892-11e3-9b6c-76d478c0c927.png)

**Comment by tmcw** [comment]
mapbox.js docs are autogenerated from [API.md](https://github.com/mapbox/mapbox.js/blob/master/API.md) into [posts in the api dir of that project's mb-pages branch](https://github.com/mapbox/mapbox.js/tree/mb-pages/_posts/api)

**Comment by geografa** [comment]
:+1: https://github.com/mapbox/mapbox.js/commit/6154c57dbb51a922e781cd12d2e053b47f61efc5
