### ISSUE TITLE
Geocoder response doesn't include bounds for higher levels

### ISSUE THREAD

**Issue by wraybowling** [mapbox/mapbox.js#712]
Results from the Javascript geocoder are formatted in a way that does not include bounds for the surrounding political boundaries.

Results from the reverse geocoder are formatted as such that these bounds are included.

To see this problem visualized, compare the boxes that appear in this jsfiddle when the "find me" button is used (reverse geocoder) versus searching a location via the geocoder
http://jsfiddle.net/rgbk/JgmE3/13/

**Comment by tmcw** [comment]
This is a detail of the API we need to document, but it's not a bug: address results from the geocoder are simply points, not areas, so they do not include bounds data, only latitude and longitude vaues.

**Comment by wraybowling** [comment]
The Reverse Geocoding web service uses a single point just like the Geocoder JS API uses a single point. The results from a Geocoder query already include the outer political boundaries.

Let's use "New York City" as an example. I can use the geocoder search or the reverse geocoding web service to pinpoint New York City. In both cases the "New York" is part of those results because it surrounds New York City. I think then that the bounds should always be included so I can always make use of data that is of type "country" or type "region" or any other type that is an area in the real world.

**Comment by dpoirier** [comment]
It would be a nice feature if when you geocoded input that wasn't as detailed as a street address, it would return the bounds of the political entity it was able to come up with.  E.g. if the input was just "Albany, NY", it would include a bounding box for Albany.

**Comment by tmcw** [comment]
> E.g. if the input was just "Albany, NY", it would include a bounding box for Albany.

Not sure what you mean: this is already the case: https://a.tiles.mapbox.com/v3/examples.map-vyofok3q/geocode/Albany%2C%20NY.json

**Comment by wraybowling** [comment]
What dan meant to say is that a result for Albany NY would include the bounds for New York, and likewise the bounds for the US.
