### ISSUE TITLE
how to import legends from mapbox the same way maps are imported

### ISSUE THREAD

**Issue by abbood** [mapbox/mapbox.js#713]
I currently import mapbox maps such as [this](https://a.tiles.mapbox.com/v3/lri.hb670c6k/page.html?secure=1#11/33.8567/35.5957) one by simply using it's map id (ie `lri.hb670c6k`) and adding it into a [jekyll](http://jekyllrb.com/) generated website. The trick is to specify this information in an md file like so:

```

---
layout: map
firstlayer: "lri.hb670c6k"
lat: 33.756
lon: 35.712
zoom: 9
permalink: /climate_change/lri.hb670c6k

---
```

However there is a legend associated with the above map.. but i'm not sure how to get hold of that information from the map itself using the above technique (or any other technique for that matter).. ideas?

**Comment by abbood** [comment]
I got this answer on SO:

If your map has a legend built in, when you construct your map object, it will load/display with it:

```
  L.mapbox.map('map', 'lri.hb670c6k');
```

If you're adding it as a tileLayer, you'd be looking at adding the legend from the tileLayer's tileJSON:

```
tileLayer.on('ready', function() {
      legend = map.legendControl.addLegend(tileLayer.getTileJSON().legend);          
    });
```

however my client is using mapbox 0.6.7.. is there a way to address this in that version?

**Comment by tmcw** [comment]
Something in this vein should work:

``` js
wax.tilejson('lri.hb670c6k', function(data) {
    wax.mm.legend().map(map).content(data.legend);
});
```
