### ISSUE TITLE
Slider on mapbox.com front page 

### ISSUE THREAD

**Issue by gouilaz** [mapbox/mapbox.js#714]
Hi there 

This is not really an issue or anything. I was wondering if you guys from mapbox could share the script that is used for the slider on the front page of https://www.mapbox.com/ ? 
I am currently searching for a slider that is capable of doing exactly that on your main page, sliding through 4-5 different maps. Keep up the great work and thanks a lot! 

Best regards

**Comment by tmcw** [comment]
Sure: right click & view the source of the page. The code that runs the slider is unobfuscated.

**Comment by gouilaz** [comment]
Thx. Thought I ask before taking anything from the source. Have found the code. Best
