### ISSUE TITLE
Zoom Lens example is no longer round

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#720]
![image](https://f.cloud.github.com/assets/98601/2479194/d9124354-b091-11e3-97c0-bc885696d355.png)

**Comment by geografa** [comment]
works externally so must be CSS(?) on our side that's mucking with it.

**Comment by incanus** [comment]
Maybe a missing shadow asset?

**Comment by tmcw** [comment]
@incanus this is a css trick - it doesn't require any images.
