### ISSUE TITLE
Polygons not appearing in IE8

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#724]
http://www.browserstack.com/start#os=Windows&os_version=XP&browser=IE&browser_version=8.0&zoom_to_fit=true&full_screen=true&url=http%3A%2F%2Fa.tiles.mapbox.com%2Fv3%2Fmishobaranovic.gm7oookm%2Fmm%2Fzoompan%2Czoomwheel%2Cgeocoder%2Cshare.html%3Fwmode%3Dtransparent%2312%2F-37.8139%2F144.9452%3Fwmode%3Dtransparent&resolution=1280x1024&speed=2

@mourner any ideas why this might not work? Markers show up, so the cross-domain request suceeds, and there are no errors in the console. Could this be because of the CSS differences? /cc @tristen

**Comment by tristen** [comment]
Any [browser conditions are here](https://github.com/mapbox/mapbox.js/blob/mb-pages/theme/style.css#L760-L773) and we're not messing with vml.

**Comment by mourner** [comment]
Yes, you need to add back the VML stuff if you want IE8 support.

**Comment by tmcw** [comment]
So, we'll need to mess with vml. We have not dropped IE8 support on embeds at this point.

**Comment by tristen** [comment]
Just added https://github.com/mapbox/mapbox.js/commit/13317918afd56f341635c9abe07bc8461ae14374 needs testing.

**Comment by tristen** [comment]
Alright that fixes things

![](http://cl.ly/UjN7/Screen%20Shot%202014-03-31%20at%2011.04.47%20AM.png)
