### ISSUE TITLE
embed code from share page is share page, not embed page

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox.js#728]
Every mapbox map has two different pages, the share page (1): https://a.tiles.mapbox.com/v3/saman.map-c9578zur/page.html and the embed page (2): http://a.tiles.mapbox.com/v3/saman.map-c9578zur/attribution,zoompan,zoomwheel,geocoder,share.html

From the share page, the embed link points to (1):
![screen shot 2014-04-01 at 7 02 28 pm](https://cloud.githubusercontent.com/assets/108094/2585712/cea3b542-b9f1-11e3-8229-e03d25f5879a.png) `<iframe width="100%" height="500px" frameBorder="0" src="https://a.tiles.mapbox.com/v3/saman.map-c9578zur/page.html?secure=1#3/58.40/-129.38"></iframe>`

From the mapbox editor, the embed link points to (2):
![screen shot 2014-04-01 at 7 03 28 pm](https://cloud.githubusercontent.com/assets/108094/2585716/e15c8bfa-b9f1-11e3-833e-df6844502bb2.png) `<iframe width='100%' height='500px' frameBorder='0' src='http://a.tiles.mapbox.com/v3/saman.map-c9578zur/attribution,zoompan,zoomwheel,geocoder,share.html'></iframe>`

From the share page, we probably want to link to the embed, not page.html right?

**Comment by tmcw** [comment]
We are using `tilejson.embed` in https://github.com/mapbox/mapbox.js/blob/mb-pages/src/share_control.js#L70 so seems upstream
