### ISSUE TITLE
geocoderControl positions other than left are breaky

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#734]
See http://geojson.io/#map=2/20.0/0.0

The geojson control's style does not detect or accomodate for positioning other than `left`. It should flip, ideally.

**Comment by tristen** [comment]
This should accomodate for bottom positioning as well. Thinking the results will populate above the input in the same was as it does in tm2.

**Comment by tristen** [comment]
https://github.com/mapbox/mapbox.js/pull/747
