### ISSUE TITLE
Line edits moving map view centering

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox.js#736]
I'm just becoming familiar with this tool but I've noticed when attempting certain line edits (not always reproducible) the center of the map view has been moving ~50 miles north. My attached map has this problem when clicking on the (poorly reproduced) Valley Trail Run in Washington, DC:

[drewbo19.i282koj3](https://a.tiles.mapbox.com/v3/drewbo19.i282koj3/page.html?secure=1#13/39.4585/-77.0447) (opening will likely be centered in the "wrong" location)

Seems non-reproducible using shared link, only works when logged in and editing.

**Comment by jfirebaugh** [comment]
Hi @drewbo. Thanks for the report. Since this seems to be an issue with the mapbox.com editor rather than mapbox.js itself, please email support@mapbox.com and we'll figure out what's up. Thanks!
