### ISSUE TITLE
Provide Compiled Version of code for Bower

### ISSUE THREAD

**Issue by willfarrell** [mapbox/mapbox.js#740]
Currently I'm using `https://github.com/platanus/bower-mapboxjs` for bower since I don't use requirejs. Is it possible to update your build process to generate `/dist/*.{js,css}` files? I prefer to get the code from the creators. Thanks again for an awesome service.

**Comment by tmcw** [comment]
See https://github.com/mapbox/mapbox.js/issues/404 - happy to accept a pull request that does this properly, but otherwise you can use bower install with http urls.

**Comment by willfarrell** [comment]
Thanks, I'll see what @platanus is doing. Maybe they can create a PR.
