### ISSUE TITLE
doc formatting - overlap with sidebar

### ISSUE THREAD

**Issue by mick** [mapbox/mapbox.js#741]
![screen shot 2014-05-09 at 1 01 53 pm](https://cloud.githubusercontent.com/assets/26278/2932707/01dc4a7e-d7b5-11e3-9e87-0757aa0a0abe.png)

The last section of the doc is overlap with the sidebar.  Seen on https://www.mapbox.com/mapbox.js/example/v1.0.0/static-map-from-geojson-with-geo-viewport/ in chrome.  Maybe a missing closing tag?

**Comment by tmcw** [comment]
yep, noticed this too - this little message at the bottom was my addition, and thus doesn't have total `base.css` foo attached, would love a code review by @tristen or @samanpwbb https://github.com/mapbox/mapbox.js/blob/mb-pages/docs/_layouts/example.html#L59-L66

**Comment by tristen** [comment]
I'll take a peek!
