### ISSUE TITLE
L.Marker not working

### ISSUE THREAD

**Issue by hemantgudadhe** [mapbox/mapbox.js#742]
Previously when I using L.Marker through cloudemade multiple marker was displayed. Today I am using L.mapbox marker not displayed. Please suggest me.
My code is below :+1: 

``` js
MapClick = L.marker([latitude, longitude], {
                       icon: myIcon
                    }).bindLabel(positions[i].split(";")[2] + " " + positions[i].split(";")[3] + " knots", { noHide: true }).addTo(map).bindPopup($('.popover-content').html()).showLabel();
map.setView([latitude, longitude], zoomlevel);
```

**Comment by mourner** [comment]
Please provide us with a minimal test case reproducing the issue, e.g. in a JSFiddle.

**Comment by tmcw** [comment]
@hemantgudadhe please open a new issue with complete code, if you can provide more information.
