### ISSUE TITLE
Leaflet code working with Mapbox key

### ISSUE THREAD

**Issue by hemantgudadhe** [mapbox/mapbox.js#746]
Previously I was using Leaflet code :

var map = L.map('mapDiv').setView([51.505, -0.09], 2);

var te = L.tileLayer('http://{s}.tile.cloudmade.com/14a642b9a57141fea80e5207fa2f4a08/60885/256/{z}/{x}/{y}.png', {
maxZoom: 18,
attribution: 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>'
}).addTo(map);

As per shutdown mail, then I replace cloudemade to Mapbox :

var map = L.map('mapDiv').setView([45.505, -0.09], zoomlevel);

L.tileLayer('https://{s}.tiles.mapbox.com/v3/hemantgudadhe.i3gllj3d/{z}/{x}/{y}.png', {
attribution: '<a href="http://www.mapbox.com/about/maps/" target="_blank">Terms & Feedback</a>'
}).addTo(map);

I have question all changes of leaflet code is working corretly with MapBox key ?

**Comment by mourner** [comment]
It should work correctly, what's the problem?

**Comment by hemantgudadhe** [comment]
thanks for replied, there is no problem with development just I am asking for future. Because all development is working with leaflet code in testing server, we have plan to purchase plan for production.
