### ISSUE TITLE
Share control option: add a string

### ISSUE THREAD

**Issue by aborruso** [mapbox/mapbox.js#749]
Hi,
it would be very useful to have the possibility to add a string in the share messagge, to add in example an hashtag string.

Thank you,

Andrea

**Comment by tmcw** [comment]
You can use L.Class to extend the L.mapbox.ShareControl class and [replace the _shareClick](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/share_control.js#L51-94) function with something custom - I don't see a clean way to make this configurable by default.

**Comment by aborruso** [comment]
Thank you
