### ISSUE TITLE
example: switch between variables in a vector choropleth

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox.js#758]
The [vector choropleth](https://www.mapbox.com/mapbox.js/example/v1.0.0/choropleth/) example is -while complex - one of the coolest ones available. You know what would make it cooler? A toggle between multiple variables.

![switch](https://cloud.githubusercontent.com/assets/735463/2975261/ee748118-db92-11e3-89ae-db904d414f67.gif)

I [tried to do this myself](http://geosprocket.github.io/sactree-map/), but it devolved into a tangled spaghetti-mess when I realized I couldn't easily make all the [chained functions](https://github.com/mapbox/mapbox.js/blob/mb-pages/docs/_posts/examples/v1.0.0/0100-01-01-choropleth.html#L40-L68) reusable. Someone who knows what the hell they're doing could pull this off. Someone like @tmcw.

**Comment by iandees** [comment]
Our example has very little to do with mapbox.js, but here's how CensusReporter does it:

http://censusreporter.org/data/map/?table=B06011&geo_ids=040%7C01000US

(use the "show column" dropdown)

**Comment by tmcw** [comment]
https://www.mapbox.com/mapbox.js/example/v1.0.0/choropleth-joined-data-multiple-variables/

**Comment by wboykinm** [comment]
Awesome. Thanks!
