### ISSUE TITLE
No tiles loaded in IE10 for local html file

### ISSUE THREAD

**Issue by danielopitz** [mapbox/mapbox.js#759]
I have a local html file for a simple map. I use the latest version of mapbox.js to get the tiles and when I open it in Firefox everything is fine. But opening it in Internet Explorer 10 results in blank webpage with only the zoom controls in the upper left corner and shows the "SCRIPT5: Access is denied" message in the console. After switching to leaflet.js the map shows up without any problems on IE10.

I need to show the local file in an application which only has IE10 engine as rendering backend, so not using IE10 or hosting the webpage online is not an option.

Examples from the documentation work without any problems on mapbox.com, but as soon as I want to use them locally no tiles are loaded.

As mapbox.js is a leaflet.js plug-in, I'm wondering where the difference comes from and if any fix for this issue is available.

Platform: IE10, Win7 64bit, mapbox.js v1.6.2

**Comment by tmcw** [comment]
Are you switching the exact same code between Leaflet & Mapbox.js, or making changes other than that? Mapbox.js will not be able to request any sort of remote resources when served on a `file://` protocol or similar because of [the Same Origin Policy](http://en.wikipedia.org/wiki/Same-origin_policy) (same as any other JavaScript using CORS)

**Comment by danielopitz** [comment]
For mapbox.js I use:

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>A Simple Map</title>

<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
<script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.css' rel='stylesheet' />

<style>
  body { margin:0; padding:0; }
  #map { position:absolute; top:0; bottom:0; width:100%; }
</style>
</head>
<body>

<div id='map'></div>
<script>
var map = L.mapbox.map('map', 'examples.map-i86nkdio')
    .setView([40, -74.50], 9);
</script>

</body>
</html>
```

For leaflet, as stated in Help section of the Mapbox webpage:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset=utf-8 />
    <title></title>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
    <style>
        body { margin:0; padding:0; }
        .map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>
<div id='map' class='map'></div>
<script>
var map = L.map('map').setView([51.505, -0.09], 13);
L.tileLayer('https://{s}.tiles.mapbox.com/v3/my.map/{z}/{x}/{y}.png').addTo(map);
</script>
</body>
</html>
```

As mentioned - Firefox and Chrome have no problem at all with running both examples, but IE10 doesn't run the mapbox.js one.

**Comment by tmcw** [comment]
If you're running these from non-http urls, then the Mapbox.js code won't work - non-http(s) protocols will make interaction with any sort of AJAX request (like the one Mapbox uses to initialize a map) unpredictable and likely breaky. You can either run this from a http url (like with a local server) or use the Leaflet code with Mapbox.js, since it won't require an AJAX roundtrip.

**Comment by tmcw** [comment]
@danielfox Can you provide any more details? What the errors were in IE10, or if you were able to get this fixed?

**Comment by danielopitz** [comment]
@tmcw I used the approach you mentioned (Leaflet way of initializing the map and adding tile layer to it) and this is my workaround ATM. I won't be doing complex stuff for a while, so it is not necessary to initialize it the mapbox.js way, but would rather be good in the future.

Recently I tested the mapbox.js map initialization in IE once more and there was a small improvement - IE asked to allow blocked content and after confirming, the map was actually shown (as I wrote this bug report even this didn't work, after confirming nothing shown up). But in my application I embed IE rendering engine via SWT Browser and the popup doesn't show up (and I don't want my users confirm it each time). It is a local file so I can't add it to safe pages in IE (which would automatically allow blocked content).

The security policy of IE seems to be more strict than the ones of Firefox and Chrome and that is the problem here. The only error / warning IE has ever shown was `SCRIPT5: Access is denied` as mentioned in the initial comment.

**Comment by tmcw** [comment]
Hm - okay, sounds like IE10 doesn't allow CORS for local files. This is unfortunate, but it's a corner case that shouldn't really affect the design here.

**Comment by danielopitz** [comment]
Funny thing - it started working today (local HTML file in IE10 with Mapbox.js map initialization). I have no idea why, it just works without any problems (and nothing was changed in IE settings, no windows update, nothing).

**Comment by tmcw** [comment]
Open to alternatives here: unless I'm missing something, if you're developing a webapp locally, you should be doing so with a local server like SimpleHTTPServer or one of the many alternatives. Non-`http` or `https` protocols are very much 'voiding your warranty' in terms of how web pages in general will behave.
