### ISSUE TITLE
Swipe layer handle displaced after zoom

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox.js#76]
Swipe layer handle [doesn't correspond to tileset breakpoint](http://flic.kr/p/cDBoAU) after a swipe of any kind followed by a zoom in. Doesn't seem to occur on zoom out.

Happens on Chrome. Doesn't happen on FF, though handle exhibits some weird grabbing/releasing behavior on both.

**Comment by ansis** [comment]
The issue where clipping gets stuck when zooming is fixed in new ModestMaps d52266d8c8511890cfda8a1481b0052355222125

A bunch of handle fixes in 078debfe7a58adf4fc872bf7ae536b4876c7be7a
