### ISSUE TITLE
example: overlay projected image on map

### ISSUE THREAD

**Issue by jalbertbowden** [mapbox/mapbox.js#760]
i converted usgs drg's for virginia from .tif to .png so they can be viewed on the web...but its so limited; i do have a real purpose for this that hopefully okfn/cfa can utilize to further digitize government, but without map uses, image conversion is rather trivial, if not mundane at this point. i got .tif's from here:  
http://libremap.org/data/state/virginia/drg/  
.png conversions posted here:  
https://www.flickr.com/photos/jalbertbowdenii/sets/72157644649919101/  
for reference of what i'm working with.  
i think i understand what you meant by projected...

**Comment by tmcw** [comment]
These would need coordinate references to be positioned on the map - otherwise there's no telling where they are in the world and how big they are versus geographical coordinates.

**Comment by tmcw** [comment]
Going to do this with a known georeferenced image, as in the leaflet docs: http://leafletjs.com/reference.html#imageoverlay

**Comment by tmcw** [comment]
https://www.mapbox.com/mapbox.js/example/v1.0.0/imageoverlay-georeferenced/
