### ISSUE TITLE
example: detailed choropleth with details on hover

### ISSUE THREAD

**Issue by iandees** [mapbox/mapbox.js#761]
Thanks for using Census Reporter on [this example](https://www.mapbox.com/mapbox.js/example/v1.0.0/choropleth-joined-data-multiple-variables/), @tmcw. I'd love to see an example like that one, but using geometries that are more complicated than a single geojson allows, requiring a vector+utfgrid tileset.

Now that I type that out, though, it sounds more like a Tilemill example than a Mapbox.js example...

**Comment by tmcw** [comment]
> a vector+utfgrid tileset

I'm not sure what this would be... you mean like rclark's example of geojson embedded in utfgrid?

**Comment by iandees** [comment]
Yea, I think that's what I am thinking about.

**Comment by tmcw** [comment]
Hm. I'd rather stall on that. People tend to be confused enough about what is utfgrid/raster/hoverable/canvas/svg/leaflet/geojson that we should just punt on trying to make any more compromises until the vector future is real.
