### ISSUE TITLE
Markers not showing up in PhoneGap/Xcode Simulator (and probably device)

### ISSUE THREAD

**Issue by cappelaere** [mapbox/mapbox.js#762]
mapbox.js 1.6.2
Runs fine in Browser.  But when running in xcode simulator for IOS (the one I am using right now), image markers are not found (question mark).  Using Safari Web Inspector, I see this:
<img src='//api.tiles.mapbox.com/mapbox.js/v1.6.2/images/marker-icon-2x.png'...
Problem disappears when adding protocol "http:"
Thanks,
Pat.

**Comment by tmcw** [comment]
[PhoneGap doesn't play well with protocol relative urls](http://stackoverflow.com/questions/17620882/application-error-on-android-cordova-phonegap-application). We might want to start advertising just the HTTPS url, but not sure about what effect this will have on mixed-content HTTP

**Comment by tmcw** [comment]
Closing: use http.
