### ISSUE TITLE
Geocoder duplicate and missing results

### ISSUE THREAD

**Issue by notflip** [mapbox/mapbox.js#765]
When using the geocoder, When i search for a city, it returns a street in that city, not the city itself. And some streets are shown multiple times.. ( see screenshot )

You can see an example if i query for 'drongen' a city, it returns an address
http://api.tiles.mapbox.com/v3/notflip.hojkfi0h/geocode/drongen.json

![mb](https://cloud.githubusercontent.com/assets/4146384/3019678/655c0962-df95-11e3-979b-671da45d4a53.jpg)

**Comment by tmcw** [comment]
This would be at the API level, rather than Mapbox.js's interface - cc @yhahn

**Comment by notflip** [comment]
Aha sorry. Can this be moved or do i recreate it?

**Comment by yhahn** [comment]
@notflip can you make a ticket in https://github.com/mapbox/carmen/issues

In particular, what city are you searching for in this case?

**Comment by notflip** [comment]
The city is called 'drongen' Thank you
