### ISSUE TITLE
Example with Torque

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#768]
This is possible, but seems a little sprawly, torque is more complex than one might hope.

**Comment by javisantana** [comment]
If you need help with this...

**Comment by tmcw** [comment]
It doesn't look like there's a cdn-hosted version of torque, or one concated with carto? Mapbox.js examples have moved to only using hosted libraries, so that copy & paste works

**Comment by javisantana** [comment]
http://libs.cartocdn.com/torque.full.js (carto included)

if you want to point to a fixed version: 

http://libs.cartocdn.com/torque.js/2.4.0/torque.full.js

**Comment by tmcw** [comment]
Cool, I'll queue this up. Is there a cartodb table I can hit for a demo?

**Comment by javisantana** [comment]
we use the navy one used in this article: http://www.theguardian.com/news/datablog/interactive/2012/oct/01/first-world-war-royal-navy-ships-mapped

the leaflet example using it is: https://github.com/CartoDB/torque/blob/master/examples/navy_leaflet.html

we use that for our examples and it's located in a "examples server" so it will not change.

**Comment by tmcw** [comment]
> http://libs.cartocdn.com/torque.full.js (carto included)

Ah, that isn't going to work - mapbox.js examples are https-only and https://libs.cartocdn.com/torque.full.js isn't valid

**Comment by javisantana** [comment]
https://cartodb-libs.global.ssl.fastly.net/torque.full.js

is the host we use for https

**Comment by tmcw** [comment]
https://www.mapbox.com/mapbox.js/example/v1.0.0/torque-temporal-data/
