### ISSUE TITLE
Space to account for `.leaflet-popup-close-button`

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#770]
![](http://cl.ly/VfNE/Screen%20Shot%202014-05-22%20at%2012.05.27%20PM.png)

**Comment by tristen** [comment]
Another option is to remove the close button completely? It should behave the same way as the standard popup.

**Comment by tmcw** [comment]
> Another option is to remove the close button completely?

Let's not do that. Mapbox.js should not significantly change default Leaflet functionality, especially not disabling it at a CSS level.
