### ISSUE TITLE
https://www.mapbox.com/mapbox.js/example/ 404s

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox.js#771]
https://www.mapbox.com/mapbox.js/example/ 404s

This should redirect https://www.mapbox.com/mapbox.js/example/v1.0.0/ or to the latest examples.

**Comment by tmcw** [comment]
Are there any links to this page?

**Comment by bsudekum** [comment]
Not that I know of. From a usability stand point it makes sense though, no?

**Comment by tmcw** [comment]
I don't think so. Nice to have, but not a priority.
