### ISSUE TITLE
Directions API example

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox.js#782]
showing results of Directions API call.

edit: ...or wait for official release?

**Comment by tmcw** [comment]
> wait for official release?

This one

**Comment by tmcw** [comment]
Done: https://www.mapbox.com/mapbox.js/example/v1.0.0/mapbox-directions/

**Comment by wboykinm** [comment]
Am I missing something that this example isn't working on the mapbox page? Official release required?
![directions](https://cloud.githubusercontent.com/assets/735463/4154654/8de48bde-3463-11e4-86f3-00efed88272d.gif)

**Comment by tmcw** [comment]
Currently only works by placing waypoints by clicking the map, rather than entering in text.

**Comment by wboykinm** [comment]
AHA. Dope.

**Comment by tmcw** [comment]
This is definitely very "work in progress", this is just getting it out in the open :)

**Comment by wboykinm** [comment]
Can't wait to see what this looks like a few days after launch:

https://github.com/mapbox/mapbox.js/labels/whyaremydirectionsweird

**Comment by rajapulau** [comment]
i use code in example
https://www.mapbox.com/mapbox.js/example/v1.0.0/mapbox-directions/ 

i have error 
GET https://api.tiles.mapbox.com/v4/directions/mapbox.driving/110.3472375869751…token=pk.eyJ1IjoicmFqYXB1bGF1IiwiYSI6IkFtdzYtanMifQ.kjDE091qu3CQPFnPkUxDGA 400 (Bad Request) 

{"message":"Feature not enabled"}

**Comment by rajapulau** [comment]
how to make Waypoint not using click ... but manual coordinat input and enter.. how i change this function?

**Comment by DanielAguirre** [comment]
The directions can be localized in other languages?

**Comment by tonyspiro** [comment]
It this ready for release yet?  I'm getting "GET https://api.tiles.mapbox.com/v4/directions/mapbox.driving/-74.9789428710937…token=pk.eyJ1IjoiZGFubnl0NDc0IiwiYSI6IlF2UHFxMzgifQ.BFqY_Hcjv-OFeIZl9FHTfw 400 (Bad Request)"

**Comment by achalnexus** [comment]
I have try this code but i have clear direction rout , Origin and Destination using GL-Mapbox.
 What i to do.?
