### ISSUE TITLE
Show markers _as_ labels

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#786]
Weirdly common question - people want labels that show all the time.

**Comment by wboykinm** [comment]
[The](http://resources.arcgis.com/en/help/main/10.1/index.html#//00s800000026000000) [legacy](http://gis.stackexchange.com/questions/26702/how-to-place-elevation-numbers-on-contours-with-uphill-orientation-and-position) of [GIS](http://docs.autodesk.com/CIV3D/2013/ENU/index.html?url=filesCUG/GUID-0F9ADC32-F54E-4BC3-87EC-9E3BF2DC0DD0.htm,topicNumber=CUGd30e85884) . . .
