### ISSUE TITLE
Blurry image when browser default zoom is larger than 100%

### ISSUE THREAD

**Issue by lordaugustus** [mapbox/mapbox.js#787]
For example in higher resolution laptop screen, many would change the default zoom ratio to say 125%. This would lead to blurry map as the tile images are also zoomed.

**Comment by tmcw** [comment]
This is the same behavior as the core library, [Leaflet](http://leafletjs.com/), and the same as any image in a webpage when your browser is zoomed - the only real way to fix this is to not use browser zoom, and change your screen resolution if necessary.
