### ISSUE TITLE
maxzoom is sometimes being set as 18 when it shouldn't be

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#79]
In this example: http://mapbox.com/mapbox.js/example/geolocation/ maxzoom is 18 and should be 17.

I'm not sure that this code should only set max/minzoom when bounds are present: https://github.com/mapbox/mapbox.js/blob/master/src/layer.js#L64

**Comment by ansis** [comment]
Zoom range is never automatically set on the map. If it did, how would it handle multiple layers with different layers? We had this code before but it was removed. The code you linked sets the tile limits (and does so correctly in your example).
