### ISSUE TITLE
Remove/deprecate HTTP_URLS / HTTPS_URLS configurability

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#791]
As a public API, these are misleading: only the first URL in the array is ever used.

They also complicate questions of backward compatibility. E.g., when we release a version of Mapbox.js that uses Mapbox API version v4 and API keys, do we continue to support setting these to `['http[s]://a.tiles.mapbox.com/v3/']`? Other values?

**Comment by tmcw** [comment]
:+1: we should switch from an array to a single entry.

I do think these should still be configurable, though - it's useful for staging, mocking and if people want to build their own mapboxen.

> E.g., when we release a version of Mapbox.js that uses Mapbox API version v4 and API keys, do we continue to support setting these to ['http[s]://a.tiles.mapbox.com/v3/']?

I imagined that we would always release a new version of mapbox.js when we release a new api version, and it would have a different default endpoint.

**Comment by jfirebaugh** [comment]
Cool, doing that in v4 branch.
