### ISSUE TITLE
v4 @2x handling

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox.js#792]
@jfirebaugh OTOH when using the Mapbox v4 api mapbox.js can:
- Drop all handling/logic around the `autoscale` flag in tilejson,
- Leave the 256 virtual pixel (DOM) image size alone,
- Append the `@2x` suffix to tile URLs when `window.devicePixelRatio` says so.

The _only_ thing that needs to change when on a retina screen is using the `@2x` suffix.

cc @tmcw

**Comment by jfirebaugh** [comment]
Do we want to continue to support [TileLayer `retinaVersion` option](https://www.mapbox.com/mapbox.js/api/v1.6.3/l-mapbox-tilelayer/)?

Do we want to support turning the default autodetection off, via `{detectRetina: false}`?

**Comment by yhahn** [comment]
Per convo, both of these options will be dropped as they amount to hacks/stopgap solutions.

**Comment by willwhite** [comment]
Done with a5ac82a61e9fea46d5057499e0fbc408d975c904 ?

**Comment by jfirebaugh** [comment]
Yes

**Comment by seb-thomas** [comment]
Hey guys, will you be doing an example or docs about how to use retina tiles in v2.0?
We're using mapbox.js with our own, non-mb tiles, and using a separate tileset rather than getting tiles from the next zoom level like Leaflet does is really important to us as our map changes drastically between zoom levels. 

thanks.

**Comment by tmcw** [comment]
Yeah, reopening - this needs better documentation and examples.

**Comment by seb-thomas** [comment]
Hey @tmcw Sorry to bother you, any progress with this?

**Comment by jfirebaugh** [comment]
@tmcw are you looking for a sentence somewhere that says "On retina screens, retina (@2x) tiles will be used automatically?" That's basically all that retina support amounts to. Mapbox.js 2.0 does not support `autoscale`, `detectRetina: false`, getting tiles from the next zoom level, or other retina-related things, and per usual convention, we do not document everything not supported. The differences between 1.x and 2.x, retina-wise, is documented [here](https://www.mapbox.com/mapbox.js/api/v2.1.4/upgrading-from-mapbox-js-v1/).

@sebastianthomas If you are using your own tileset, your best bet is to use `L.TileLayer` directly and customize it to the specifics of your tileset. `L.mapbox.tileLayer` will always be optimized for Mapbox tile conventions (i.e. `@2x` tiles are always available and used unconditionally on retina).

**Comment by seb-thomas** [comment]
@jfirebaugh OK, thanks. 
I guess the documentation should then read "retina tiles will be used automatically when using a Mapbox tileset".

**Comment by jfirebaugh** [comment]
@joaodoria Sounds like a different issue, can you open a separate ticket, and include the exact URLs?

**Comment by joaodoria** [comment]
@jfirebaugh sure! Just deleted the comment here and opened a new one. Thanks!

**Comment by jfirebaugh** [comment]
⇢ #918
