### ISSUE TITLE
Handling protocol-relative vs IE vs

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#795]
:crying_cat_face:

So:
- Protocol relative URLs do not work with PhoneGap, because it uses non-http or https urls.
- Protocol relative URLs do not work with people who open HTML files in browsers without local servers

But
- Hardcoding HTTPS could break IE's fragile `XDomainRequest` system we use for XHR.

---

Thus: we either need instructions for PhoneGap/people who open HTML files, or need to test IE + XHR with all-HTTPS resources even on mixed pages.

**Comment by jfirebaugh** [comment]
Something like [this](https://github.com/mapbox/mapbox.js/compare/protocols) would prevent IE breaking in cross-protocol scenarios.

It makes protocol-relative XHR requests work for PhoneGap/`file://`, but of course `<script src='//a.tiles...'` and the like will still fail. I guess maybe we just always use https in docs/examples?

**Comment by tmcw** [comment]
@jfirebaugh's fix fixes this.
