### ISSUE TITLE
natural earth for the web set

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#796]
:full_moon_with_face:

I have a dream of a website that's like [Natural Earth](http://www.naturalearthdata.com/) except it serves [GeoJSON](http://geojson.org/), pre-simplified to rational browser sizes. So, the basics like:
- US States
- Countries
- ZCTAs
- Congressional Districts

So, like [us-atlas](https://github.com/mbostock/us-atlas) except GeoJSON-focused, not TopoJSON, you don't need to run a makefile, you can just download them, [properties are included](https://github.com/mbostock/us-atlas/issues/14), and they are simplified to rational sizes.

Thoughts? @ajashton @mourner ?

**Comment by wboykinm** [comment]
Not to be confused with @nvkelso's [version](https://github.com/nvkelso/natural-earth-vector/tree/master/geojson)? I mean there are obvious limitations on size coming from github, but you might test there . . .

**Comment by tmcw** [comment]
Basically picking up the torch from that version, yeah - making that easily downloadable and tuning simplification based on size rather than meters. Unfortunately it's pretty unlikely that natural-earth-vector will move much.

**Comment by nvkelso** [comment]
Tell me more...

**Comment by tmcw** [comment]
It doesn't look like `natural-earth-vectors` has been updated for a year, and isn't integrated into NaturalEarthData.com?

**Comment by nvkelso** [comment]
The natural-earth-vectors repo is integrated into NaturalEarthData.com.

I'm confused why this is being forked instead of maintained directly?

**Comment by tmcw** [comment]
Huh - maybe I'm missing the part of the site where you can download GeoJSON? [this kind of listing page](http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/) doesn't have it...

**Comment by nvkelso** [comment]
GeoJSON are all in the GitHub repo now:

```
https://github.com/nvkelso/natural-earth-vector/tree/master/geojson
```

If they need extra or different processing, let's add it directly to the
main repo via a change to the Makefile instead of making a shadow fork,
please.

The source shapefiles are listed on individual download pages; other format
flavors are listed on the main download page:

```
http://www.naturalearthdata.com/downloads/
```

Now that GeoJSON and TopoJSON are well established, those can be provided
there as well.

**Comment by tmcw** [comment]
> Now that GeoJSON and TopoJSON are well established, those can be provided
> there as well.

Cool: that's what I'm looking for, basically: previewing and downloading GeoJSON of useful size for Leaflet, without doing the GitHub dance. I'd PR it but the .com is a WP site.

**Comment by tmcw** [comment]
@nvkelso any plans on exposing GeoJSON more prominently on NaturalEarthData.com?

**Comment by wboykinm** [comment]
O_o https://github.com/tmcw/geojson-xyz

**Comment by tmcw** [comment]
-> https://github.com/tmcw/geojson-xyz
