### ISSUE TITLE
Doesn't play well with RequireJS

### ISSUE THREAD

**Issue by benwatts** [mapbox/mapbox.js#80]
O hai there! I'm trying to get the js api working with an app that also uses RequireJS, but it's currently dying an agonizing death. Seems as though bean never gets defined. Ack. Trying to load the api via a normal script tag outside of RequireJS (which might be feasible in my situation) also breaks as a result of [this RequireJS-related error](http://requirejs.org/docs/errors.html#mismatch). Any thoughts?

I'm reproducing the issue with the following ( http://jsfiddle.net/3qUTd/ ): 

``` html
<div id="map" style="width: 500px; height: 500px; background: #eee;"></div>
<script src="http://cdnjs.cloudflare.com/ajax/libs/require.js/2.0.2/require.min.js"></script>
<script>
require(["http://api.tiles.mapbox.com/mapbox.js/v0.6.2/mapbox.js"], function(util) {
  map = mapbox.map('map');
  map.addLayer(mapbox.layer().id('examples.map-vyofok3q')).zoom(5).center({lat:26, lon:-77});
});
</script>
```

**Comment by tmcw** [comment]
Yeah, we've seen errors with RequireJS. This is basically out of our control, though - [bean is a contrib project](https://github.com/fat/bean) and kind of has its own way of doing things.

Without buying into RequireJS hard, is there any way to fix this?

**Comment by benwatts** [comment]
Ho'k so, I think the problem is that Bean is set up to use this [async module stuff](http://requirejs.org/docs/whyamd.html). So if Bean is loaded via RequireJS, Bean will expect other modules to define it as a dependency. Bean will only be made available to those modules that require it. I guess it is never attached to the window object. At least, _I think_ that's what's happening. _Boourns._

Shitty solution? Deleting [this line](https://github.com/mapbox/mapbox.js/blob/master/dist/dev/mapbox.uncompressed.js#L12) makes the problem go away. :/ but obviously that won't do. **Oh... balls**. As it turns out, this same problem will also affect [Reqwest](https://github.com/ded/reqwest/blob/master/reqwest.js#L9).

I'm assuming the only way around it would involve modularizing code that depends on Bean+Reqwest? Tbh, that goes above my head. Most of this does. There's _got_ to be a simpler way, though. This seems _really_ silly.

**Comment by ansis** [comment]
If you want to use mapbox.js without loading it through require.js just include it as a normal script tag **before** including require.js. If require.js hasn't been loaded, bean and reqwest won't use the amd stuff.

I'm looking into what it would take to make mapbox.js compatible with require.js

**Comment by benwatts** [comment]
I'm face-palming so hard right now, I fail. Thanks for pointing that out.

**Comment by ansis** [comment]
We've also handled this in 1a69825ca1541b1345227781003d99acc161b65a, so you should be able to include the next release wherever making your jsfiddle example work

We're not planning to add full require.js support (yet), but if you think this is important let us know

**Comment by benwatts** [comment]
You guys are wizards, thanks :D
