### ISSUE TITLE
Compress dist

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#803]
Looks like CF now supports gzip, so let's do it.

**Comment by tmcw** [comment]
> When generating HTML that links to content in CloudFront (for example, using php, asp, or jsp), evaluate whether the request from the viewer includes Accept-Encoding: gzip in the request header. If so, rewrite the corresponding link to point to the compressed object name.

GRR NOOO

**Comment by yhahn** [comment]
lol
