### ISSUE TITLE
Code blocks have too much spacing

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox.js#804]
![screen shot 2014-06-17 at 1 00 52 pm](https://cloud.githubusercontent.com/assets/58878/3303684/1e973024-f642-11e3-9968-2b6f99241633.png)

Seems to be leaflet originating documentation only. Ex. https://www.mapbox.com/mapbox.js/api/v1.6.4/l-events/

**Comment by tmcw** [comment]
We could probably do the HTML 'compact spaces' trick here, like `str.replace(/\s{2,}/ /g)`

**Comment by aaronlidman** [comment]
Fixed in https://github.com/mapbox/mapbox.js/commit/d8788b2c361fb4bd9dfe0145e26429f94e1e4e74

![screen shot 2014-06-23 at 2 44 16 pm](https://cloud.githubusercontent.com/assets/58878/3362120/6ed33dd0-fb06-11e3-9ec2-e0b632677d03.png)
