### ISSUE TITLE
v4 support

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox.js#806]
Roundup ticket tracking remaining actions for a beta release that supports v4 web services API.

Looks like a lot is complete in the [v4 branch](https://github.com/mapbox/mapbox.js/commits/v4).
- [x] API keys
- [x] Pull jsonp
- [x] Retina #792 
- [x] www.mapbox.com integration https://github.com/mapbox/www.mapbox.com/pull/4205
- [x] Embed user's API token in examples

What else do we need to hit?

/cc @jfirebaugh @yhahn

**Comment by jfirebaugh** [comment]
Working on a beta release and mapbox.com integration today.
