### ISSUE TITLE
Hosting extensions

### ISSUE THREAD

**Issue by dhcole** [mapbox/mapbox.js#81]
@tmcw how do you want to handle hosting things like this: https://github.com/mapbox/mapbox.js/blob/master/extensions/mapbox.converters.googledocs.js

**Comment by tmcw** [comment]
They'll live under

   http://api.tiles.mapbox.com/mapbox.js/v0.6.2/extensions/*.js

**Comment by ansis** [comment]
So they'll be versioned together with the core mapbox.js? Would changes in extensions affect mapbox.js versions?

**Comment by tmcw** [comment]
Versioned in-step with mapbox.js. extensions version == mapbox.js version.

**Comment by ansis** [comment]
Would, for example, a backwards incompatible extension trigger a new mapbox.js version?

**Comment by tmcw** [comment]
Yes; versions can be like
- Extensions: lots of changes
- MapBox.js no changes

**Comment by tmcw** [comment]
Closing; different approach in v1
