### ISSUE TITLE
'Displaying WMS layers' example NOAA source broken

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox.js#810]
The temperature toggle in [Displaying WMS layers](https://www.mapbox.com/mapbox.js/example/v1.0.0/wms/) doesn't do anything right now -- seems like there's an issue with the NOAA source?

**Comment by tmcw** [comment]
Sigh, this is the Last Remaining WMS Server On The Internet That We Can Rely On®. Will have to look for alternatives if it's starting to crumble.

**Comment by jfirebaugh** [comment]
It seems to go up and down, see #529.

**Comment by lbud** [comment]
it's baaa-aaaack

What is happening with the green is beyond me (green = hot, green = cold...?) but hey.

**Comment by tmcw** [comment]
the rainbow colored thing is america `¯\_(ツ)_/¯`
