### ISSUE TITLE
GeoJSON Marker from Github example broken

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox.js#811]
[GeoJSON Marker from Github](https://www.mapbox.com/mapbox.js/example/v1.0.0/geojson-marker-from-remote-url/) looks like it should do more and is unhappy? 

> XMLHttpRequest cannot load https://api.github.com/repos/mapbox/mapbox.js/contents/test/manual/example.geojson?_=1403572733743. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'https://www.mapbox.com' is therefore not allowed access.

**Comment by jfirebaugh** [comment]
Adding `xhrFields: { withCredentials: false }` to the `$.ajax` options will probably fix this.
