### ISSUE TITLE
Help with Opacity control

### ISSUE THREAD

**Issue by aborruso** [mapbox/mapbox.js#812]
Hi,
I have seen your opacity control example page (https://www.mapbox.com/mapbox.js/example/v1.0.0/opacity/) and I would like to modify it, and to start with the slider at its minimum (nearby full transparency ).

I have tried to change the code, but I'm not able to to do it.

Thank you

**Comment by tmcw** [comment]
Please contact support at support@mapbox.com - this issue tracker is for bugs & potential features.

**Comment by aborruso** [comment]
You are right, I'm very sorry. Thank you very much
