### ISSUE TITLE
/v4/ tests need to handle https

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#819]
![2014-07-02 at 6 10 pm](https://cloud.githubusercontent.com/assets/32314/3463112/c1853ce6-0235-11e4-925c-47cbbcce2fe6.png)

some test servers will run on https.

**Comment by jfirebaugh** [comment]
There are failures related to https/http mismatch on mb-pages as well -- we've got some work to do if this is a test environment we want to support.

**Comment by tmcw** [comment]
Closing - this is not a test environment we should support.
