### ISSUE TITLE
"Uncaught TypeError: Cannot read property '0' of undefined" when using Geocoder

### ISSUE THREAD

**Issue by muan** [mapbox/mapbox.js#821]
Hi. :wave:

`L.mapbox.geocoder(id).query('wherever', function(err, obj) {})` triggers 
`Uncaught TypeError: Cannot read property '0' of undefined` in mapbox.js(v1.6.4).

I can't get into the callback to catch the error since it errors before that.

I found 3 strings that trigger the same error: `wherever`, `ひよし`, `LCY`. Looks like the location is just not found... Thoughts? :grimacing:

**Comment by muan** [comment]
Just tried with `v1.3.1` and it works fine. EDIT: all fine until `v1.6.3`.

**Comment by tmcw** [comment]
Ah, this may be related to a format change in geocoding, will check it out. Thx for reporting!

**Comment by jfirebaugh** [comment]
This is fixed in Mapbox.js 2.x.
