### ISSUE TITLE
v2.0.0 status

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#832]
@jfirebaugh seeing some support volume come in about v2.0.0 - it's what you get if you `npm install mapbox.js`, and the switched version on mapbox.com is creating some [dead links](https://www.mapbox.com/help/set-map-position/) to non-existent docs wherever we use `{{mapboxjs-version}}` or similar. What's the best strategy here?

**Comment by jfirebaugh** [comment]
2.0 is live.
