### ISSUE TITLE
geocoder.query returns a 404

### ISSUE THREAD

**Issue by Anahkiasen** [mapbox/mapbox.js#833]
I was using 1.6.\* of Mapbox until recently, I'm trying to setup 2.0 but I'm encountering a problem when it comes to Geocoding, here is my code:

``` js
L.mapbox.accessToken = 'myToken';

var geocoder = L.mapbox.geocoder(key);
var map = L.mapbox.map('map', key);

geocoder.query('France', function (errors, data) {

});
```

Pretty straightforward stuff, but when the function is actually called, although it properly pings `http://a.tiles.mapbox.com/v4/geocode/maximefabre.ibf3ciod/France.json?access_token=myToken` I get the following response:

``` json
{"message":"Not Found"}
```

Anything changed in the way geocoding works in 2.0 that I need to update?

**Comment by jfirebaugh** [comment]
Hi @Anahkiasen. You are correct that there was a change in 2.0, namely that the geocoder now uses the [v4 geocoding API](https://www.mapbox.com/developers/api/geocoding/), which no longer accepts arbitrary map ids. Instead, you can use one of the predefined geocoding indexes. The one that gives you the same data as before is `mapbox.places-v1`. So try the following:

```
L.mapbox.accessToken = 'myToken';

var geocoder = L.mapbox.geocoder('mapbox.places-v1');
geocoder.query('France', function (errors, data) {

});
```

I will update the documentation for `L.mapbox.geocoder` and mention this change in the [upgrade notes](https://www.mapbox.com/mapbox.js/api/v2.0.0/upgrading-from-mapbox-js-v1/).

Note that in 2.0 the format of geocoding results has also changed (they are now GeoJSON). You might need to update your code to handle this change as well.

**Comment by Anahkiasen** [comment]
Ok good to know, I looked in the docs and examples indeed but didn't find any. Didn't know about the upgrade notes either. Changes in the data structure don't bother me, it's expected for a 2.0 release. Guess this can be closed then.
