### ISSUE TITLE
"Error: An API access token is required to use Mapbox.js" - 2.0.0

### ISSUE THREAD

**Issue by 84564221** [mapbox/mapbox.js#834]
deleted

**Comment by jfirebaugh** [comment]
Sorry about that. The correct URL is: https://www.mapbox.com/mapbox.js/api/v2.0.0/api-access-tokens/

You may also want to look over https://www.mapbox.com/mapbox.js/api/v2.0.0/upgrading-from-mapbox-js-v1/
