### ISSUE TITLE
Creating Mapbox.js objects with accessToken does not work (2.0.0)

### ISSUE THREAD

**Issue by 84564221** [mapbox/mapbox.js#835]
You can create Mapbox.js objects with the `accessToken` option parameter.

``` javascript
 var map = L.mapbox.map('map', 'examples.map-8ced9urs', {
   minZoom: 5,
   maxZoom: 9,
   maxBounds: [[42.311109, -4.156986], [49.101366, 22.193721]],
   accessToken: '<your access token>'
 });
```

This does not work. However, you need to set `L.mapbox.accessToken = '<your access token>';`.

![321331](https://cloud.githubusercontent.com/assets/812964/3770060/5654d810-18e6-11e4-9b60-c12daf1c40e1.png)

Reference: https://www.mapbox.com/mapbox.js/api/v2.0.0/api-access-tokens/

**Comment by jfirebaugh** [comment]
You are replacing the string `'<your access token>'` with your actual access token, right?

This example code works as expected when I provide my access token. Could you be more specific about what doesn't work?

**Comment by jfirebaugh** [comment]
Can you please provide the complete code? If you prefer not to post it publicly, you can contact help@mapbox.com and I can assist you there.

**Comment by jfirebaugh** [comment]
Well, that's still not the complete code -- it has references to `this.model.get('position')`. But I substituted fixed coordinates there and can see what the issue is. If you are not setting the global `L.mapbox.accessToken`, you need to supply an access token to `L.mapbox.featureLayer` as well, so it can load icons from the marker API.

```
var mapFeatureLayer = L.mapbox.featureLayer({
    type: 'FeatureCollection',
    features: features,
    accessToken: '<your access token>'
}).addTo(map);
```

**Comment by jfirebaugh** [comment]
Oops, that example code should be:

```
var mapFeatureLayer = L.mapbox.featureLayer({
    type: 'FeatureCollection',
    features: features
}, {
    accessToken: '<your access token>'
}).addTo(map);
```
