### ISSUE TITLE
About "List markers and pan to clicked items"

### ISSUE THREAD

**Issue by aborruso** [mapbox/mapbox.js#844]
Hi,
I have seen the code of this example https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-list-click/, but where is the source text of the makerList?

Thank you

**Comment by tmcw** [comment]
The text is automatically grabbed from the markers, which are stored in the Mapbox project used in that example: https://a.tiles.mapbox.com/v3/examples.map-zr0njcqy.html#12/38.9070/-77.0460

**Comment by aborruso** [comment]
Thank you very much
