### ISSUE TITLE
Usage with Browserify

### ISSUE THREAD

**Issue by aborruso** [mapbox/mapbox.js#849]
Hi all,
I'm testing mapbox Browserify use, and it's very useful.

Where is it possible to download mapbox.css file and all required images, useful to run properly mapbox in an own server without any external dependency?

Thank you very much,

Andrea

**Comment by tmcw** [comment]
> Where is it possible to download mapbox.css file and all required images, useful to run properly mapbox in an own server without any external dependency?

Yes, the node package includes these - you can either copy them out of the folder into your assets path, or use a route to `node_modules/mapbox.js/dist`, or use something like `brfs` to bring out the CSS.
