### ISSUE TITLE
Support arbitrary domains for compositing, or add fallback

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox.js#85]
Needed for testing local tile hosts.

@willwhite

**Comment by tmcw** [comment]
Arbitrary domains probably won't work; for the corner case of a testing server for MapBox Hosting, maybe we should carve out a backdoor for something like

```
mapbox.MAPBOX_URL = 'http://foo.mapbox.com/';
```

**Comment by ansis** [comment]
Sounds like the right way to handle this. Done in 936586e41278a11a9f280b99076ff514c3ed24ff

**Comment by ansis** [comment]
@willwhite does this work well enough?

**Comment by tmcw** [comment]
This looks solid, closing.

**Comment by willwhite** [comment]
Yeah this looks good. Is it available in a tag yet? [Last tag](https://github.com/mapbox/mapbox.js/tags) is v0.6.0.

**Comment by tmcw** [comment]
Hmm, there are v0.6.3 and v0.6.4 releases (and on the CDN); ansis do you have a tag for v0.6.4

**Comment by ansis** [comment]
Tags have been pushed
