### ISSUE TITLE
Should retina tiles be served when tileSize is doubled?

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox.js#859]
http://bl.ocks.org/tristen/0e9d6613138888bc09e1

**Comment by jfirebaugh** [comment]
No, let's not re-complicate how retina tiles work.

If you _really_ want to use retina tiles as if they were just regular 512 pixel tiles, you can do something like:

```
L.mapbox.tileLayer({
    tiles: ['https://a.tiles.mapbox.com/v4/mapid/{z}/{x}/{y}@2x.png?access_token=...']
}, {
    tileSize: 512
});
```
