### ISSUE TITLE
undefined TypeError due to Pinch Functionality on Ipad 

### ISSUE THREAD

**Issue by mayarichman** [mapbox/mapbox.js#86]
When a map is in between zoom levels and the user stops pinching to zoom, the console shows this incredibly vague error: 

_JavaScript: Error undefined TypeError:'\undefined' is not an object_

I believe it is due to the pinching functions rounding to the next zoom.  The error doesn't appear every time the user pinches and zooms, just when it needs to snap to a different zoom level. 

The site I tried it on was developmentseed.org/tandale with the Safari debugger.

**Comment by ansis** [comment]
Fixed in easey v2.0.3
