### ISSUE TITLE
Tile loading problem

### ISSUE THREAD

**Issue by vanhumbeecka** [mapbox/mapbox.js#861]
While trying out phonegap+jquery mobile development, i came across the following problem (testing on a physical nexus 5):
When using the following code, the map shows up OK:

``` javascript
$(document).on('pageinit', '#pagetwo', function() {
    L.mapbox.accessToken = '<myAccessToken>';
    var map = L.mapbox.map('map', 'avh.ja4hlfbf');
});
```

However, when i split the layer from the map in 2 elements, the map tiles won't load. Not even when i add the 'redraw' to the layer:

``` javascript
$(document).on('pageinit', '#pagetwo', function() {
    L.mapbox.accessToken = '<myAccessToken>';
    var map = L.mapbox.map('map');
    var layer = L.mapbox.tileLayer('avh.ja4hlfbf');
    layer.addTo(map);
    layer.redraw();
});
```

Not sure if i'm doing something wrong, or it is a bug

**Comment by tmcw** [comment]
``` js
var map = L.mapbox.map('map', 'avh.ja4hlfbf');
```

is not equivalent to

``` js
    var map = L.mapbox.map('map');
    var layer = L.mapbox.tileLayer('avh.ja4hlfbf');
```

The first form will
- Include any marker layers
- Use the tile layer's default center and zoom

The latter - using center and zoom - is what the main difference for you is. And the way to fix it (if you want to split the two) is to set a center and zoom for your map with `.setView`.
