### ISSUE TITLE
Show close button for geoJSON popups

### ISSUE THREAD

**Issue by paulmach** [mapbox/mapbox.js#862]
Basically run a `markerLayer.setGeoJSON(geoJson);` and all the popups don't have a closing 'x'. How can I make this true, or as an option. 

See https://github.com/mapbox/mapbox.js/blob/a02a9d00b1545884b74a095f8ee97228c2cd72c3/src/feature_layer.js#L103

**Comment by tmcw** [comment]
@heyitsgarrett looks like you made this call - https://github.com/mapbox/mapbox.js/commit/ef3905e8 - let's keep this as default but make it configurable?

**Comment by paulmach** [comment]
I found a work around. I switched this:

```
markerLayer.on('popupopen', function(e) {
    e.popup.setContent(_.template(tmplPopupMarkup, e.layer.feature.properties));
});
```

to

```
markerLayer.on('click', function(e) {
    e.layer.bindPopup(_.template(tmplPopupMarkup, e.layer.feature.properties)).openPopup();
});
```

That's probably the right way to do it. Feel free to close if you don't want to fix.
