### ISSUE TITLE
Don't show grid lines when zooming in and out on a map

### ISSUE THREAD

**Issue by jtcornelius** [mapbox/mapbox.js#864]
When you are zooming in and out on a map, you can see visible grid lines on the map (likely the map tile boundaries).  This detracts from the visual appeal of the zoom effect.

Desired behavior: don't show grid lines when zooming

**Comment by tmcw** [comment]
Please post a complete example (a link to a working webpage that demonstrates this issue), and let us know what browser you're using.

This isn't the observed behavior of Mapbox.js on any browsers I use and know of.

**Comment by heyitsgarrett** [comment]
Please also confirm that the zoom of your browser is 100%, not over- or under-zoomed, as that will reveal gaps between tiles.

**Comment by jtcornelius** [comment]
Wow, great response guys!

Browser = Safari 7.0.6
Browser zoom level at 100%
This can be observed on your demo site with this sample:
https://www.mapbox.com/mapbox.js/example/v1.0.0/dynamically-drawing-a-line/

you will see vertical lines (presumably from between map tiles).

Note: I cannot reproduce this in chrome

**Comment by mourner** [comment]
This was fixed in Leaflet master. Quite a bug I tell you. Hacking around it was really difficult.
