### ISSUE TITLE
Directions example weird behavior

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox.js#865]
Clearing start or beginning values from directions examples removes geometries from the map but doesn't clear the directions sidebar. This leaves user is a weird state where they can interact with the sidebar, see a marker on the map hover, but without a visible route.

This feels wrong. I would clear the sidebar when one of the values gets cleared.

**Comment by tmcw** [comment]
Can you post this [in the repo for that plugin?](https://github.com/mapbox/mapbox-directions.js)

**Comment by samanpwbb** [comment]
See https://github.com/mapbox/mapbox-directions.js/issues/51
