### ISSUE TITLE
share control -- embed URL broken

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#877]
If you click (1) you get the share control w embed URL (2). URL is missing a "/" (3).

![image](https://cloud.githubusercontent.com/assets/851894/4279714/d0999154-3d23-11e4-8b5e-86eb7169d837.png)

**Comment by pdgoodman** [comment]
@jfirebaugh I continue to see broken URLs in the share field:

![image](https://cloud.githubusercontent.com/assets/851894/4364726/02ee2f0a-42a3-11e4-8b1e-df264905231e.png)

**Comment by jfirebaugh** [comment]
@pdgoodman We haven't made a mapbox.js release (and corresponding embed updates) with this fix yet. Doing that now.

**Comment by wyattp11** [comment]
Was this ever resolved? I'm still getting broken links and also looking for the function to initialize the share popup as I'd like to assign it to my own custom button...
