### ISSUE TITLE
Legend list items no longer unstyled

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox.js#878]
Looks like your parent CSS for `<li>` elements must have changed; [the choropleth example](https://www.mapbox.com/mapbox.js/example/v1.0.0/choropleth/) has a bulleted legend:
![2014-09-17_1330](https://cloud.githubusercontent.com/assets/735463/4308208/a15f6080-3e90-11e4-87cd-58084b9e2384.png)

**Comment by jfirebaugh** [comment]
Probably was implicitly depending on base CSS prior to the [iframening](https://github.com/mapbox/mapbox.js/issues/846).
