### ISSUE TITLE
"marker-symbol: 0" not rendering

### ISSUE THREAD

**Issue by jwass** [mapbox/mapbox.js#879]
If `marker-symbol` is set to 0 as a number not a string, the icon doesn't render. 1-9 will render okay.

This affects at least geojson.io and the github renderer:
- http://geojson.io/#id=gist:anonymous/a03199684d47b524fdfd&map=5/41.722/-73.784
- https://gist.github.com/anonymous/a03199684d47b524fdfd

You can duplicate this by adding a couple of points in geojson.io, adding a 'marker-symbol' column and filling in with some integers.

I don't know the intended behavior (are strings always expected?), but I guess if 1-9 work I'd expect 0 to behave similarly.

**Comment by tmcw** [comment]
> If marker-symbol is set to 0 as a number not a string

This is something that [simplestyle-spec](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0#3-client-behavior) needs to be clearer about, we should at least strongly recommend strings.

But mapbox.js could do better https://github.com/mapbox/mapbox.js/blob/mb-pages/src/marker.js#L19
