### ISSUE TITLE
UTF grids not flipped for xyz -> tms

### ISSUE THREAD

**Issue by grovduck** [mapbox/mapbox.js#882]
I'm storing UTFGrid tiles in an MBTiles file (using mb-util) and they are being stored as TMS (similar to the corresponding image tiles).  When I specify the TileJSON for the GridLayer, I am using `"scheme": "tms"`.  In digging through the code, it looks like the logic for the TileLayer is correctly converting XYZ to TMS in Leaflet (_adjustTilePoint), but it doesn't look like the GridLayer goes through the same logic when loading tiles.  In fact, I don't think the GridLayer.options currently store the schema of the tiles.

For now, I can generate the tiles through mb-util as XYZ and it looks to work correctlly.  Is this the necessary route?  I'm using mapbox.js v2.1.2.

**Comment by tmcw** [comment]
> For now, I can generate the tiles through mb-util as XYZ and it looks to work correctlly. Is this the necessary route?

That's certainly what we'd recommend. TMS is purely a legacy scheme and we don't recommend using it for grids or images.
