### ISSUE TITLE
setFilter causing problem : Unable to change feature property after filter

### ISSUE THREAD

**Issue by apaleja** [mapbox/mapbox.js#888]
When using [setFilter](https://www.mapbox.com/mapbox.js/example/v1.0.0/markers-with-multiple-filters/) with [List Items](https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-list-click/), I am not able to change property of feature, such as [marker color change](https://www.mapbox.com/mapbox.js/example/v1.0.0/change-marker-color-click/).

This is so far, I've archived : [link](http://breaklo.com/TravelThroughItaly/)

Without change filter option, if I click on list, I am able to change property of feature to highlight it. But after changing filter Highlight does not work.

Anyone can guide me, If I am missing anything here ?

**Comment by jfirebaugh** [comment]
Hi @apaleja. `setFilter` works by removing all layers and then readding new layers that pass the filter. So you should move your `addLayerPopup` call to the `layeradd` handler (line 51) so that it gets called every time the marker layers are filtered.
