### ISSUE TITLE
Popup on marker not working on mobile devices

### ISSUE THREAD

**Issue by nicolasaiz173** [mapbox/mapbox.js#893]
I'm creating a map with Mapbox.js and I have a problem. I've added some markers to the map with a popup on each of them. Testing this on Chrome Desktop it works well, when I click the marker it shows the popup. But when I'm trying to do the same on mobile (Android and iOS) it doesn't work at all. On mobile the popup is never shown when I touch on them.

Anyone know why is this happening? And how to solve it?

Thanks

**Comment by tmcw** [comment]
Can provide specific code and a working example?

**Comment by nicolasaiz173** [comment]
Thanks @tmcw 
I've sended you an email with some credentials.

**Comment by nicolasaiz173** [comment]
Ok, I created this [Fiddle](http://jsfiddle.net/nicolasaiz173/3ap4ge9n/) with the same code I have on my project. The weird thing is that the Fiddle works on mobile but the map on my project does not. The only difference is that in my app I'm using the Ionic framework with AngularJS.

There is a known issue related with Mapbox and Angular.JS?

**Comment by tmcw** [comment]
Angular.js tends to cause many problems in many different ways. Unless you can provide an example of this actually working/not working in a jsFiddle, we won't be able to debug it.

**Comment by ghost** [comment]
If you haven't fixed this yet, try adding data-tap-disabled="true" on your map div

**Comment by ghost** [comment]
For me, I needed to put this attribute on a div wrapping my map div.  Thanks!

**Comment by ghost** [comment]
It also appears iOS devices need a relatively large marker to register a click.  I changed from a marker size of 15x15 px to 50x50 px to have marker click events fire consistently.

**Comment by tnoulas** [comment]
Hi @tessaalexander-uob, 

Could you please provide an example on how you did this div thing? Sounds like you have worked a solution the problem!

**Comment by ghost** [comment]
The working example can be seen here: https://www.charlemagne-icon.ac.uk/trail/claverley-church-trail/

Here is the CSS for map markers I used:

```
.marker {
    background-image: url('https://www.charlemagne-icon.ac.uk/wp-content/themes/charlemagne/images/marker-15.svg');
    background-position: center;
    background-repeat: no-repeat;
    width: 50px;  /* iOS devices need a larger click surface */
    height: 50px; /* iOS devices need a larger click surface */
    cursor: pointer;
  }
```

NB: In the JS I use to create markers I also assign the CSS class name "marker":

`el.className = 'marker';`

**Comment by webdevb** [comment]
This helped me @ghost

> The working example can be seen here: https://www.charlemagne-icon.ac.uk/trail/claverley-church-trail/
> 
> Here is the CSS for map markers I used:
> 
> ```
> .marker {
>     background-image: url('https://www.charlemagne-icon.ac.uk/wp-content/themes/charlemagne/images/marker-15.svg');
>     background-position: center;
>     background-repeat: no-repeat;
>     width: 50px;  /* iOS devices need a larger click surface */
>     height: 50px; /* iOS devices need a larger click surface */
>     cursor: pointer;
>   }
> ```
> NB: In the JS I use to create markers I also assign the CSS class name "marker":
> 
> `el.className = 'marker';`

This fixed my issue!!

**Comment by austindetzel** [comment]
Hey guys, I'm having the issue now too. I tried all the above suggestions with no luck, all the html and js can be found on app.greatlakespwc.org and viewing the script Thanks!!

**Comment by mach1media** [comment]
This worked for me:

```
// create a DOM element for the marker
var el = document.createElement('div');

// give it a class name for styling purposes
el.className = 'c-gmap__marker';

// give it a unique ID
el.setAttribute("id", "marker_1");

// create the marker using the element just created
var marker_1 = new mapboxgl.Marker({element: el, color: '#404946'})
	.setPopup(
		new mapboxgl.Popup({anchor:'bottom'}).setHTML('...')
	)
	.setLngLat([XXX,YYY])
	.addTo(map);

// attach touch event to marker so it works on mobile
$('#marker_1').on('touchend', function(){ 
	
	// Check if there is already a popup on the map and if so, remove it
	$('.mapboxgl-popup').remove();
	
	// toggle its popup
	marker_1.togglePopup();
});
```

**Comment by cby016** [comment]
It seems adding drawing controls to a map will also disable the marker popups on iOS.  After I removed the drawing controls, the marker popups started working.

**Comment by ydrea** [comment]
> Hey guys, I'm having the issue now too. I tried all the above suggestions with no luck, all the html and js can be found on app.greatlakespwc.org and viewing the script Thanks!!

+1
