### ISSUE TITLE
Consider Adding New Popup Positioning option

### ISSUE THREAD

**Issue by 1parkplace** [mapbox/mapbox.js#895]
Other mapping solutions like Google and Bing for instance allow the popup (when clicked) to calculate a position that keeps it in the map, rather Mapbox only has support for either forcing the map to pan or having the popup load outside the visible frame, making the user pan to see it.

For many of us, having the popup pan the map creates a bad experience for our end-users, turning off panning creates an even worse experience.

Is there a solution out there that does this already and I'm just missing it?  If not - it would be a GREAT and welcome modification!

Thanks!

**Comment by tmcw** [comment]
Yes, you can use [Rrose](http://erictheise.github.io/rrose/) for more fancy popup behavior.
