### ISSUE TITLE
Zoom Control not styled correctly in IE8

### ISSUE THREAD

**Issue by nwp** [mapbox/mapbox.js#897]
![jira-capture-screenshot-20141015-163213-687](https://cloud.githubusercontent.com/assets/16463/4681823/690f4cde-5616-11e4-878c-e001dda02fbd.png)

**Comment by tristen** [comment]
@tmcw Are we supporting IE8?

@nwp I'd suggest adding a IE8 targeted stylesheet with the following CSS: https://gist.github.com/tristen/2818807c8c1dc9498753

**Comment by tmcw** [comment]
@tristen yes, see the [third bullet point](https://www.mapbox.com/mapbox.js/api/v2.1.2/)

**Comment by nwp** [comment]
I would submit that supporting IE8, which sucks BTW (I want to acknowledge that fact), means out of the box. Thus, it shouldn't require that Mapbox consumers use targeted stylesheets as suggested.

**Comment by nwp** [comment]
When an issue is closed does that mean that it's deployed to production and that we should see it in our consuming apps? (We haven't tested yet, but just wanted to makes sure our expectations are correct.)

**Comment by tristen** [comment]
Hey @nwp -- this will be packaged in a new version of mapbox.js. The bug has been addressed but it's not deployed yet.

**Comment by nwp** [comment]
Is there any particular mechanism to determine when new versions have been deployed?

**Comment by tristen** [comment]
@nwp Just https://mapbox.com/mapbox.js. fyi a new version is ready: https://www.mapbox.com/mapbox.js/api/v2.1.3/
