### ISSUE TITLE
worldCopyJump markers not displaying

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox.js#902]
https://www.mapbox.com/mapbox.js/example/v1.0.0/worldcopyjump/
![image](https://cloud.githubusercontent.com/assets/3170312/4744629/c2fc581c-5a31-11e4-83f6-eb8bae5c40dd.png)

**Comment by tristen** [comment]
Hrm. So any example that uses L.marker ...

The src attributes are pointed at https://api.tiles.mapbox.com/mapbox.js/v2.2.0/images/marker-icon-2x.png when it should be https://api.tiles.mapbox.com/mapbox.js/v2.1.3/images/marker-icon-2x.png Note the `v2.2.0` difference in the path which is reflective an earlier [un-merged branch](https://github.com/mapbox/mapbox.js/pull/899). 

I re-ran make and re-deployed `v2.1.3` but it looks like its still pointing at the wrong src. Also awk'ing over the entire project shows no mention of `v2.2.0`. Not sure what's up yet.

**Comment by tristen** [comment]
Alright. it looks like the CDN is just holding on to the earlier cached version. I guess the best option here is to bump the version to `v2.1.4` :baby_chick:

**Comment by tristen** [comment]
v2.1.4 is deployed.
