### ISSUE TITLE
Mapbox.js examples not working in IE9 (browserstack)

### ISSUE THREAD

**Issue by tatsvc** [mapbox/mapbox.js#904]
I was testing [this bite](https://www.mapbox.com/bites/00058/) in IE9 via Browserstack, but it was not working. So I wanted to check if the [driving directions example](https://www.mapbox.com/mapbox.js/example/v1.0.0/mapbox-directions/) was working, but turned out none of the examples is working:

![screen shot 2014-10-24 at 12 20 56 pm](https://cloud.githubusercontent.com/assets/2894119/4772791/bafcd932-5b9b-11e4-96c1-214495ac80a5.png)

![screen shot 2014-10-24 at 12 22 35 pm](https://cloud.githubusercontent.com/assets/2894119/4772792/be899fc2-5b9b-11e4-839f-ba490eb8c742.png)

cc. @tristen @jfirebaugh

**Comment by jfirebaugh** [comment]
git bisect lands on b1ad299087df2111111e5368154dfa31dda7e70b.
