### ISSUE TITLE
Handling @2x urls cross-browser

### ISSUE THREAD

**Issue by joaodoria** [mapbox/mapbox.js#905]
@jfirebaugh > Quick question: When generating the tiles through Mapbox studio, all 1x tiles work well cross-browser but the @2x ones only work well on Chrome.

When pasting the url address for each specific @2x tile on Chrome I get access to all of them individually but on Firefox and Safari I get a 404. Isn't that strange? Doesn't seem like cache-related – could it be either cookie-related, or something on the .js that is breaking the url reference or some character that needs to be escape or url construction that Safari / Firefox can't deal with but Chrome can?

*just throwing a bunch of guesses here. I see that nothing wrong happened when generating the tiles (all files are perfect and in the right location) but what I don't understand is how I paste the same url in different browsers and the result is not the same.

Try pasting this in different browsers (with retina screen / @2x device)

http://b.tiles.mapbox.com/v4/joaodoria.k295oi1j/4/3/8@2x.png?access_token=pk.eyJ1Ijoiam9hb2RvcmlhIiwiYSI6InUzWEpNVEUifQ.YDxhzwLQ_iGZ2xRnM6VLCA

Or opening this in different browsers (again with retina / @2x device)

http://dev.joaodoria.com/varanda-products

**Comment by jfirebaugh** [comment]
Yes, I see what you mean -- Firefox will not show [this tile](http://b.tiles.mapbox.com/v4/joaodoria.k295oi1j/4/3/8@2x.png?access_token=pk.eyJ1Ijoiam9hb2RvcmlhIiwiYSI6InUzWEpNVEUifQ.YDxhzwLQ_iGZ2xRnM6VLCA). Looking at the response headers, there is no `Content-Type` header, which is probably the issue. This is a bug in our tile server; we'll investigate.

**Comment by jfirebaugh** [comment]
Our tile server now serves these tiles with the correct Content-Type header.
