### ISSUE TITLE
Clicking on marker cause window to scoll in chrome 

### ISSUE THREAD

**Issue by lookuptable** [mapbox/mapbox.js#920]
Steps to reproduce:
1. Open the page https://www.mapbox.com/mapbox.js/example/v1.0.0/single-marker/ in Chrome
2. Resize the window of chrome so that the map is not 100% displayed.
3. Now click on the marker, which will cause the browser to scoll so that the whole map is fit in the current window of the browser with the mark staying unclicked.

Mapbox behaves differently when following the same steps in firefox. So I guess this looks like a bug.

**Comment by tmcw** [comment]
Would be upstream in Leaflet /cc @mourner

**Comment by tmcw** [comment]
Closing, upstream.
