### ISSUE TITLE
Mapbox freezes Chrome browser

### ISSUE THREAD

**Issue by alexeyschepin** [mapbox/mapbox.js#921]
I've just figured out that in some cases mapbox freezes Chrome browser in MacOS and Windows. However it works perfect in FireFox and Safari.
When this issue appears OS starts to lose all free memory (up to 15Gb)
I tried to profile it, but I was not able to find a bug.

**Comment by tmcw** [comment]
Can you give examples of which cases, and code that replicates the issue - that way we can debug this problem?

**Comment by heyitsgarrett** [comment]
Been seeing this too for the last week, hard to peg down specific steps. Fails silently as well.

### Specs
- Chrome OS X, Version 39.0.2171.95 (64-bit)

### Steps to reproduce:
1. Go to [sample page](https://a.tiles.mapbox.com/v4/heyitsgarrett.i03bibck/page.html?access_token=pk.eyJ1IjoiaGV5aXRzZ2FycmV0dCIsImEiOiIwdWt5ZlpjIn0.73b7Y47rgFnSD7QCNeS-zA#3/49.10/-66.27)
2. Draw bounding box (holding `SHIFT` + `click`)
3. If bounding box is certain size (arbitrary?), map freezes and requires closed + reopened tab to interact:

![bug](https://cloud.githubusercontent.com/assets/200357/5420141/196ffdbe-8207-11e4-9ebb-2ac65aaf5a07.gif)

If box is larger, it seems to work:

![bug2](https://cloud.githubusercontent.com/assets/200357/5420143/22b3d8d2-8207-11e4-9a70-bc8a2001b53c.gif)

**Comment by jfirebaugh** [comment]
@forme, @heyitsgarrett -- still seeing this on latest Chrome?

**Comment by heyitsgarrett** [comment]
No longer an issue in latest Chrome ( version 40.0.2214.111 )
