### ISSUE TITLE
Mapbox not working on IE8

### ISSUE THREAD

**Issue by nwp** [mapbox/mapbox.js#926]
Our QA team noticed today that Mapbox.js is no longer working on IE8.

![jira-capture-screenshot-20141219-124348-436](https://cloud.githubusercontent.com/assets/16463/5584908/2a37549a-9061-11e4-905a-42c9be7fea58.png)

**Comment by tmcw** [comment]
Can't replicate this using a testing instance running IE8 & Windows 7

![2015-01-01 at 4 05 pm](https://cloud.githubusercontent.com/assets/32314/5593249/039d4fae-91d0-11e4-8075-5582d3a64a16.png)

**Comment by jfirebaugh** [comment]
@nwp Is this still an issue? If so can you provide any other configuration details that could help us replicate it?

**Comment by nwp** [comment]
This was an issue on our end. Apologies for the trouble. Mapbox is awesome.
