### ISSUE TITLE
Zoom Control problem  Angular (Ionic) Mapbox 

### ISSUE THREAD

**Issue by ignacionieto** [mapbox/mapbox.js#928]
Im trying to work with Angular.js and Mapbox.

The map is loaded, from Mapbox with no problem. But the Zoom Control have problems, in the browser it shows the Zoom Control, but it doesnt appear in the Android Emulator. In the browser and in the emualtor, they dont work: they cant zoom in or zoom out.

I draw another Zoom Control and it happen the same problem, both in the browser appear and both doesnt Zoom in or Zoom out. In the browser they show both zoom control and Android Emulator both Zoom Controller doesnt appear and they doesnt work.

I have try this work Mapbox with no problem outside Angular:

https://www.mapbox.com/mapbox.js/example/v1.0.0/

I also put a Map Box Slider Zoom and works perfectly btu the Zoom Control still doesnt work!

Could some one could explain me or give me a hand.
thanks in advance

Here is the code that I was working:

.controller('loa', function($scope, $ionicModal) {

  $ionicModal.fromTemplateUrl('templates/calama.html', {
    scope: $scope
  }).then(function(modal) {
    $scope.modal1 = modal;
      }, {
    animation: 'slide-in-down',
    focusFirstInput: true,
    scope: $scope
  });
  $scope.cierra1 = function() {
    $scope.modal1.hide();
  };
  $scope.mapaCalama = function() {
    $scope.modal1.show();
    L.mapbox.accessToken = 'pk.xxxxxx';
    var map = L.mapbox.map('map')
        .setView([-22.4562, -68.9249], 6
        .addLayer(L.mapbox.tileLayer('itelius.xxxxx'));
        L.mapbox.featureLayer('itelius.xxxxxx').on('ready', function(e) {
        var clusterGroup = new L.MarkerClusterGroup();
        e.target.eachLayer(function(layer) { clusterGroup.addLayer(layer); });
        map.addLayer(clusterGroup); 
        });  
    };

**Comment by ignacionieto** [comment]
I think is the CSS from leafflet. Beacuse when I put slider i wrote oter css styles tht work. I use the zoom slider from mapbox

**Comment by nicolasaiz173** [comment]
Hi @ignacionieto

Have you tried using [this](http://ionicframework.com/docs/api/page/tap/)?
I had a similar problem and I fixed with that.

Hope it works.

**Comment by ignacionieto** [comment]
thanks nicolas
finally i decide to make the prototipe only in javascript.
but it could be a posibility.
thank you very much
in
