### ISSUE TITLE
Geocoder example does not say you can always get latlng

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox.js#932]
In this example: https://www.mapbox.com/mapbox.js/example/v1.0.0/map-center-geocoding/

It says:

```
    // The geocoder can return an area, like a city, or a
    // point, like an address. Here we handle both cases,
    // by fitting the map bounds to an area or zooming to a point.
    if (data.lbounds) {
        map.fitBounds(data.lbounds);
    } else if (data.latlng) {
        map.setView([data.latlng[0], data.latlng[1]], 13);
    }
```

This is misleading as it sounds like you need to handle both cases. So if you want a `latlng` you need to get the centre of the `lbounds`.

In reality `latlon` is always set so you don't actually need to handle `lbound` in the simple case you just want a point.

**Comment by jfirebaugh** [comment]
But if it does have bounds, you want to fit the bounds, i.e. change the zoom to a level that shows the entire object. That's the reason to handle lbounds differently.

**Comment by ljbade** [comment]
@jfirebaugh but it does not make it clear that for non-map view uses of geocoder you do not need to add logic to handle `lbound`.

Perhaps a second example showing how geocoder can be used outside the context of a map view is needed.
