### ISSUE TITLE
TileLayer ignores detectRetina option

### ISSUE THREAD

**Issue by alexkorban** [mapbox/mapbox.js#933]
tile_layer.js:77 says:

```
L.Browser.retina ? this.scalePrefix : '.'
```

Instead of L.Browser.retina, it should really be checking `options.detectRetina && L.Browser.retina`.

**Comment by jfirebaugh** [comment]
This is by design: all Mapbox tilesets support `@2x` tiles, and they will always be automatically used when appropriate. See #792.

**Comment by alexkorban** [comment]
Maybe you could document this design then, so nobody wastes time on this? Your documentation says that TileLayer takes "same options as provided to L.TileLayer, with the following addition [...]".

**Comment by jfirebaugh** [comment]
Agreed, we need to document it better: #918.

**Comment by mgiraldo** [comment]
does this apply to non-mapbox layers? I'm not getting any tiles even though I specified `detectRetina:false`

**Comment by mgiraldo** [comment]
had to downgrade to `1.6.4` because `2.1.9` wouldn't let me ignore retina devices, thus showing nothing in [this map](http://mgiraldo.github.io/inspectorviz/)

**Comment by jfirebaugh** [comment]
@mgiraldo -- If you want to use non-Mapbox tiles and `detectRetina: false`, you can use `L.tileLayer` directly, with any Mapbox.js version. `L.mapbox.tileLayer` assumes the tileset follows the conventions of the Mapbox Tile API, i.e. that `@2x` tiles are always available.

**Comment by mgiraldo** [comment]
tried that and was not working. will try again tomorrow
