### ISSUE TITLE
Can't pan on Safari mobile

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox.js#934]
Can't pan this map on Safari mobile https://www.mapbox.com/blog/japan-roads/

![img_9703](https://cloud.githubusercontent.com/assets/98233/5793511/4180a090-9f14-11e4-9b9c-3a73699a319c.PNG)

**Comment by tmcw** [comment]
From the post's source:

``` js
    var map = L.mapbox.map('map', 'enf.681c99f3', {
      scrollWheelZoom: false,
      // disables dragging on mobile devices
      dragging: !('ontouchend' in document)
    }).setView([mapLocations[0].lat,mapLocations[0].lon],mapLocations[0].z);
```

Looks like this is intentional.

**Comment by samanpwbb** [comment]
If you were able to pan on this map, it would be impossible to navigate anywhere else on the page because the map would steal all touch events.

**Comment by ljbade** [comment]
Don't forget these maps can't pan with mouse on any machine with a touchscreen too! Basically Windows 8.

**Comment by heyitsgarrett** [comment]
> Don't forget these maps can't pan with mouse on any machine with a touchscreen too! Basically Windows 8.

@ljbade As the sole owner of this machine at Mapbox, it would be great if you dug in on the best way of correcting for this while still preserving the intent of the current JavaScript, which works for the majority of use cases. Squeaky wheels won't oil themselves :)

**Comment by ljbade** [comment]
@heyitsgarret are you in SF for 9 - 20 Feb or DC 23 - 27 Feb? If so we can look at this IRL since this is a physical thing.

**Comment by ljbade** [comment]
@heyitsgarrett - forgot the second t ^

**Comment by incanus** [comment]
@ljbade Is this something you can probe into a bit ahead of SF? Do you know JS at all? Want to learn? :-)

**Comment by ljbade** [comment]
@incanus sure I can have a crack at it, but last time I looked at it every complain loudly that my Chrome was "doing it wrong" in respect to mouse vs touch events :-(

**Comment by incanus** [comment]
@ljbade Ok, maybe we just drop it then? Choose your battles, etc.

**Comment by ljbade** [comment]
@incanus I would still like to try since I don't know much about JS events.
