### ISSUE TITLE
Support "tilesloaded" event for I.map

### ISSUE THREAD

**Issue by hy9be** [mapbox/mapbox.js#936]
In mapbox.js, there seems no event is implemented after the base map tiles are loaded and positioned, after a zoom or pan action. Events "viewreset" and "zoomend" are both triggered after the css transformation of the existing basemap layer, before new tiles are brought in and positioned.

I used to use google map api, and they have a "tilesloaded" event doing this job. The event is useful to interact with the new basemap tiles after user changes the zoom level or viewport.

**Comment by tmcw** [comment]
There's already [a closed upstream bug for this](https://github.com/Leaflet/Leaflet/issues/11) - let's keep this discussion in the Leaflet project, because that's where the functionality would live.
