### ISSUE TITLE
remove InfoControl in v3.0

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox.js#941]
Proposal: we should remove the InfoControl in the next major version release of Mapbox.js.

We [ended up rolling](https://github.com/mapbox/mapbox.js/issues/744) the "Improve this map" functionality into map attribution, and turned off the info control by default. At this point I don't think it's narrow potential use (as a replacement for the attribution control in extremely space-constrained layouts) justifies the additional code bulk and complexity it introduces.

cc @lxbarth @tmcw @tristen

**Comment by tristen** [comment]
:+1: might be silly but this could always be a little Leaflet plugin.

**Comment by lxbarth** [comment]
I'd be inclined, but: could info control be a responsive thing? Maps gets small -> attribution line turns into info control?

**Comment by jfirebaugh** [comment]
:+1:, responsive attribution would be a good approach.

**Comment by lxbarth** [comment]
Awesome. I love the responsive approach as it moves the decision from the developer to the library, simplifies our API and our documentation.

**Comment by tristen** [comment]
Good plan. I can cut this in a branch.
