### ISSUE TITLE
TileJSON properties not taken into account

### ISSUE THREAD

**Issue by mohsentaleb** [mapbox/mapbox.js#943]
When initializing map with a tileJSON as the source, its properties such as minzoom, bounds etc, are not reflected into map view.

You use `this.redraw();` in https://github.com/mapbox/mapbox.js/blob/mb-pages/src/tile_layer.js#L57 but apparently this method does not set `this.options` of L.TileLayer.

**Comment by jfirebaugh** [comment]
See [just above](https://github.com/mapbox/mapbox.js/blob/aa3c3d7bceb42c8da683128a254f75b1da5779dc/src/tile_layer.js#L47-L54) the line you linked for where `this.options` gets the TileJSON options.

Can you provide a JSFiddle that demonstrates the issue you are seeing?

**Comment by mohsentaleb** [comment]
@jfirebaugh yeah, I see that `this.options` is extended, but `this.redraw()` doesn't seem to take the bounds into account. The bounds I set for the tileJSON is slightly bigger than the current view, but map can be panned further.

See this example: http://jsfiddle.net/pn3Lgs8j/1/

**Comment by jfirebaugh** [comment]
As currently implemented, the [`bounds` option](http://leafletjs.com/reference.html#tilelayer-bounds) of a tile layer does not control where panning is allowed, only which tiles are loaded. If you want to limit panning, you need to use [`map.setMaxBounds()`](http://leafletjs.com/reference.html#map-setmaxbounds).

**Comment by tmcw** [comment]
Closing: use setMaxBounds to restrict panning.
