### ISSUE TITLE
Mapbox is painfully slow in mobile

### ISSUE THREAD

**Issue by kimmobrunfeldt** [mapbox/mapbox.js#947]
I switched from Google Maps to Mapbox because you have much better API and support for customizations. Thanks for the awesome work! However, Mapbox feels very slow when used from mobile compared to Google Maps.

The map tiles seem to load a bit slower in Mapbox but that's not the actual problem. The problem is that when Mapbox loads new tiles, user interactions might stop completely. It causes the overall usage to be quite annoying when you want to pinch zoom and pan into an area quickly. I setup two nearly identical demos based on the site I'm currently working on:
- http://kimmobrunfeldt.github.io/googlemaps-demo/app/
- http://kimmobrunfeldt.github.io/mapbox-demo/app/

Both work quite well in the desktop, but even then you can notice the problem with Mapbox when you zoom, and very quickly after that pan the map. The pan movement doesn't work in that scenario. In mobile the slowness is much more noticeable since the pinch zoom, pan, pinch zoom movements are so quick.

I don't know if these give any more insight but here's two videos of me pinch zooming and panning the sites with iPhone 6, iOS 8.1 Safari:
- Google Maps video: https://vimeo.com/119376466
- Mapbox video: https://vimeo.com/119376525

**Comment by jfirebaugh** [comment]
This would be upstream in Leaflet, and I see you've submitted the same issue there -- thanks! Closing here.
