### ISSUE TITLE
GeoJSON form geojson.io causes "Error: An API access token is required to use Mapbox.js."

### ISSUE THREAD

**Issue by TimJMartin** [mapbox/mapbox.js#950]
I am currently testing some of the Turf modules using data created from geojson.io, 

Linestrings and Polygons work fine but when I do the following I get the token error.

`var location = {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "properties": {},
              "geometry": {
                "type": "Point",
                "coordinates": [
                  -1.4703387022018433,
                  50.939003772527535
                ]
              }
            }
          ]
        }`

```
    var locationLayer = L.mapbox.featureLayer(location).addTo(map);
```

I have tested with a single point and multiple points in the same geojson and both cause this error.

**Comment by jfirebaugh** [comment]
Are you setting `L.mapbox.accessToken = <your access token>`? Can you share a JSFiddle that demonstrates the issue?

**Comment by tmcw** [comment]
Needs more details.
