### ISSUE TITLE
React.js support

### ISSUE THREAD

**Issue by mderazon** [mapbox/mapbox.js#951]
Any plan on supporting React.js ?

**Comment by tmcw** [comment]
You can certainly use Mapbox.js with React, and we do, often. Do you mean something like wrapping mapbox.js in a React component? That could also be neat.

**Comment by mderazon** [comment]
Yes, meant wrapping it in a component.

I wonder how are you using it with React, any code examples available ?

**Comment by tmcw** [comment]
Sure, here's [how I used Mapbox.js in coffeeedex](https://github.com/tmcw/coffeedex/blob/gh-pages/index.js#L419-L452): much the same flow as you'd use for integrating d3 or any other dom-manipulating library: prop up in componentDidMount, use a `ref` to find the map element, and update in `componentDidUpdate`.

**Comment by mderazon** [comment]
cool :+1:

**Comment by notpushkin** [comment]
@mderazon I'm writing a more configurable component for one of my current projects. Probably will release it as free/open source soon :)

(A sneak peek: https://gist.github.com/iamale/52b8d378cd4c4a23d765)

**Comment by mderazon** [comment]
@iamale that would be awesome. please update us if / when you do

**Comment by notpushkin** [comment]
@mderazon I've also found this: [react-leaflet](https://www.npmjs.com/package/react-leaflet)

**Comment by notpushkin** [comment]
@mderazon https://www.npmjs.com/package/react-mapboxmap! :)

**Comment by mderazon** [comment]
Thanks !

**Comment by j16h** [comment]
Working on the map component + markers. It's gonna be ready soon, you gonna find it here https://github.com/julianusti/react-mapbox, just watch it.

**Comment by notpushkin** [comment]
@julianusti FYI, there is a declarative component called [react-leaflet](https://www.npmjs.com/package/react-leaflet), I've mentioned it above.

**Comment by j16h** [comment]
@iamale oh, sorry I haven't seen. Is it also works with MapBox? Can I use it and have advantages of MapBox?

**Comment by notpushkin** [comment]
@julianusti It does work with Mapbox, although you'll have to specify the tiles URL by hand, like so:

``` js
var map = (<Map center={position} zoom={13}>
  <TileLayer
    url="http://api.tiles.mapbox.com/v4/<mapid>/{z}/{x}/{y}.png?access_token=<your access token>"
    attribution='<a href="https://www.mapbox.com/about/maps/" target="_blank">&copy; Mapbox &copy; OpenStreetMap</a> <a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a>'
  />
  <Marker position={position}>
    <Popup>
      <span>A pretty CSS3 popup.<br/>Easily customizable.</span>
    </Popup>
  </Marker>
</Map>);
```

What could have been done is some kind of abstraction layer, like `MapboxTileLayer` or so.

**Comment by j16h** [comment]
That looks great, thank you very much @iamale I'm gonna try to use it.

**Comment by tmcw** [comment]
👍 `react-leaflet` is the way to go for Mapbox maps in React land.

**Comment by hrahimi270** [comment]
Hi there.
Any update?
I want to use mapbox.js in my React project and I have some issues!
Look at this picture:
![image](https://user-images.githubusercontent.com/38007163/53267569-ec8d8e00-36f8-11e9-8656-a122eb354f8e.png)

Something is worng with my mapp :/
And this is my code:
![image](https://user-images.githubusercontent.com/38007163/53267704-48581700-36f9-11e9-8de3-2cfdef39516e.png)
