### ISSUE TITLE
divicon example is confusing

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox.js#952]
This is tricky for newbies: https://www.mapbox.com/mapbox.js/example/v1.0.0/divicon/

The math and the for loop get in the way of the basic lesson, which is that you can create HTML icons at specific locations and put them on your map.

**Comment by lyzidiamond** [comment]
:+1: strongly agree here.

What's the process for updating and adding examples?

**Comment by jfirebaugh** [comment]
See [DOCUMENTING.md](https://github.com/mapbox/mapbox.js/blob/mb-pages/DOCUMENTING.md) for details -- other than that feel free to dive in and JFDI!

**Comment by lyzidiamond** [comment]
@samanpwbb you wanna take this? i can do it otherwise

**Comment by samanpwbb** [comment]
All yours :+1:
