### ISSUE TITLE
example for firebase could use cleanup

### ISSUE THREAD

**Issue by pdgoodman** [mapbox/mapbox.js#965]
there are a few colorful labels on the firebase example in our docs - @tmcw can you point me to the credentials for ~~location~~ where these are stored w/in firebase so I can clean?

![image](https://cloud.githubusercontent.com/assets/851894/6543434/dffb2232-c4cf-11e4-83b4-613f8532b347.png)

**Comment by tmcw** [comment]
That's Free Speech in Action © - https://mapboxexample.firebaseio.com/ - the login is in Meldium

**Comment by tmcw** [comment]
Removed in https://github.com/mapbox/mapbox.js/commit/b99cfdab5b98de51612b406ea8274261e1a74429
