### ISSUE TITLE
Provide an all-in-one but non-minified version of mapbox.js?

### ISSUE THREAD

**Issue by hanfeisun** [mapbox/mapbox.js#966]
Currently I'm using    `<script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.js'></script>` to import mapbox.js. 

While this works well, it is an uglified version, which make it difficult to view the source code sometimes.. 

Another way seems to download the whole `mapbox.js` github repository, and import them locally, but this is still a bit time-costing.. I was wondering that whether it was possible to serve two js file, which are `mapbox.min.js` and `mapbox.js`...

**Comment by tmcw** [comment]
The uncompressed version of Mapbox.js lives at: https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.uncompressed.js
