### ISSUE TITLE
Use index as parameter of the callback function of `eachLayer` method?

### ISSUE THREAD

**Issue by hanfeisun** [mapbox/mapbox.js#967]
My jsfiddle can be viewed at http://jsfiddle.net/svgoz3z1/2/

It is based on the official example: https://www.mapbox.com/mapbox.js/example/v1.0.0/rotating-controlling-marker/

But I add another marker in the map, wrap two markers in a `L.featureGroup`, and then tried to use `eachLayer` method to operate these two markers separately..

However, I found those two marker alway moves to the same direction, though I expect them to behave different because they depends on two different random number..

Does that mean use `eachLayer()` here is not right?

**Comment by tmcw** [comment]
> However, I found those two marker alway moves to the same direction, though I expect them to behave different because they depends on two different random number..

This is incorrect: both layers depend on the `direction` variable: `var direction = 0`. If you want them to be separate, you'll need two directions variables, or to use an array. The `.eachLayer` method is working.

**Comment by hanfeisun** [comment]
I see~ I forgot the direction is variable outside of that scope, thanks!

**Comment by hanfeisun** [comment]
@tmcw 

By the way,  currently `eachLayer` is used like this:

```
            markerGroup.eachLayer(
                    function (marker) {
             )
```

Would it be possible to pass in a index for the parameter of the callback, like this?

```
            markerGroup.eachLayer(
                    function (marker, index) {
             )
```

This is related to my above case.. Because if I use an array to store directions for each layer, I might need to use the index of eachLayer to find its own `direction` in the array.

**Comment by tmcw** [comment]
Currently Leaflet doesn't expose that as an option, but it's simple to do otherwise:

``` js
var i = 0;
markerGroup.eachLayer(
                    function (marker) {
// do something with marker and i
i++;
             })
```
