### ISSUE TITLE
The direction API returns {lon},{lat} but L.polyline accepts {lat},{lon}

### ISSUE THREAD

**Issue by hanfeisun** [mapbox/mapbox.js#973]
I found the direction API (https://www.mapbox.com/developers/api/directions/) returns [[lon,lat]] in its `routes[0].geometry.coordinates`, which means that longitude first and latitude second. However, `L.polyline` needs a [[lat, lon]] as its first parameter, which has a different order from direction API..

Therefore, if I use `L.polyline(directionResult.routes[0].geometry.coordinates).addTo(map)`, the result is wrong. Isn't this unintuitive? Is there a better way to draw a polyline according to the waypoints of direction?

**Comment by tmcw** [comment]
You can use `L.mapbox.featureLayer` or `L.geoJson` with the output of the Directions API and it will do what you expect, or you can use the [mapbox-directions](https://github.com/mapbox/mapbox-directions.js) plugin and it will also do what you want.

The Directions API outputs [GeoJSON](http://geojson.org/), which has a lon, lat order, and Leaflet has a `lat, lon` order. It's an unfortunate mismatch but it is thoroughly documented on both sides and somewhat unavoidable at this point.

**Comment by hanfeisun** [comment]
I see, thanks!
