### ISSUE TITLE
Leaflet Circle Draw Issues with Included Version

### ISSUE THREAD

**Issue by sephcoster** [mapbox/mapbox.js#974]
When drawing circles with the same radius at the same latitude, the included version of Leaflet within Mapbox.js returns two circles of differing sizes - this occurs at zoom level 10 for the examples, but may occur at other zoom levels where rounding lat/long and projection is a factor.

This appears to be a problem with leaflet rounding and/or calculating incorrect radii based on projections which has been fixed in the latest development version of Leaflet

Version using all inclusive 2.1.5:
https://jsfiddle.net/sailfast/493pjygz/ (12x12 vs. 14x14 circles)

Version using Standalone.js and Leaflet 0.8dev:
https://jsfiddle.net/sailfast/4e12z3p9/9/ (both 10x10 circles)

I have re-worked my apps layer declarations to use the standalone version of Mapbox.js and the leaflet API but would much rather get the vector layer and syntactic goodness of an all-inclusive Mapbox package. Any idea when the latest Leaflet release will be incorporated?

Thanks!

**Comment by tmcw** [comment]
Mapbox.js is updated to 1.0.2 in its version 3.0.1.
