### ISSUE TITLE
bower 2.1.6 build broken

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox.js#976]
I've been informed that the new v2.1.6 bower build I pushed today is broken because it's missing a trailing semicolon here preventing nice concatenation (https://github.com/mapbox/mapbox.js-bower/blob/master/mapbox.js#L62).

I'll dig into what's up -- perhaps an upstream browserify change?

cc @tmcw

**Comment by yhahn** [comment]
Looks like the introduction of a sourcemap is what's causing the trailing ; to be removed. If I rollback to the commit prior to https://github.com/mapbox/mapbox.js/commit/b0bc95fbf73b0340e9a72f8d8cbdb59b1929d434 I can see the trailing semicolon return.

@jfirebaugh @tmcw please advise -- you can probably guess which way my moral compass leans on this one : P

**Comment by tmcw** [comment]
My morale compass broke so long ago. So,
- uglifyjs2, arguably the most-used code compressor, and the core of minifyify, does not append a trailing `;`

do you know what concatenation they're using? just `cat`? something else? basically like whatever they're using sounds like it's the deadly combination of
- minify (again), that will remove the // comment that would avoid this problem
- and then just smoosh together

because... that's a kind of cornery thing, and both grunt & gulp's concat tasks have configurable separators where you can throw in a `;`

**Comment by yhahn** [comment]
Poked @drewbo and @jflasher about this this morning -- it sounds like this might be more of an issue with the specific grunt concatenator they are using not being able to handle the output of browserify in this case.

@drewbo @jflasher could you reference the project you're using to bundle with here?

**Comment by jflasher** [comment]
@tmcw We're using https://github.com/yeoman/generator-backbone which is in turn using https://github.com/yeoman/grunt-usemin to handle the concat step.

**Comment by rdmurphy** [comment]
I'm also having this issue, but over in gulp. Using [`gulp-concat`](https://github.com/wearefractal/gulp-concat).

I've tried it with both `mapbox.js` and `mapbox.uncompressed.js` from this release and both throw the same error when used pre- and post-uglify (using [`gulp-uglify`](https://github.com/terinjokes/gulp-uglify)). It makes whatever comes after the concat'ed mapbox.js throw a `Cannot find module` error.

**Comment by tmcw** [comment]
Can you try something like

``` js
.pipe(concat('main.js', {newLine: ';'}))
```

as noted in the concat readme?

**Comment by rdmurphy** [comment]
Doh. I meant to say I did try that – except I just noticed I put the `{newLine: ';'}` in the `.pipe()` call, not the `concat()`.

After correcting that, it worked. :+1: Thanks @tmcw!

**Comment by tmcw** [comment]
Closing: this is handled by upstream tools.
