### ISSUE TITLE
Mapbox Directions API

### ISSUE THREAD

**Issue by shkfnly** [mapbox/mapbox.js#979]
Hey,

Is there a reason why the mapbox directions API returns the coordinates of the routes in [Longitude, Latitude] rather than [Latitude, Longitude]?

**Comment by jfirebaugh** [comment]
Yes: it returns GeoJSON objects, which are specified to be [lon, lat].

**Comment by duncangraham** [comment]
Hey @shkfnly here's the full spec for more details: http://geojson.org/geojson-spec.html
