### ISSUE TITLE
Path.onRemove throws error in IE when this._container is undefined

### ISSUE THREAD

**Issue by sbaggott** [mapbox/mapbox.js#980]
IE (tested on IE11/Win 8.1 and IE9/Win 7) throws a notFoundError when calling Path.onRemove() and this._container is undefined.

STR:
NOTE: this requires an account with Lookout with at least 2 devices on it (can be a free account).
1. Navigate to https://www.lookout.com/d#missingDevice in IE11 or IE9.
2. Select a different device from the dropdown menu (requires more than one device registered with Lookout):
![ie9_-_win7__running_](https://cloud.githubusercontent.com/assets/527856/7030626/c5560f4c-dd1a-11e4-8f3d-4ffc5102404d.png)
3. A notFoundError is thrown and the map breaks:
![error](https://cloud.githubusercontent.com/assets/527856/7030739/753fa2ec-dd1b-11e4-81d4-57ba0d54d575.png)

**Comment by tmcw** [comment]
Closing; stale as of Leaflet 1.0 switch.
