### ISSUE TITLE
provide portable build

### ISSUE THREAD

**Issue by urbanhop** [mapbox/mapbox.js#981]
Would like to debug mapbox.js.
Looks like to do so, I have to build ot from source.
Fine, but getting any sort of make (tried MinGW, GnuMake32, Cygwin) does not work.

Maybe you can get away from make in favor of a more cross platform tool or explain how one can build a debugable js library on Windows.

**Comment by jfirebaugh** [comment]
Mapbox.js on the Mapbox CDN (https://api.tiles.mapbox.com/mapbox.js/v2.1.7/mapbox.js) is supplied with a source map (https://api.tiles.mapbox.com/mapbox.js/v2.1.7/mapbox.js.map). You should be able to debug with the original source files in any modern browser.
