### ISSUE TITLE
featureLayer + custom points / styles example

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox.js#984]
/cc @lyzidiamond @katydecorah 

Been seeing an uptick in questions about this, and we don't have an example. Anyone want to build this - L.mapbox.featureLayer + pointToLayer usage?

**Comment by lyzidiamond** [comment]
We had a few conversations about this last week, particularly related to moving from editor to Mapbox.js. I can hit this example.

**Comment by lyzidiamond** [comment]
Related (note for syntax): #938

**Comment by geografa** [comment]
@tmcw can I use a map ID for the GeoJSON parameter or does this need an on ready function when using that?

**Comment by tmcw** [comment]
you can use a map id

Rule of thumb is
- pointToLayer & `on('layeradd'` work "as layers are added", so they are good to use regardless of when the data appears.
- eachLayer works **right now**, so it needs to be run on `ready` if the data is async.

**Comment by geografa** [comment]
Cool. just realized this doesn't make sense for an editor-made map since there's only title, desc so I'll stick with a inline GeoJSON example.
