### ISSUE TITLE
setZIndex() does not work on L.geoJson layers

### ISSUE THREAD

**Issue by MichaelMarkieta** [mapbox/mapbox.js#985]
Is there a fix for this?

**Comment by jfirebaugh** [comment]
Hi Michael -- can you be more specific? Please see http://www.macwright.org/report-a-bug/.

**Comment by MichaelMarkieta** [comment]
Sorry @jfirebaugh -- I understand.

I am wondering if there is fix for manually specifying or programmatically setting z-index of L.geoJson (or L.mapbox.featureLayer with geojson source).

The layers are drawn in the order at which they are added to the map. There are situations where being able to specify the z-index of a layer would be needed (e.g. one layer hides parts of another).

http://bl.ocks.org/MichaelMarkieta/e287fe4c51455e27de54

**Comment by jfirebaugh** [comment]
Ah, I see. `L.LayerGroup` defines `setZIndex` (as a `setZIndex` on each layer in the group that supports it), but the only layer type that does support it is `L.TileLayer`. So no, it isn't possible to reorder GeoJSON layers this way. This would be an upstream issue in Leaflet.

**Comment by MichaelMarkieta** [comment]
Thanks @jfirebaugh. Digging through the leaflet source to identify a refactor.
