### ISSUE TITLE
[enhancement] toGeoJSON store style data

### ISSUE THREAD

**Issue by 1c7** [mapbox/mapbox.js#988]
what I am trying to do is embed a Mapbox map on my page.
and any visitor can draw "PolyLine" and put "Marker" on map,
and click "save", save all these information.
even refresh page, these draw still exists on map.

by now, I know how to store GeoJSON into file.
and read them, and display on map.

**But**. GeoJSON didn't store style info,
so when I refresh, **everything become black color**.
and I have try to set color on these Marker and PolyLine again, after load GeoJSON.
but document didn't say how to do it. so I don't know how to change color.

**can you guys enhence toGeoJSON function? store style data too**
Thank you~
(if I have grammar error, please point out. thanks)

**Comment by tmcw** [comment]
The [GeoJSON](http://geojson.org/) standard does not include any rules for how geometries are styled, so the `toGeoJSON` method can't include anything that would style GeoJSON elsewhere. If you style features with the [simplestyle-spec](https://github.com/mapbox/simplestyle-spec) properties, then the output of toGeoJSON will (automatically & currently) include the necessary properties it needs to be styled, but styling features with Leaflet's methods does not & shouldn't change their GeoJSON content.

**Comment by 1c7** [comment]
Thank you
