### ISSUE TITLE
Is it possible to prefetch offscreen map tiles?

### ISSUE THREAD

**Issue by hy9be** [mapbox/mapbox.js#998]
I am trying to use mapbox in the map UI of my hybrid app (with ionic framework). But it looks on touch screen, users tend to pan the map fast and frequently. So the perceived performance would be significantly better, if we could have some prefetched base map tiles as the "buffer area" for the user interactions.

Currently, it is just so easy to see a blank and loading tile.

**Comment by tmcw** [comment]
The downside of loading tiles outside of the viewport is that you have a 1/4 chance of the user panning in a certain direction, and the increased number of requests tends to slow down the rest of the page. However, this feature is planned & tracked upstream in Leaflet, so closing this ticket in favor of https://github.com/Leaflet/Leaflet/issues/3087
